In [19]:
import http.client
import pandas as pd 
import json
import time, datetime
conn = http.client.HTTPSConnection("tefas-api.p.rapidapi.com")

headers = {
    'x-rapidapi-key': "c3c297e087mshf0c09b3c9068e2fp1ae78fjsnf0b02d992e8a",
    'x-rapidapi-host': "tefas-api.p.rapidapi.com"
}

date = datetime.datetime.now().strftime("%d.%m.%Y")
date
conn.request("GET", f"/api/v1/funds/historical?startDate={date}&fundType=1", headers=headers)

res = conn.getresponse()
data = res.read()
data = data.decode("utf-8")
data

'{"data":[],"success":true,"message":"Fund historical data retrieved successfully"}'

In [5]:
import datetime 

date = datetime.datetime.now().strftime("%Y-%m-%d")
date

'2025-10-25'

In [20]:
import http.client

conn = http.client.HTTPSConnection("tefas-api.p.rapidapi.com")

headers = {
    'x-rapidapi-key': "c3c297e087mshf0c09b3c9068e2fp1ae78fjsnf0b02d992e8a",
    'x-rapidapi-host': "tefas-api.p.rapidapi.com"
}

conn.request("GET", "/api/v1/funds", headers=headers)

res = conn.getresponse()
data = res.read()

print(data.decode("utf-8"))

{"data":[{"key":"AVJ","value":"AGESA EMEKLİLİK VE HAYAT A.Ş. BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU"},{"key":"AVY","value":"AGESA HAYAT VE EMEKLİLİK A.Ş.  KARMA GRUP EMEKLİLİK YATIRIM FONU"},{"key":"AVE","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU"},{"key":"EAE","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. ALTIN EMEKLİLİK YATIRIM FONU"},{"key":"GEV","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. ALTIN KATILIM EMEKLİLİK YATIRIM FONU"},{"key":"AHJ","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. BAŞLANGIÇ EMEKLİLİK YATIRIM FONU"},{"key":"AVH","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. BIST TEMETTÜ 25 ENDEKSİ EMEKLİLİK YATIRIM FONU"},{"key":"AE4","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. BİRİNCİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"},{"key":"MZN","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. BİRİNCİ FON SEPETİ EMEKLİLİK YATIRIM FONU"},{"key":"AE1","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. BİRİNCİ PARA PİYASASI EMEKLİLİK YATIRIM FONU"},{"key":"AE2","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU"},{"key":"AEK","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. BORÇLANMA ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU"},{"key":"AVP","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"},{"key":"AVG","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU"},{"key":"AE3","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU"},{"key":"ENF","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. ENERJİ SEKTÖRÜ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"},{"key":"AEH","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. HİSSE SENEDİ EMEKLİLİK YATIRIM FONU"},{"key":"AEB","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. HİSSE SENEDİ GRUP EMEKLİLİK YATIRIM FONU"},{"key":"AVU","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. İKİNCİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"},{"key":"MZL","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. İKİNCİ FON SEPETİ EMEKLİLİK YATIRIM FONU"},{"key":"AVL","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. İKİNCİ PARA PİYASASI EMEKLİLİK YATIRIM FONU"},{"key":"AVB","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. KAMU DIŞ BORÇLANMA ARAÇLARI (ABD DOLARI 5-15 YIL VADELİ) EMEKLİLİK YATIRIM FONU"},{"key":"AVD","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. KARMA EMEKLİLİK YATIRIM FONU"},{"key":"EHK","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. KATILIM HİSSE SENEDİ EMEKLİLİK YATIRIM FONU"},{"key":"FYL","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. KATILIM KATKI EMEKLİLİK YATIRIM FONU"},{"key":"FYN","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. KATILIM STANDART EMEKLİLİK YATIRIM FONU"},{"key":"AEI","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. KATKI EMEKLİLİK YATIRIM FONU"},{"key":"KML","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. KIYMETLİ MADENLER EMEKLİLİK YATIRIM FONU"},{"key":"AEG","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. MUHAFAZAKAR DEĞİŞKEN EMEKLİLİK YATIRIM FONU"},{"key":"VVA","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. OKS AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU"},{"key":"VVZ","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"},{"key":"VVE","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. OKS DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"},{"key":"VVD","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. OKS DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU"},{"key":"VVU","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. OKS DİNAMİK KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"},{"key":"AYJ","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU"},{"key":"VVM","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. OKS MUHAFAZAKAR DEĞİŞKEN EMEKLİLİK YATIRIM FONU"},{"key":"AAJ","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. OKS STANDART EMEKLİLİK YATIRIM FONU"},{"key":"AVK","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. ORTA VADELİ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU"},{"key":"AVO","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. ÖZEL SEKTÖR BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU"},{"key":"SBA","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. SABANCI TOPLULUĞU ŞİRKETLERİ ENDEKSİ EMEKLİLİK YATIRIM FONU"},{"key":"AVN","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. STANDART EMEKLİLİK YATIRIM FONU"},{"key":"GFH","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. SÜRDÜRÜLEBİLİRLİK HİSSE SENEDİ EMEKLİLİK YATIRIM FONU"},{"key":"TVC","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. TARIM VE GIDA SEKTÖRÜ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"},{"key":"TSZ","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. TAŞINMAZ VE İNŞAAT SEKTÖRÜ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"},{"key":"AVR","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. TEKNOLOJİ SEKTÖRÜ YABANCI DEĞİŞKEN EMEKLİLİK YATIRIM FONU"},{"key":"TVH","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. TEKNOLOJİ ŞİRKETLERİ HİSSE SENEDİ EMEKLİLİK YATIRIM FONU"},{"key":"MZP","value":"AGESA HAYAT VE EMEKLİLİK A.Ş. ÜÇÜNCÜ FON SEPETİ EMEKLİLİK YATIRIM FONU"},{"key":"CJF","value":"AK PORTFÖY ADOC SERBEST (DÖVİZ) ÖZEL FON"},{"key":"SSO","value":"AK PORTFÖY AK SANDIK SERBEST ÖZEL FON"},{"key":"PUD","value":"AK PORTFÖY AKY SERBEST (DÖVİZ) ÖZEL FON"},{"key":"FUM","value":"AK PORTFÖY ALESTA SERBEST (DÖVİZ) ÖZEL FON"},{"key":"ANL","value":"AK PORTFÖY ALTERNATİF BANK PARA PİYASASI (TL)FONU"},{"key":"AOY","value":"AK PORTFÖY ALTERNATİF ENERJİ YABANCI HİSSE SENEDİ FONU"},{"key":"AFO","value":"AK PORTFÖY ALTIN FONU"},{"key":"PAL","value":"AK PORTFÖY ALTINCI SERBEST(DÖVİZ) FON"},{"key":"AFA","value":"AK PORTFÖY AMERİKA YABANCI HİSSE SENEDİ FONU"},{"key":"AFV","value":"AK PORTFÖY AVRUPA YABANCI HİSSE SENEDİ FONU"},{"key":"AJL","value":"AK PORTFÖY BEŞİNCİ SERBEST (DÖVİZ) FON"},{"key":"BNC","value":"AK PORTFÖY BEŞİNCİ SERBEST FON"},{"key":"BND","value":"AK PORTFÖY BIST BANKA DIŞI LİKİT 10 ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU"},{"key":"ADP","value":"AK PORTFÖY BIST BANKA ENDEKSİ HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)"},{"key":"BLH","value":"AK PORTFÖY BIST LİKİT BANKA ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU"},{"key":"APJ","value":"AK PORTFÖY BIST ŞİRKETLERİ FON SEPETİ FONU"},{"key":"BDY","value":"AK PORTFÖY BIST 100 DIŞI ŞİRKETLER HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)"},{"key":"MDL","value":"AK PORTFÖY BIST 100 ENDEKSİ MODEL PORTFÖY  HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU"},{"key":"AKU","value":"AK PORTFÖY BIST 30 ENDEKSİ HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)"},{"key":"BOE","value":"AK PORTFÖY BIST 30 ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU"},{"key":"ABU","value":"AK PORTFÖY BİREBİR BANKACILIK DEĞİŞKEN ÖZEL FON"},{"key":"ARL","value":"AK PORTFÖY BİRİNCİ FON SEPETİ FONU"},{"key":"BHE","value":"AK PORTFÖY BİRİNCİ HİSSE SENEDİ SERBEST FON (HİSSE SENEDİ YOĞUN FON)"},{"key":"LTC","value":"AK PORTFÖY BİRİNCİ İSTATİSTİKSEL ARBİTRAJ HİSSE SENEDİ SERBEST FON (HİSSE SENEDİ YOĞUN FON)"},{"key":"CVE","value":"AK PORTFÖY BİRİNCİ KAMU BORÇLANMA ARAÇLARI (TL) ÖZEL FONU"},{"key":"PUC","value":"AK PORTFÖY BİRİNCİ KISA VADELİ SERBEST (TL)  FON"},{"key":"PUR","value":"AK PORTFÖY BİRİNCİ PARA PİYASASI SERBEST (TL) FON"},{"key":"URG","value":"AK PORTFÖY BİRİNCİ SERBEST (DÖVİZ) ÖZEL FON"},{"key":"BVC","value":"AK PORTFÖY BİRİNCİ SERBEST (TL) ÖZEL FON"},{"key":"BUY","value":"AK PORTFÖY BÜYÜYEN ŞİRKETLER HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)"},{"key":"VAY","value":"AK PORTFÖY DEĞER ODAKLI 100 ŞİRKETLERİ HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)"},{"key":"CJH","value":"AK PORTFÖY DOKUZUNCU SERBEST (DÖVİZ-AVRO) FON"},{"key":"DZS","value":"AK PORTFÖY DOKUZUNCU SERBEST FON"},{"key":"AJN","value":"AK PORTFÖY DÖRDÜNCÜ SERBEST (DÖVIZ) FON"},{"key":"DSH","value":"AK PORTFÖY DÖRDÜNCÜ SERBEST FON"},{"key":"VCY","value":"AK PORTFÖY ELEKTRİKLİ VE OTONOM ARAÇ TEKNOLOJİLERİ DEĞİŞKEN FON"},{"key":"EML","value":"AK PORTFÖY EMLAK SEKTÖRÜ DEĞİŞKEN FON"},{"key":"AVZ","value":"AK PORTFÖY EMS SERBEST ( DÖVİZ ) ÖZEL FON"},{"key":"KVT","value":"AK PORTFÖY ENERJİ ŞİRKETLERİ HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)"},{"key":"AKE","value":"AK PORTFÖY EUROBOND (AMERİKAN DOLARI) BORÇLANMA ARAÇLARI FONU"},{"key":"ZFB","value":"AK PORTFÖY FİNTEK VE BLOKZİNCİRİ TEKNOLOJİLERİ DEĞİŞKEN FON"},{"key":"UCN","value":"AK PORTFÖY FNM SERBEST ÖZEL FON"},{"key":"URV","value":"AK PORTFÖY GELİNCİK SERBEST ÖZEL FON"},{"key":"GUM","value":"AK PORTFÖY GÜMÜŞ FON SEPETI FONU"},{"key":"GMI","value":"AK PORTFÖY GÜMÜŞ SERBEST FON"},{"key":"HVV","value":"AK PORTFÖY HERAKLES SERBEST (DÖVİZ) ÖZEL FON"},{"key":"HYY","value":"AK PORTFÖY HERAKLES SERBEST ÖZEL FON"},{"key":"HZV","value":"AK PORTFÖY HEZ SERBEST ÖZEL FON"},{"key":"AK3","value":"AK PORTFÖY HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)"},{"key":"PAI","value":"AK PORTFÖY ING ÖZEL BANKACILIK VE PLATINUM MUTLAK GETİRİ HEDEFLİ DEĞİŞKEN ÖZEL FON"},{"key":"GNZ","value":"AK PORTFÖY ING Z KUŞAĞI FON SEPETİ ÖZEL FONU"},{"key":"FUA","value":"AK PORTFÖY İHRACATÇI ŞİRKETLER HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)"},{"key":"AGC","value":"AK PORTFÖY İKİNCİ DEĞİŞKEN FON"},{"key":"ARM","value":"AK PORTFÖY İKİNCİ FON SEPETİ FONU"},{"key":"BRR","value":"AK PORTFÖY İKİNCİ KISA VADELİ BORÇLANMA ARAÇLARI (TL) FONU"},{"key":"PPJ","value":"AK PORTFÖY İKİNCİ PARA PİYASASI SERBEST (TL) FON"},{"key":"CVB","value":"AK PORTFÖY İKİNCİ SERBEST (TL) ÖZEL FON"},{"key":"KUP","value":"AK PORTFÖY KAR PAYI ÖDEYEN SERBEST (DÖVİZ) FON"},{"key":"ALC","value":"AK PORTFÖY KAR PAYI ÖDEYEN ŞİRKETLER HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)"},{"key":"KH1","value":"AK PORTFÖY KATILIM HİSSE SENEDİ FONU (HİSSE SENEDİ YOĞUN FON)"},{"key":"KHO","value":"AK PORTFÖY KATILIM 30 ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU"},{"key":"AVT","value":"AK PORTFÖY KISA VADELİ BORÇLANMA ARAÇLARI (TL) FONU"},{"key":"GGC","value":"AK PORTFÖY KIYI SERBEST ÖZEL FON"},{"key":"KNP","value":"AK PORTFÖY KOR SERBEST (DÖVİZ) ÖZEL FON"},{"key":"ZLG","value":"AK PORTFÖY MARAL SERBEST (DÖVİZ) ÖZEL FON"},{"key":"MTV","value":"AK PORTFÖY METAVERSE VE DİJİTAL YAŞAM TEKNOLOJİLERİ DEĞİŞKEN FON"},{"key":"AIM","value":"AK PORTFÖY MİMKA SERBEST ÖZEL FON"},{"key":"PAP","value":"AK PORTFÖY MİSTRAL SERBEST(DÖVİZ) ÖZEL FON"},{"key":"KNZ","value":"AK PORTFÖY MNM SERBEST (DÖVİZ) ÖZEL FON"},{"key":"ADE","value":"AK PORTFÖY MUTLAK GETİRİ HEDEFLİ DEĞİŞKEN FON"},{"key":"MU1","value":"AK PORTFÖY MUTLAK GETİRİ HEDEFLİ HİSSE SENEDİ SERBEST FON (HİSSE SENEDİ YOĞUN FON)"},{"key":"LHM","value":"AK PORTFÖY NETA SERBEST (DÖVİZ) ÖZEL FON"},{"key":"OBN","value":"AK PORTFÖY ONBEŞİNCİ SERBEST (DÖVİZ) FON"},{"key":"OBR","value":"AK PORTFÖY ONBİRİNCİ SERBEST (DÖVİZ) FON"},{"key":"ODN","value":"AK PORTFÖY ONDÖRDÜNCÜ SERBEST (DÖVİZ) FON"},{"key":"ONK","value":"AK PORTFÖY ONİKİNCİ SERBEST (DÖVİZ-AVRO) FON"},{"key":"URC","value":"AK PORTFÖY ONUNCU SERBEST (DÖVİZ) FON"},{"key":"OSN","value":"AK PORTFÖY ONUNCU SERBEST FON"},{"key":"OUN","value":"AK PORTFÖY ONÜÇÜNCÜ SERBEST (DÖVİZ) FON"},{"key":"KNV","value":"AK PORTFÖY OPERA SERBEST (DÖVİZ) ÖZEL FON"},{"key":"URS","value":"AK PORTFÖY ORKİDE SERBEST ÖZEL FON"},{"key":"APT","value":"AK PORTFÖY ORTA VADELI BORÇLANMA ARAÇLARI FONU"},{"key":"URM","value":"AK PORTFÖY ÖPY ALTINCI SERBEST (DÖVİZ) ÖZEL FON"},{"key":"OPZ","value":"AK PORTFÖY ÖPY ALTINCI SERBEST ÖZEL FON"},{"key":"PUT","value":"AK PORTFÖY ÖPY BEŞİNCİ SERBEST ÖZEL FON"},{"key":"ARP","value":"AK PORTFÖY ÖPY BİRİNCİ SERBEST ÖZEL FON"},{"key":"CVD","value":"AK PORTFÖY ÖPY DÖRDÜNCÜ SERBEST (DÖVİZ) ÖZEL FON"},{"key":"ARF","value":"AK PORTFÖY ÖPY İKİNCİ SERBEST (TL) ÖZEL FON"},{"key":"CVC","value":"AK PORTFÖY ÖPY KAR PAYI ÖDEYEN SERBEST ÖZEL FON"},{"key":"AZZ","value":"AK PORTFÖY ÖPY MUTLAK GETİRİ HEDEFLİ SERBEST (DÖVİZ) ÖZEL FON"},{"key":"UHV","value":"AK PORTFÖY ÖPY SEKİZİNCİ SERBEST (DÖVİZ) ÖZEL FON"},{"key":"KNC","value":"AK PORTFÖY ÖPY ÜÇÜNCÜ SERBEST (DÖVİZ) ÖZEL FON"},{"key":"UHN","value":"AK PORTFÖY ÖPY YEDİNCİ SERBEST (DÖVİZ-AVRO) ÖZEL FON"},{"key":"BVB","value":"AK PORTFÖY ÖPY YEDİNCİ SERBEST (TL) ÖZEL FON"},{"key":"AYR","value":"AK PORTFÖY ÖZEL SEKTÖR BORÇLANMA ARAÇLARI (TL) FONU"},{"key":"AIS","value":"AK PORTFÖY PARA PİYASASI KATILIM FONU"},{"key":"ALE","value":"AK PORTFÖY PARA PİYASASI (TL) FONU"},{"key":"AES","value":"AK PORTFÖY PETROL YABANCI BYF FON SEPETİ FONU"},{"key":"PUV","value":"AK PORTFÖY PRUVA SERBEST (DÖVİZ) ÖZEL FON"},{"key":"AZF","value":"AK PORTFÖY PY ÖZEL SEKTÖR BORÇLANMA ARAÇLARI (TL) ÖZEL FONU"},{"key":"APP","value":"AK PORTFÖY P1 SERBEST ÖZEL FON"},{"key":"DTZ","value":"AK PORTFÖY ROBOTİK TEKNOLOJİLER DEĞİŞKEN FON"},{"key":"AIH","value":"AK PORTFÖY RTH SERBEST ÖZEL FON"},{"key":"SAS","value":"AK PORTFÖY SABANCI TOPLULUĞU ŞİRKETLERİ ENDEKSİ HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)"},{"key":"AFS","value":"AK PORTFÖY SAĞLIK SEKTÖRÜ YABANCI HİSSE SENEDİ FONU"},{"key":"CJG","value":"AK PORTFÖY SDSD SERBEST (DÖVİZ) ÖZEL FON"},{"key":"CJD","value":"AK PORTFÖY SEKİZİNCİ SERBEST (DÖVİZ) FON"},{"key":"SCZ","value":"AK PORTFÖY SEKİZİNCİ SERBEST FON"},{"key":"CVF","value":"AK PORTFÖY SÜRDÜRÜLEBİLİRLİK SERBEST (TL) ÖZEL FON"},{"key":"SAP","value":"AK PORTFÖY ŞEKERBANK PARA PİYASASI (TL) FONU"},{"key":"TAR","value":"AK PORTFÖY TARIM VE GIDA TEKNOLOJİLERİ DEĞİŞKEN FON"},{"key":"ICZ","value":"AK PORTFÖY TEKNOLOJİ ŞİRKETLERİ HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)"},{"key":"TGR","value":"AK PORTFÖY TURİZM VE SEYAHAT SEKTÖRÜ DEĞİŞKEN FON"},{"key":"AK2","value":"AK PORTFÖY UZUN VADELİ BORÇLANMA ARAÇLARI FONU"},{"key":"AUV","value":"AK PORTFÖY UZUN VADELİ SERBEST (DÖVİZ) FON"},{"key":"ODV","value":"AK PORTFÖY ÜÇÜNCÜ FON SEPETİ FONU"},{"key":"CVA","value":"AK PORTFÖY ÜÇÜNCÜ KAMU BORÇLANMA ARAÇLARI (TL) ÖZEL FONU"},{"key":"BGP","value":"AK PORTFÖY ÜÇÜNCÜ PARA PİYASASI (TL) FONU"},{"key":"AJE","value":"AK PORTFÖY ÜÇÜNCÜ SERBEST ( DÖVİZ ) FON"},{"key":"KNT","value":"AK PORTFÖY VİRA SERBEST (DÖVİZ) ÖZEL FON"},{"key":"LHP","value":"AK PORTFÖY YEDİNCİ SERBEST (DÖVİZ) FON"},{"key":"YDH","value":"AK PORTFÖY YEDİNCİ SERBEST FON"},{"key":"AFT","value":"AK PORTFÖY YENİ TEKNOLOJİLER YABANCI HİSSE SENEDİ FONU"},{"key":"ICI","value":"AK PORTFÖY YÖNETIMI A.Ş.İKİNCİ GİRİŞİM SERMAYESİ YATIRIM FONU"},{"key":"AK5","value":"AK PORTFÖY YÖNETİMİ A.Ş. AKBANK VENTURE BUİLDER ÖZEL GİRİŞİM SERMAYESİ YATIRIM FONU"},{"key":"BGY","value":"AK PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ GAYRİMENKUL YATIRIM FONU"},{"key":"AK4","value":"AK PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ TEKNOLOJİ GİRİŞİM SERMAYESİ YATIRIM FONU"},{"key":"IDG","value":"AK PORTFÖY YÖNETİMİ A.Ş. DÖRDÜNCÜ GAYRİMENKUL YATIRIM FONU"},{"key":"DDN","value":"AK PORTFÖY YÖNETİMİ A.Ş. DÖRDÜNCÜ GİRİŞİM SERMAYESİ YATIRIM FONU"},{"key":"IJG","value":"AK PORTFÖY YÖNETİMİ A.Ş. JEC YENİLENEBİLİR ENERJİ ÖZEL GİRİŞİM SERMAYESİ YATIRIM FONU"},{"key":"JST","value":"AK PORTFÖY YÖNETİMİ A.Ş. J-START ÖZEL GİRİŞİM SERMAYESİ YATIRIM FONU"},{"key":"SGF","value":"AK PORTFÖY YÖNETİMİ A.Ş. SOFAZ ÖZEL GAYRİMENKUL YATIRIM FONU"},{"key":"IUG","value":"AK PORTFÖY YÖNETİMİ A.Ş. ÜÇÜNCÜ GİRİŞİM SERMAYESİ YATIRIM FONU"},{"key":"TAV","value":"AK PORTFÖY YÖNETİMİ A.Ş.AGESA EMEKLİLİK TEKNOLOJİ GİRİŞİM SERMAYESİ YATIRIM FONU"},{"key":"AGN","value":"AK PORTFÖY YÖNETİMİ A.Ş.BİRİNCİ GİRİŞİM SERMAYESİ YATIRIM FONU"},{"key":"BYG","value":"AK PORTFÖY YÖNETİMİ A.Ş.BİRİNCİ YENİLENEBİLİR ENERJİ GİRİŞİM SERMAYESİ YATIRIM FONU"},{"key":"IKG","value":"AK PORTFÖY YÖNETİMİ A.Ş.İKİNCİ GAYRİMENKUL YATIRIM FONU"},{"key":"SHG","value":"AK PORTFÖY YÖNETİMİ A.Ş.SABANCI HOLDİNG ÖZEL GİRİŞİM SERMAYESİ YATIRIM FONU"},{"key":"AJK","value":"AK PORTFÖY 0-5 YIL VADELİ SERBEST (DÖVİZ) FON"},{"key":"YRB","value":"AK PORTFÖY 2025 SERBEST (DÖVİZ) FON"},{"key":"SDA","value":"AK PORTFÖY 2026 SERBEST (DÖVİZ) FON"},{"key":"CYD","value":"AK PORTFÖY 2027 SERBEST (DÖVİZ-AVRO) FON"},{"key":"SER","value":"AK PORTFÖY 2028 SERBEST (DÖVİZ) FON"},{"key":"COT","value":"AK PORTFÖY 2030 SERBEST (DÖVİZ-AVRO) FON"},{"key":"AB1","value":"AKFEN GAYRİMENKUL VE GİRİŞİM SERMAYESİ PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ GAYRİMENKUL YATIRIM FONU"},{"key":"ONN","value":"AKTİF PORTFÖY AKTİF ONİKS SERBEST (TL) FON"},{"key":"DSU","value":"AKTİF PORTFÖY AKTİF SERBEST (DÖVİZ - ABD DOLARI) FON"},{"key":"MPD","value":"AKTİF PORTFÖY AKTİF SERBEST (DÖVİZ) FON"},{"key":"MJL","value":"AKTİF PORTFÖY AKTİF SERBEST (DÖVİZ-AVRO) FON"},{"key":"MKG","value":"AKTİF PORTFÖY ALTIN KATILIM FONU"},{"key":"YBJ","value":"AKTİF PORTFÖY AYBÜKE SERBEST (DÖVİZ) ÖZEL FON"},{"key":"HRZ","value":"AKTİF PORTFÖY BIST HALKA ARZ ŞİRKETLERİ HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)"},{"key":"MMH","value":"AKTİF PORTFÖY BIST 30 ENDEKSİ HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)"},{"key":"MJB","value":"AKTİF PORTFÖY BİRİNCİ FON SEPETİ FONU"},{"key":"ONE","value":"AKTİF PORTFÖY BİRİNCİ HİSSE SENEDİ SERBEST (TL) FON (HİSSE SENEDİ YOĞUN FON)"},{"key":"CIN","value":"AKTİF PORTFÖY BİRİNCİ SERBEST FON"},{"key":"BOL","value":"AKTİF PORTFÖY BORÇLANMA ARAÇLARI FONU"},{"key":"GLG","value":"AKTİF PORTFÖY CAPİTAL HİSSE SENEDİ SERBEST FON (HİSSE SENEDİ YOĞUN FON)"},{"key":"ENJ","value":"AKTİF PORTFÖY ENERJİ ŞİRKETLERİ HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)"},{"key":"ESG","value":"AKTİF PORTFÖY ESG SÜRDÜRÜLEBİLİRLİK SERBEST FON"},{"key":"MJH","value":"AKTİF PORTFÖY FORTUNA SERBEST FON"},{"key":"MJG","value":"AKTİF PORTFÖY GÜMÜŞ FON SEPETİ FONU"},{"key":"FLY","value":"AKTİF PORTFÖY HAVACILIK VE SAVUNMA TEKNOLOJİLERİ DEĞİŞKEN FON"},{"key":"ASJ","value":"AKTİF PORTFÖY HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)"},{"key":"MPN","value":"AKTİF PORTFÖY İKİNCİ AKTİF SERBEST (DÖVİZ) FON"},{"key":"EYT","value":"AKTİF PORTFÖY İKİNCİ FON SEPETİ FONU"},{"key":"DB2","value":"AKTİF PORTFÖY İKİNCİ KISA VADELİ SERBEST (TL) FON"},{"key":"LKT","value":"AKTİF PORTFÖY İKİNCİ PARA PİYASASI (TL) FONU"},{"key":"BUL","value":"AKTİF PORTFÖY İNŞAAT SEKTÖRÜ HİSSE SENEDİ SERBEST (TL) FON (HİSSE SENEDİ YOĞUN FON)"},{"key":"SPT","value":"AKTİF PORTFÖY KATILIM FON SEPETİ FONU"},{"key":"MPS","value":"AKTİF PORTFÖY KATILIM HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)"},{"key":"MPF","value":"AKTİF PORTFÖY KISA VADELİ KİRA SERTİFİKASI KATILIM (TL) FONU"},{"key":"NKL","value":"AKTİF PORTFÖY KISA VADELİ SERBEST (TL) FON"},{"key":"MPK","value":"AKTİF PORTFÖY KİRA SERTİFİKASI KATILIM (TL) FONU"},{"key":"TLK","value":"AKTİF PORTFÖY PARA PİYASASI KATILIM (TL) FONU"},{"key":"PPV","value":"AKTİF PORTFÖY PARA PİYASASI SERBEST (TL) FON"},{"key":"IDL","value":"AKTİF PORTFÖY PARA PİYASASI (TL) FONU"},{"key":"GPT","value":"AKTİF PORTFÖY ROBOTİK TEKNOLOJİLERİ DEĞİŞKEN FON"},{"key":"MLS","value":"AKTİF PORTFÖY SİYAH BEYAZ SERBEST ÖZEL FON"},{"key":"MTS","value":"AKTİF PORTFÖY TARIM VE SÜRDÜRÜLEBİLİRLİK FON SEPETİ FONU"},{"key":"CPU","value":"AKTİF PORTFÖY TEKNOLOJİ KATILIM FONU"},{"key":"TFE","value":"AKTİF PORTFÖY TÜRKİYE FİNANS ALA BANKACILIK KATILIM ÖZEL FONU"},{"key":"DOL","value":"AKTİF PORTFÖY ÜÇÜNCÜ AKTİF SERBEST (DÖVİZ) FON"},{"key":"GLC","value":"AKTİF PORTFÖY ÜÇÜNCÜ FON SEPETİ FONU"},{"key":"MPT","value":"AKTİF PORTFÖY YÖNETİMİ A.Ş. AKTİF VENTURES GİRİŞİM SERMAYESİ YATIRIM FONU"},{"key":"LTI","value":"AKTİF PORTFÖY YÖNETİMİ A.Ş. ALTINCI GİRİŞİM SERMAYESİ YATIRIM FONU"},{"key":"MGA","value":"AKTİF PORTFÖY YÖNETİMİ A.Ş. BİRİNCİ GAYRİMENKUL YATIRIM FONU"},{"key":"MBB","value":"AKTİF PORTFÖY YÖNETİMİ A.Ş. BUKET GİRİŞİM SERMAYESİ YATIRIM FONU"},{"key":"FUT","value":"AKTİF PORTFÖY YÖNETİMİ A.Ş. FUTUREBRİGHT GİRİŞİM SERMAYESİ YATIRIM FONU"},{"key":"HMN","value":"AKTİF PORTFÖY YÖNETİMİ A.Ş. HUMANİS GİRİŞİM SERMAYESİ YATIRIM FONU"},{"key":"MPG","value":"AKTİF PORTFÖY YÖNETİMİ A.Ş. İKİNCİ GAYRİMENKUL YATIRIM (TL) FONU"},{"key":"MBK","value":"AKTİF PORTFÖY YÖNETİMİ A.Ş. MİNDVEST GİRİŞİM SERMAYESİ YATIRIM FONU"},{"key":"NKB","value":"AKTİF PORTFÖY YÖNETİMİ A.Ş. NKOLAY EV BEŞİKTAŞ KATILIM GAYRİMENKUL YATIRIM FONU"},{"key":"NEV","value":"AKTİF PORTFÖY YÖNETİMİ A.Ş. NKOLAY EV KADIKÖY KATILIM GAYRİMENKUL YATIRIM FONU"},{"key":"NKE","value":"AKTİF PORTFÖY YÖNETİMİ A.Ş. NKOLAY EV KATILIM GAYRİMENKUL YATIRIM FONU"},{"key":"PLY","value":"AKTİF PORTFÖY YÖNETİMİ A.Ş. PLAYGATE GİRİŞİM SERMAYESİ YATIRIM FONU"},{"key":"SGS","value":"AKTİF PORTFÖY YÖNETİMİ A.Ş. SEKİZİNCİ GİRİŞİM SERMAYESİ YATIRIM FONU"},{"key":"STO","value":"AKTİF PORTFÖY YÖNETİMİ A.Ş. STARTUPFON OPPORTUNITY GİRİŞİM SERMAYESİ YATIRIM FONU"},{"key":"MUG","value":"AKTİF PORTFÖY YÖNETİMİ A.Ş. ÜÇÜNCÜ GAYRİMENKUL YATIRIM FONU"},{"key":"MYP","value":"AKTİF PORTFÖY YÖNETİMİ A.Ş. YAPRAK YENİLENEBİLİR ENERJİ GİRİŞİM SERMAYESİ YATIRIM FONU"},{"key":"AG8","value":"ALBARAKA  PORTFÖ

In [21]:
import http.client

conn = http.client.HTTPSConnection("tefas-api.p.rapidapi.com")

headers = {
    'x-rapidapi-key': "c3c297e087mshf0c09b3c9068e2fp1ae78fjsnf0b02d992e8a",
    'x-rapidapi-host': "tefas-api.p.rapidapi.com"
}

conn.request("GET", "/api/v1/funds/periodic-top-earners", headers=headers)

res = conn.getresponse()
data = res.read()

print(data.decode("utf-8"))

{"data":{"weekly":[{"name":"Hisse Senedi Şemsiye Fonu","funds_count":167,"sector_volume":"161.406.696.264,59","y":1.9028,"id":"104","funds":[{"id":"TEB PORTFÖY BIST BANKA ENDEKSİ HİSSE SENEDİ FONU (HİSSE SENEDİ YOĞUN)","code":"YZH","value":5.3649},{"id":"PHİLLİP PORTFÖY BİRİNCİ HİSSE SENEDİ FONU (HİSSE SENEDİ YOĞUN FON)","code":"PPB","value":5.3344},{"id":"TERA PORTFÖY HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","code":"THF","value":5.3227},{"id":"AK PORTFÖY BIST BANKA ENDEKSİ HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","code":"ADP","value":5.1784},{"id":"İŞ PORTFÖY BIST BANKA ENDEKSİ HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","code":"TAU","value":5.1572}]},{"name":"Serbest Şemsiye Fonu","funds_count":1231,"sector_volume":"4.745.029.433.770,76","y":1.0767,"id":"108","funds":[{"id":"HEDEF PORTFÖY DOĞU HİSSE SENEDİ SERBEST (TL) FON (HİSSE SENEDİ YOĞUN FON)","code":"HDH","value":35.2518},{"id":"PUSULA PORTFÖY GÜNEY HİSSE SENEDİ SERBEST (TL) FON (HİSSE SENEDİ YOĞUN FON)","code":"PGH","value":33.5955},{"id":"HEDEF PORTFÖY ECE HİSSE SENEDİ SERBEST (TL) FON (HİSSE SENEDİ YOĞUN FON)","code":"HVA","value":33.5156},{"id":"PUSULA PORTFÖY ÜÇÜNCÜ HİSSE SENEDİ SERBEST FON (HİSSE SENEDİ YOĞUN FON)","code":"PCS","value":33.0691},{"id":"MT PORTFÖY ALTINCI HİSSE SENEDİ SERBEST FON (HİSSE SENEDİ YOĞUN FON)","code":"MT6","value":26.9537}]},{"name":"Para Piyasası Şemsiye Fonu","funds_count":74,"sector_volume":"1.310.220.361.483,16","y":0.7694,"id":"107","funds":[{"id":"PUSULA PORTFÖY PARA PİYASASI (TL) FONU","code":"PRY","value":0.914},{"id":"MT PORTFÖY PARA PİYASASI (TL) FONU","code":"MPL","value":0.8852},{"id":"AURA PORTFÖY PARA PİYASASI (TL) FONU","code":"PRH","value":0.8841},{"id":"TERA PORTFÖY PARA PİYASASI (TL) FONU","code":"TP2","value":0.8655},{"id":"FONERİA PORTFÖY PARA PİYASASI (TL) FONU","code":"GO6","value":0.8625}]},{"name":"Borçlanma Araçları Şemsiye Fonu","funds_count":83,"sector_volume":"159.526.328.983,23","y":0.766,"id":"100","funds":[{"id":"TERA PORTFÖY BİRİNCİ BORÇLANMA ARAÇLARI (TL) FONU","code":"TRJ","value":1.2961},{"id":"TEB PORTFÖY BORÇLANMA ARAÇLARI FONU","code":"TBT","value":1.0716},{"id":"YAPI KREDİ PORTFÖY EUROBOND (DOLAR) BORÇLANMA ARAÇLARI FONU","code":"YBE","value":1.0485},{"id":"FİBA PORTFÖY BORÇLANMA ARAÇLARI (TL) FONU","code":"FIT","value":0.9246},{"id":"AZİMUT PYŞ BİRİNCİ BORÇLANMA ARAÇLARI FONU","code":"GTF","value":0.9093}]},{"name":"Değişken Şemsiye Fonu","funds_count":150,"sector_volume":"71.846.443.954,55","y":0.6665,"id":"101","funds":[{"id":"DENİZ PORTFÖY TEMETTÜ ÖDEYEN ŞİRKETLER DEĞİŞKEN FON","code":"DTM","value":3.9943},{"id":"INVEO PORTFÖY BİRİNCİ DEĞİŞKEN FON","code":"GPG","value":3.2734},{"id":"GARANTİ PORTFÖY AGRESİF DEĞİŞKEN FON","code":"TGA","value":3.0086},{"id":"NEO PORTFÖY İKİNCİ DEĞİŞKEN FON","code":"NZH","value":2.994},{"id":"NEO PORTFÖY BİRİNCİ DEĞİŞKEN FON","code":"NRC","value":2.9908}]},{"name":"Katılım Şemsiye Fonu","funds_count":84,"sector_volume":"300.512.881.314,64","y":0.4843,"id":"114","funds":[{"id":"KUVEYT TÜRK PORTFÖY ENERJİ KATILIM FONU","code":"KNJ","value":3.2711},{"id":"HEDEF PORTFÖY ALTIN KATILIM FONU","code":"HAM","value":1.4491},{"id":"ZİRAAT PORTFÖY AGRESİF KATILIM FONU","code":"ZCK","value":1.0849},{"id":"ZİRAAT PORTFÖY ALTIN KATILIM FONU","code":"TCA","value":1.0306},{"id":"KUVEYT TÜRK PORTFÖY İKİNCİ SEPET HESAP PARA PİYASASI KATILIM FONU","code":"ZA2","value":1.0253}]},{"name":"Kıymetli Madenler Şemsiye Fonu","funds_count":22,"sector_volume":"171.667.588.027,35","y":0.1545,"id":"105","funds":[{"id":"TRIVE PORTFÖY ALTIN FONU","code":"TRO","value":0.9029},{"id":"INVEO PORTFÖY ALTIN FON","code":"GGK","value":0.8464},{"id":"ATLAS PORTFÖY ALTIN KATILIM FONU","code":"TAL","value":0.7479},{"id":"NEO PORTFÖY ALTIN FONU","code":"NAU","value":0.7246},{"id":"FİBA PORTFÖY ALTIN FONU","code":"FIB","value":0.7}]},{"name":"Karma Şemsiye Fonu","funds_count":7,"sector_volume":"4.662.461.371,19","y":-0.0693,"id":"110","funds":[{"id":"YAPI KREDİ PORTFÖY KARMA FON","code":"YAK","value":1.3244},{"id":"İŞ PORTFÖY SAĞLIK ŞİRKETLERİ KARMA FON","code":"IKL","value":1.3003},{"id":"İŞ PORTFÖY TEKNOLOJİ KARMA FON","code":"ITP","value":0.1531},{"id":"İŞ PORTFÖY DİJİTAL OYUN SEKTÖRÜ KARMA FON","code":"IJB","value":0.0734},{"id":"İŞ PORTFÖY ELEKTRİKLİ ARAÇLAR KARMA FON","code":"IPJ","value":-0.1828}]},{"name":"Fon Sepeti Şemsiye Fonu","funds_count":84,"sector_volume":"86.110.255.946,74","y":-0.1685,"id":"102","funds":[{"id":"AK PORTFÖY PETROL YABANCI BYF FON SEPETİ FONU","code":"AES","value":4.4773},{"id":"İSTANBUL PORTFÖY BİRİNCİ FON SEPETİ FONU","code":"IRF","value":2.5254},{"id":"PHİLLİP PORTFÖY FON SEPETİ FONU","code":"PFO","value":2.3452},{"id":"AK PORTFÖY BIST ŞİRKETLERİ FON SEPETİ FONU","code":"APJ","value":2.1825},{"id":"DENİZ PORTFÖY ESG-SÜRDÜRÜLEBİLİRLİK FON SEPETİ FONU","code":"DHM","value":1.9586}]}],"monthly":[{"name":"Kıymetli Madenler Şemsiye Fonu","funds_count":22,"sector_volume":"171.667.588.027,35","y":13.62,"id":"105","funds":[{"id":"BULLS PORTFÖY ALTIN FONU","code":"BLT","value":17.1},{"id":"ÜNLÜ PORTFÖY ALTIN FONU","code":"UP1","value":15.2504},{"id":"INVEO PORTFÖY ALTIN FON","code":"GGK","value":14.7327},{"id":"ICBC TURKEY PORTFÖY ALTIN FONU","code":"ICA","value":14.5514},{"id":"PHİLLİP PORTFÖY ALTIN FONU","code":"PTN","value":14.4534}]},{"name":"Katılım Şemsiye Fonu","funds_count":80,"sector_volume":"300.512.881.314,64","y":4.1229,"id":"114","funds":[{"id":"HEDEF PORTFÖY ALTIN KATILIM FONU","code":"HAM","value":16.1812},{"id":"FONMAP PORTFÖY ALTIN KATILIM FONU","code":"FAK","value":15.7379},{"id":"ZİRAAT PORTFÖY ALTIN KATILIM FONU","code":"TCA","value":15.2097},{"id":"RE-PIE PORTFÖY ALTIN KATILIM FONU","code":"RJG","value":15.183},{"id":"KUVEYT TÜRK PORTFÖY ALTIN KATILIM FONU","code":"KZL","value":14.9033}]},{"name":"Para Piyasası Şemsiye Fonu","funds_count":72,"sector_volume":"1.310.220.361.483,16","y":3.4084,"id":"107","funds":[{"id":"TERA PORTFÖY PARA PİYASASI (TL) FONU","code":"TP2","value":3.9148},{"id":"AURA PORTFÖY PARA PİYASASI (TL) FONU","code":"PRH","value":3.9113},{"id":"PUSULA PORTFÖY PARA PİYASASI (TL) FONU","code":"PRY","value":3.9062},{"id":"MT PORTFÖY PARA PİYASASI (TL) FONU","code":"MPL","value":3.8331},{"id":"FONERİA PORTFÖY PARA PİYASASI (TL) FONU","code":"GO6","value":3.8033}]},{"name":"Fon Sepeti Şemsiye Fonu","funds_count":84,"sector_volume":"86.110.255.946,74","y":2.5809,"id":"102","funds":[{"id":"OYAK PORTFÖY KIYMETLİ MADENLER FON SEPETİ FONU","code":"OTJ","value":12.8704},{"id":"YAPI KREDİ PORTFÖY GÜMÜŞ FON SEPETİ FONU","code":"YZG","value":12.0305},{"id":"AK PORTFÖY GÜMÜŞ FON SEPETI FONU","code":"GUM","value":11.9712},{"id":"DENİZ PORTFÖY GÜMÜŞ FON SEPETİ FONU","code":"DMG","value":11.4399},{"id":"TEB PORTFÖY GÜMÜŞ FON SEPETİ FONU","code":"GMC","value":11.3427}]},{"name":"Borçlanma Araçları Şemsiye Fonu","funds_count":82,"sector_volume":"159.526.328.983,23","y":2.5185,"id":"100","funds":[{"id":"TERA PORTFÖY BİRİNCİ BORÇLANMA ARAÇLARI (TL) FONU","code":"TRJ","value":3.9506},{"id":"NUROL PORTFÖY BİRİNCİ BORÇLANMA ARAÇLARI FONU","code":"NJR","value":3.7504},{"id":"YAPI KREDİ PORTFÖY ÇALIŞAN HESAP KISA VADELİ BORÇLANMA ARAÇLARI FONU","code":"YDK","value":3.7034},{"id":"ICBC TURKEY PORTFÖY BİRİNCİ KISA VADELİ BORÇLANMA ARAÇLARI (TL) FONU","code":"IFV","value":3.6612},{"id":"AK PORTFÖY ÜÇÜNCÜ KAMU BORÇLANMA ARAÇLARI (TL) ÖZEL FONU","code":"CVA","value":3.5386}]},{"name":"Karma Şemsiye Fonu","funds_count":7,"sector_volume":"4.662.461.371,19","y":2.1606,"id":"110","funds":[{"id":"İŞ PORTFÖY SAĞLIK ŞİRKETLERİ KARMA FON","code":"IKL","value":6.0578},{"id":"İŞ PORTFÖY ELEKTRİKLİ ARAÇLAR KARMA FON","code":"IPJ","value":5.2253},{"id":"İŞ PORTFÖY YENİLENEBİLİR ENERJİ KARMA FON","code":"IKP","value":3.4711},{"id":"İŞ PORTFÖY TEKNOLOJİ KARMA FON","code":"ITP","value":1.8181},{"id":"İŞ PORTFÖY BLOCKCHAİN TEKNOLOJİLERİ KARMA FON","code":"IJP","value":1.396}]},{"name":"Serbest Şemsiye Fonu","funds_count":1209,"sector_volume":"4.745.029.433.770,76","y":1.3908,"id":"108","funds":[{"id":"ALLBATROSS PORTFÖY ALGORİTMİK STRATEJİLER SERBEST FON","code":"STM","value":196.1974},{"id":"PUSULA PORTFÖY DÖRDÜNCÜ HİSSE SENEDİ SERBEST (TL) FON (HİSSE SENEDİ YOĞUN FON)","code":"PDC","value":111.8105},{"id":"HEDEF PORTFÖY DOĞU HİSSE SENEDİ SERBEST (TL) FON (HİSSE SENEDİ YOĞUN FON)","code":"HDH","value":105.0549},{"id":"PUSULA PORTFÖY GÜNEY HİSSE SENEDİ SERBEST (TL) FON (HİSSE SENEDİ YOĞUN FON)","code":"PGH","value":101.9977},{"id":"BULLS PORTFÖY DÖRDÜNCÜ HİSSE SENEDİ SERBEST FON (HİSSE SENEDİ YOĞUN FON)","code":"BDO","value":100.2604}]},{"name":"Değişken Şemsiye Fonu","funds_count":150,"sector_volume":"71.846.443.954,55","y":0.3188,"id":"101","funds":[{"id":"ROTA PORTFÖY İLAÇ VE MEDİKAL TEKNOLOJİLERİ DEĞİŞKEN FON","code":"RPM","value":12.8855},{"id":"ROTA PORTFÖY İKİNCİ DEĞİŞKEN FON","code":"RKC","value":7.7417},{"id":"ROTA PORTFÖY BİRİNCİ DEĞİŞKEN FON","code":"RD1","value":6.745},{"id":"TEB PORTFÖY SAĞLIK VE BİYOTEKNOLOJİ DEĞİŞKEN FON","code":"TBE","value":6.4021},{"id":"GARANTİ PORTFÖY SAĞLIK SEKTÖRÜ DEĞİŞKEN FON","code":"GZG","value":5.8896}]},{"name":"Hisse Senedi Şemsiye Fonu","funds_count":166,"sector_volume":"161.406.696.264,59","y":-4.4436,"id":"104","funds":[{"id":"AK PORTFÖY ALTERNATİF ENERJİ YABANCI HİSSE SENEDİ FONU","code":"AOY","value":7.0933},{"id":"AK PORTFÖY SAĞLIK SEKTÖRÜ YABANCI HİSSE SENEDİ FONU","code":"AFS","value":6.9217},{"id":"PARDUS PORTFÖY BİRİNCİ HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","code":"BIH","value":5.1339},{"id":"GARANTİ PORTFÖY YABANCI TEKNOLOJİ HİSSE SENEDİ FONU","code":"GUH","value":4.8926},{"id":"YAPI KREDİ PORTFÖY YABANCI TEKNOLOJİ SEKTÖRÜ HİSSE SENEDİ FONU","code":"YAY","value":4.8265}]}],"quarterly":[{"name":"Kıymetli Madenler Şemsiye Fonu","funds_count":22,"sector_volume":"171.667.588.027,35","y":30.2048,"id":"105","funds":[{"id":"PİRAMİT PORTFÖY ALTIN FONU","code":"PIR","value":37.9865},{"id":"BULLS PORTFÖY ALTIN FONU","code":"BLT","value":34.6934},{"id":"PHİLLİP PORTFÖY ALTIN FONU","code":"PTN","value":33.5061},{"id":"NEO PORTFÖY ALTIN FONU","code":"NAU","value":31.9325},{"id":"ÜNLÜ PORTFÖY ALTIN FONU","code":"UP1","value":31.6798}]},{"name":"Serbest Şemsiye Fonu","funds_count":1150,"sector_volume":"4.745.029.433.770,76","y":20.0977,"id":"108","funds":[{"id":"NEO PORTFÖY İKİNCİ SERBEST FON","code":"NMG","value":8832.4235},{"id":"NEO PORTFÖY BALKAN SERBEST FON","code":"OSF","value":1626.2707},{"id":"HEDEF PORTFÖY DOĞU HİSSE SENEDİ SERBEST (TL) FON (HİSSE SENEDİ YOĞUN FON)","code":"HDH","value":583.256},{"id":"ATA PORTFÖY BARBAROS HİSSE SENEDİ SERBEST (TL) FON (HİSSE SENEDİ YOĞUN FON)","code":"THV","value":526.0309},{"id":"PARDUS PORTFÖY DOĞU HİSSE SENEDİ SERBEST FON (HİSSE SENEDİ YOĞUN FON)","code":"PDH","value":523.9577}]},{"name":"Katılım Şemsiye Fonu","funds_count":75,"sector_volume":"300.512.881.314,64","y":13.2674,"id":"114","funds":[{"id":"ALBARAKA PORTFÖY BEREKET VAKFI NA DESTEK ALTIN KATILIM FONU","code":"RBA","value":33.1653},{"id":"HEDEF PORTFÖY ALTIN KATILIM FONU","code":"HAM","value":32.9556},{"id":"RE-PIE PORTFÖY ALTIN KATILIM FONU","code":"RJG","value":32.7013},{"id":"KUVEYT TÜRK PORTFÖY ALTIN KATILIM FONU","code":"KZL","value":32.6},{"id":"KUVEYT TÜRK PORTFÖY İKİNCİ ALTIN KATILIM FONU","code":"KZU","value":31.1786}]},{"name":"Para Piyasası Şemsiye Fonu","funds_count":70,"sector_volume":"1.310.220.361.483,16","y":10.9669,"id":"107","funds":[{"id":"PUSULA PORTFÖY PARA PİYASASI (TL) FONU","code":"PRY","value":12.2541},{"id":"TERA PORTFÖY PARA PİYASASI (TL) FONU","code":"TP2","value":12.0583},{"id":"FONERİA PORTFÖY PARA PİYASASI (TL) FONU","code":"GO6","value":12.0453},{"id":"AURA PORTFÖY PARA PİYASASI (TL) FONU","code":"PRH","value":11.8962},{"id":"ALLBATROSS PORTFÖY BİRİNCİ PARA PİYASASI (TL) FONU","code":"HVT","value":11.7116}]},{"name":"Karma Şemsiye Fonu","funds_count":7,"sector_volume":"4.662.461.371,19","y":10.3261,"id":"110","funds":[{"id":"İŞ PORTFÖY ELEKTRİKLİ ARAÇLAR KARMA FON","code":"IPJ","value":14.249},{"id":"İŞ PORTFÖY YENİLENEBİLİR ENERJİ KARMA FON","code":"IKP","value":13.7894},{"id":"İŞ PORTFÖY TEKNOLOJİ KARMA FON","code":"ITP","value":11.8738},{"id":"İŞ PORTFÖY BLOCKCHAİN TEKNOLOJİLERİ KARMA FON","code":"IJP","value":11.3511},{"id":"İŞ PORTFÖY SAĞLIK ŞİRKETLERİ KARMA FON","code":"IKL","value":9.6532}]},{"name":"Fon Sepeti Şemsiye Fonu","funds_count":80,"sector_volume":"86.110.255.946,74","y":10.1836,"id":"102","funds":[{"id":"YAPI KREDİ PORTFÖY GÜMÜŞ FON SEPETİ FONU","code":"YZG","value":28.1718},{"id":"TEB PORTFÖY GÜMÜŞ FON SEPETİ FONU","code":"GMC","value":27.5594},{"id":"AK PORTFÖY GÜMÜŞ FON SEPETI FONU","code":"GUM","value":27.4761},{"id":"DENİZ PORTFÖY GÜMÜŞ FON SEPETİ FONU","code":"DMG","value":27.2924},{"id":"KUVEYT TÜRK PORTFÖY GÜMÜŞ KATILIM FON SEPETİ FONU","code":"KGM","value":27.0624}]},{"name":"Borçlanma Araçları Şemsiye Fonu","funds_count":82,"sector_volume":"159.526.328.983,23","y":8.9774,"id":"100","funds":[{"id":"HEDEF PORTFÖY BİRİNCİ BORÇLANMA ARAÇLARI (TL) FONU","code":"HVK","value":11.912},{"id":"NUROL PORTFÖY BİRİNCİ BORÇLANMA ARAÇLARI FONU","code":"NJR","value":11.363},{"id":"AK PORTFÖY PY ÖZEL SEKTÖR BORÇLANMA ARAÇLARI (TL) ÖZEL FONU","code":"AZF","value":11.2577},{"id":"İSTANBUL PORTFÖY KISA VADELİ BORÇLANMA ARAÇLARI (TL) FONU","code":"IST","value":11.2059},{"id":"TACİRLER PORTFÖY BORÇLANMA ARAÇLARI FONU","code":"TPF","value":11.1743}]},{"name":"Değişken Şemsiye Fonu","funds_count":150,"sector_volume":"71.846.443.954,55","y":7.4608,"id":"101","funds":[{"id":"İŞ PORTFÖY YARI İLETKEN TEKNOLOJİLERİ DEĞİŞKEN FON","code":"IJC","value":23.2588},{"id":"ATA PORTFÖY ENERJİ DEĞİŞKEN FON","code":"URA","value":22.9222},{"id":"ROTA PORTFÖY İLAÇ VE MEDİKAL TEKNOLOJİLERİ DEĞİŞKEN FON","code":"RPM","value":21.5101},{"id":"OSMANLI PORTFÖY AGRESİF DEĞİŞKEN FON","code":"OPF","value":18.399},{"id":"İSTANBUL PORTFÖY BLOCKCHAIN TEKNOLOJİLERİ DEĞİŞKEN FON","code":"IVY","value":18.24}]},{"name":"Hisse Senedi Şemsiye Fonu","funds_count":162,"sector_volume":"161.406.696.264,59","y":1.6589,"id":"104","funds":[{"id":"PARDUS PORTFÖY BİRİNCİ HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","code":"BIH","value":24.7966},{"id":"PARDUS PORTFÖY İKİNCİ HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","code":"KHA","value":24.0348},{"id":"AK PORTFÖY YENİ TEKNOLOJİLER YABANCI HİSSE SENEDİ FONU","code":"AFT","value":23.4137},{"id":"YAPI KREDİ PORTFÖY YABANCI TEKNOLOJİ SEKTÖRÜ HİSSE SENEDİ FONU","code":"YAY","value":21.9822},{"id":"GARANTİ PORTFÖY YABANCI TEKNOLOJİ HİSSE SENEDİ FONU","code":"GUH","value":20.6778}]}],"semiAnnually":[{"name":"Serbest Şemsiye Fonu","funds_count":1066,"sector_volume":"4.745.029.433.770,76","y":37.7105,"id":"108","funds":[{"id":"NEO PORTFÖY İKİNCİ SERBEST FON","code":"NMG","value":9985.062},{"id":"NEO PORTFÖY BALKAN SERBEST FON","code":"OSF","value":2306.2816},{"id":"HEDEF PORTFÖY DOĞU HİSSE SENEDİ SERBEST (TL) FON (HİSSE SENEDİ YOĞUN FON)","code":"HDH","value":847.753},{"id":"PUSULA PORTFÖY İKİNCİ HİSSE SENEDİ SERBEST FON (HİSSE SENEDİ YOĞUN FON)","code":"PHN","value":692.5991},{"id":"TERA PORTFÖY BİRİNCİ SERBEST FON","code":"TLY","value":660.3368}]},{"name":"Karma Şemsiye Fonu","funds_count":7,"sector_volume":"4.662.461.371,19","y":35.7524,"id":"110","funds":[{"id":"İŞ PORTFÖY YENİLENEBİLİR ENERJİ KARMA FON","code":"IKP","value":50.124},{"id":"İŞ PORTFÖY ELEKTRİKLİ ARAÇLAR KARMA FON","code":"IPJ","value":45.8079},{"id":"İŞ PORTFÖY TEKNOLOJİ KARMA FON","code":"ITP","value":44.1093},{"id":"İŞ PORTFÖY BLOCKCHAİN TEKNOLOJİLERİ KARMA FON","code":"IJP","value":40.6097},{"id":"İŞ PORTFÖY DİJİTAL OYUN SEKTÖRÜ KARMA FON","code":"IJB","value":32.8257}]},{"name":"Kıymetli Madenler Şemsiye Fonu","funds_count":18,"sector_volume":"171.667.588.027,35","y":34.573,"id":"105","funds":[{"id":"NEO PORTFÖY ALTIN FONU","code":"NAU","value":37.6858},{"id":"ÜNLÜ PORTFÖY ALTIN FONU","code":"UP1","value":37.578},{"id":"İŞ PORTFÖY ALTIN FONU","code":"TTA","value":36.5099},{"id":"AKTİF PORTFÖY ALTIN KATILIM FONU","code":"MKG","value":36.3362},{"id":"INVEO PORTFÖY ALTIN FON","code":"GGK","value":35.6007}]},{"name":"Fon Sepeti Şemsiye Fonu","funds_count":78,"sector_volume":"86.110.255.946,74","y":30.0511,"id":"102","funds":[{"id":"YAPI KREDİ PORTFÖY GÜMÜŞ FON SEPETİ FONU","code":"YZG","value":61.3978},{"id":"TEB PORTFÖY GÜMÜŞ FON SEPETİ FONU","code":"GMC","value":60.5838},{"id":"AK PORTFÖY GÜMÜŞ FON SEPETI FONU","code":"GUM","value":59.7094},{"id":"DENİZ PORTFÖY GÜMÜŞ FON SEPETİ FONU","code":"DMG","value":59.6182},{"id":"AKTİF PORTFÖY GÜMÜŞ FON SEPETİ FONU","code":"MJG","value":59.033}]},{"name":"Değişken Şemsiye Fonu","funds_count":143,"sector_volume":"71.846.443.954,55","y":28.5668,"id":"101","funds":[{"id":"ATA PORTFÖY ENERJİ DEĞİŞKEN FON","code":"URA","value":95.865},{"id":"İŞ PORTFÖY YARI İLETKEN TEKNOLOJİLERİ DEĞİŞKEN FON","code":"IJC","value":80.8093},{"id":"GARANTİ PORTFÖY BLOCKCHAİN TEKNOLOJİLERİ DEĞİŞKEN FON","code":"GBV","value":73.5252},{"id":"İSTANBUL PORTFÖY BLOCKCHAIN TEKNOLOJİLERİ DEĞİŞKEN FON","code":"IVY","value":70.9801},{"id":"GARANTİ PORTFÖY YARI İLETKEN TEKNOLOJİLERİ DEĞİŞKEN FON","code":"YIT","value":61.9369}]},{"name":"Katılım Şemsiye Fonu","funds_count":66,"sector_volume":"300.512.881.314,64","y":25.9469,"id":"114","funds":[{"id":"AKTİF PORTFÖY TEKNOLOJİ KATILIM FONU","code":"CPU","value":58.5255},{"id":"KUVEYT TÜRK PORTFÖY TEKNOLOJİ KATILIM FONU","code":"KTJ","value":53.8524},{"id":"KUVEYT TÜRK PORTFÖY KIYMETLİ MADENLER KATILIM FONU","code":"KUT","value":45.6479},{"id":"ALBARAKA PORTFÖY BEREKET VAKFI NA DESTEK ALTIN KATILIM FONU","code":"RBA","value":38.0367},{"id":"HEDEF PORTFÖY ALTIN KATILIM FONU","code":"HAM","value":37.9956}]},{"name":"Para Piyasası Şemsiye Fonu","funds_count":66,"sector_volume":"1.310.220.361.483,16","y":24.703,"id":"107","funds":[{"id":"PUSULA PORTFÖY PARA PİYASASI (TL) FONU","code":"PRY","value":26.9017},{"id":"TERA PORTFÖY PARA PİYASASI (TL) FONU","code":"TP2","value":26.6982},{"id":"FONERİA PORTFÖY PARA PİYASASI (TL) FONU","code":"GO6","value":26.1213},{"id":"ALLBATROSS PORTFÖY BİRİNCİ PARA PİYASASI (TL) FONU","code":"HVT","value":26.0832},{"id":"QİNVEST PORTFÖY PARA PİYASASI FONU","code":"EIL","value":25.8602}]},{"name":"Borçlanma Araçları Şemsiye Fonu","funds_count":79,"sector_volume":"159.526.328.983,23","y":22.2218,"id":"100","funds":[{"id":"TERA PORTFÖY BİRİNCİ BORÇLANMA ARAÇLARI (TL) FONU","code":"TRJ","value":27.1512},{"id":"YAPI KREDİ PORTFÖY ÇALIŞAN HESAP KISA VADELİ BORÇLANMA ARAÇLARI FONU","code":"YDK","value":26.1633},{"id":"HEDEF PORTFÖY BİRİNCİ BORÇLANMA ARAÇLARI (TL) FONU","code":"HVK","value":26.0131},{"id":"NUROL PORTFÖY BİRİNCİ BORÇLANMA ARAÇLARI FONU","code":"NJR","value":25.8809},{"id":"AK PORTFÖY ÜÇÜNCÜ KAMU BORÇLANMA ARAÇLARI (TL) ÖZEL FONU","code":"CVA","value":25.7738}]},{"name":"Hisse Senedi Şemsiye Fonu","funds_count":154,"sector_volume":"161.406.696.264,59","y":18.6164,"id":"104","funds":[{"id":"YAPI KREDİ PORTFÖY YABANCI TEKNOLOJİ SEKTÖRÜ HİSSE SENEDİ FONU","code":"YAY","value":81.0825},{"id":"AK PORTFÖY YENİ TEKNOLOJİLER YABANCI HİSSE SENEDİ FONU","code":"AFT","value":73.9392},{"id":"GARANTİ PORTFÖY YABANCI TEKNOLOJİ HİSSE SENEDİ FONU","code":"GUH","value":66.445},{"id":"AK PORTFÖY ALTERNATİF ENERJİ YABANCI HİSSE SENEDİ FONU","code":"AOY","value":56.1503},{"id":"PARDUS PORTFÖY BİRİNCİ HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","code":"BIH","value":55.5023}]}],"fromYearBeginning":[{"name":"Kıymetli Madenler Şemsiye Fonu","funds_count":18,"sector_volume":"171.667.588.027,35","y":87.2407,"id":"105","funds":[{"id":"NEO PORTFÖY ALTIN FONU","code":"NAU","value":94.3807},{"id":"HSBC PORTFÖY ALTIN FONU","code":"HBF","value":93.0704},{"id":"AK PORTFÖY ALTIN FONU","code":"AFO","value":91.4108},{"id":"ROTA PORTFÖY ALTIN FONU","code":"RPG","value":91.2463},{"id":"FİBA PORTFÖY ALTIN FONU","code":"FIB","value":90.6178}]},{"name":"Serbest Şemsiye Fonu","funds_count":981,"sector_volume":"4.745.029.433.770,76","y":63.375,"id":"108","funds":[{"id":"NEO PORTFÖY İKİNCİ SERBEST FON","code":"NMG","value":11392.0706},{"id":"QNB

In [22]:
import http.client

conn = http.client.HTTPSConnection("tefas-api.p.rapidapi.com")

headers = {
    'x-rapidapi-key': "c3c297e087mshf0c09b3c9068e2fp1ae78fjsnf0b02d992e8a",
    'x-rapidapi-host': "tefas-api.p.rapidapi.com"
}

conn.request("GET", "/api/v1/funds/returns?fundType=1&startDate=01.01.2024&endDate=31.12.2024", headers=headers)

res = conn.getresponse()
data = res.read()

print(data.decode("utf-8"))

{"data":[{"fundCode":"AOY","fundName":"AK PORTFÖY ALTERNATİF ENERJİ YABANCI HİSSE SENEDİ FONU","category":"Hisse Senedi Şemsiye Fonu","returnByDate":-22.6937},{"fundCode":"AFO","fundName":"AK PORTFÖY ALTIN FONU","category":"Kıymetli Madenler Şemsiye Fonu","returnByDate":45.6979},{"fundCode":"PAL","fundName":"AK PORTFÖY ALTINCI SERBEST(DÖVİZ) FON","category":"Serbest Şemsiye Fonu","returnByDate":24.4644},{"fundCode":"AFA","fundName":"AK PORTFÖY AMERİKA YABANCI HİSSE SENEDİ FONU","category":"Hisse Senedi Şemsiye Fonu","returnByDate":46.7721},{"fundCode":"AFV","fundName":"AK PORTFÖY AVRUPA YABANCI HİSSE SENEDİ FONU","category":"Hisse Senedi Şemsiye Fonu","returnByDate":18.2311},{"fundCode":"BNC","fundName":"AK PORTFÖY BEŞİNCİ SERBEST FON","category":"Serbest Şemsiye Fonu"},{"fundCode":"ADP","fundName":"AK PORTFÖY BIST BANKA ENDEKSİ HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":71.6558},{"fundCode":"APJ","fundName":"AK PORTFÖY BIST ŞİRKETLERİ FON SEPETİ FONU","category":"Fon Sepeti Şemsiye Fonu","returnByDate":50.8449},{"fundCode":"AKU","fundName":"AK PORTFÖY BIST 30 ENDEKSİ HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":37.7057},{"fundCode":"ARL","fundName":"AK PORTFÖY BİRİNCİ FON SEPETİ FONU","category":"Fon Sepeti Şemsiye Fonu","returnByDate":54.2715},{"fundCode":"PUC","fundName":"AK PORTFÖY BİRİNCİ KISA VADELİ SERBEST (TL)  FON","category":"Serbest Şemsiye Fonu","returnByDate":60.2037},{"fundCode":"BUY","fundName":"AK PORTFÖY BÜYÜYEN ŞİRKETLER HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":4.5229},{"fundCode":"VAY","fundName":"AK PORTFÖY DEĞER ODAKLI 100 ŞİRKETLERİ HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":36.5776},{"fundCode":"VCY","fundName":"AK PORTFÖY ELEKTRİKLİ VE OTONOM ARAÇ TEKNOLOJİLERİ DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu","returnByDate":13.3888},{"fundCode":"AKE","fundName":"AK PORTFÖY EUROBOND (AMERİKAN DOLARI) BORÇLANMA ARAÇLARI FONU","category":"Borçlanma Araçları Şemsiye Fonu","returnByDate":26.9699},{"fundCode":"ZFB","fundName":"AK PORTFÖY FİNTEK VE BLOKZİNCİRİ TEKNOLOJİLERİ DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu","returnByDate":47.7066},{"fundCode":"GUM","fundName":"AK PORTFÖY GÜMÜŞ FON SEPETI FONU","category":"Fon Sepeti Şemsiye Fonu","returnByDate":42.5672},{"fundCode":"AK3","fundName":"AK PORTFÖY HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":59.8084},{"fundCode":"FUA","fundName":"AK PORTFÖY İHRACATÇI ŞİRKETLER HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":19.9466},{"fundCode":"AGC","fundName":"AK PORTFÖY İKİNCİ DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu","returnByDate":29.6443},{"fundCode":"ARM","fundName":"AK PORTFÖY İKİNCİ FON SEPETİ FONU","category":"Fon Sepeti Şemsiye Fonu","returnByDate":53.8046},{"fundCode":"ALC","fundName":"AK PORTFÖY KAR PAYI ÖDEYEN ŞİRKETLER HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":62.3444},{"fundCode":"MTV","fundName":"AK PORTFÖY METAVERSE VE DİJİTAL YAŞAM TEKNOLOJİLERİ DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu","returnByDate":33.7419},{"fundCode":"ADE","fundName":"AK PORTFÖY MUTLAK GETİRİ HEDEFLİ DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu","returnByDate":54.5603},{"fundCode":"ONK","fundName":"AK PORTFÖY ONİKİNCİ SERBEST (DÖVİZ-AVRO) FON","category":"Serbest Şemsiye Fonu","returnByDate":16.186},{"fundCode":"APT","fundName":"AK PORTFÖY ORTA VADELI BORÇLANMA ARAÇLARI FONU","category":"Borçlanma Araçları Şemsiye Fonu","returnByDate":34.2794},{"fundCode":"AYR","fundName":"AK PORTFÖY ÖZEL SEKTÖR BORÇLANMA ARAÇLARI (TL) FONU","category":"Borçlanma Araçları Şemsiye Fonu","returnByDate":54.8992},{"fundCode":"AIS","fundName":"AK PORTFÖY PARA PİYASASI KATILIM FONU","category":"Katılım Şemsiye Fonu","returnByDate":49.8198},{"fundCode":"AES","fundName":"AK PORTFÖY PETROL YABANCI BYF FON SEPETİ FONU","category":"Fon Sepeti Şemsiye Fonu","returnByDate":22.2976},{"fundCode":"DTZ","fundName":"AK PORTFÖY ROBOTİK TEKNOLOJİLER DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu","returnByDate":29.775},{"fundCode":"AFS","fundName":"AK PORTFÖY SAĞLIK SEKTÖRÜ YABANCI HİSSE SENEDİ FONU","category":"Hisse Senedi Şemsiye Fonu","returnByDate":8.2178},{"fundCode":"TAR","fundName":"AK PORTFÖY TARIM VE GIDA TEKNOLOJİLERİ DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu","returnByDate":15.0573},{"fundCode":"ICZ","fundName":"AK PORTFÖY TEKNOLOJİ ŞİRKETLERİ HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":47.0035},{"fundCode":"TGR","fundName":"AK PORTFÖY TURİZM VE SEYAHAT SEKTÖRÜ DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu","returnByDate":37.6789},{"fundCode":"AK2","fundName":"AK PORTFÖY UZUN VADELİ BORÇLANMA ARAÇLARI FONU","category":"Borçlanma Araçları Şemsiye Fonu","returnByDate":20.2605},{"fundCode":"ODV","fundName":"AK PORTFÖY ÜÇÜNCÜ FON SEPETİ FONU","category":"Fon Sepeti Şemsiye Fonu","returnByDate":52.59},{"fundCode":"BGP","fundName":"AK PORTFÖY ÜÇÜNCÜ PARA PİYASASI (TL) FONU","category":"Para Piyasası Şemsiye Fonu","returnByDate":61.877},{"fundCode":"AFT","fundName":"AK PORTFÖY YENİ TEKNOLOJİLER YABANCI HİSSE SENEDİ FONU","category":"Hisse Senedi Şemsiye Fonu","returnByDate":47.1888},{"fundCode":"AJK","fundName":"AK PORTFÖY 0-5 YIL VADELİ SERBEST (DÖVİZ) FON","category":"Serbest Şemsiye Fonu","returnByDate":17.4868},{"fundCode":"ONN","fundName":"AKTİF PORTFÖY AKTİF ONİKS SERBEST (TL) FON","category":"Serbest Şemsiye Fonu","returnByDate":54.4251},{"fundCode":"MJL","fundName":"AKTİF PORTFÖY AKTİF SERBEST (DÖVİZ-AVRO) FON","category":"Serbest Şemsiye Fonu","returnByDate":15.4193},{"fundCode":"MKG","fundName":"AKTİF PORTFÖY ALTIN KATILIM FONU","category":"Kıymetli Madenler Şemsiye Fonu","returnByDate":50.143},{"fundCode":"MMH","fundName":"AKTİF PORTFÖY BIST 30 ENDEKSİ HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":42.422},{"fundCode":"MJB","fundName":"AKTİF PORTFÖY BİRİNCİ FON SEPETİ FONU","category":"Fon Sepeti Şemsiye Fonu","returnByDate":33.8418},{"fundCode":"ONE","fundName":"AKTİF PORTFÖY BİRİNCİ HİSSE SENEDİ SERBEST (TL) FON (HİSSE SENEDİ YOĞUN FON)","category":"Serbest Şemsiye Fonu","returnByDate":22.2614},{"fundCode":"GLG","fundName":"AKTİF PORTFÖY CAPİTAL HİSSE SENEDİ SERBEST FON (HİSSE SENEDİ YOĞUN FON)","category":"Serbest Şemsiye Fonu","returnByDate":27.8642},{"fundCode":"ESG","fundName":"AKTİF PORTFÖY ESG SÜRDÜRÜLEBİLİRLİK SERBEST FON","category":"Serbest Şemsiye Fonu","returnByDate":34.2522},{"fundCode":"MJG","fundName":"AKTİF PORTFÖY GÜMÜŞ FON SEPETİ FONU","category":"Fon Sepeti Şemsiye Fonu","returnByDate":44.2251},{"fundCode":"ASJ","fundName":"AKTİF PORTFÖY HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":46.3305},{"fundCode":"MPN","fundName":"AKTİF PORTFÖY İKİNCİ AKTİF SERBEST (DÖVİZ) FON","category":"Serbest Şemsiye Fonu","returnByDate":28.8451},{"fundCode":"EYT","fundName":"AKTİF PORTFÖY İKİNCİ FON SEPETİ FONU","category":"Fon Sepeti Şemsiye Fonu","returnByDate":44.0042},{"fundCode":"BUL","fundName":"AKTİF PORTFÖY İNŞAAT SEKTÖRÜ HİSSE SENEDİ SERBEST (TL) FON (HİSSE SENEDİ YOĞUN FON)","category":"Serbest Şemsiye Fonu","returnByDate":1.684},{"fundCode":"MPS","fundName":"AKTİF PORTFÖY KATILIM HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":40.3837},{"fundCode":"MPF","fundName":"AKTİF PORTFÖY KISA VADELİ KİRA SERTİFİKASI KATILIM (TL) FONU","category":"Katılım Şemsiye Fonu","returnByDate":52.0906},{"fundCode":"MPK","fundName":"AKTİF PORTFÖY KİRA SERTİFİKASI KATILIM (TL) FONU","category":"Katılım Şemsiye Fonu","returnByDate":49.5571},{"fundCode":"IDL","fundName":"AKTİF PORTFÖY PARA PİYASASI (TL) FONU","category":"Para Piyasası Şemsiye Fonu","returnByDate":60.9247},{"fundCode":"MTS","fundName":"AKTİF PORTFÖY TARIM VE SÜRDÜRÜLEBİLİRLİK FON SEPETİ FONU","category":"Fon Sepeti Şemsiye Fonu","returnByDate":19.4428},{"fundCode":"CPU","fundName":"AKTİF PORTFÖY TEKNOLOJİ KATILIM FONU","category":"Katılım Şemsiye Fonu","returnByDate":48.9891},{"fundCode":"GLC","fundName":"AKTİF PORTFÖY ÜÇÜNCÜ FON SEPETİ FONU","category":"Fon Sepeti Şemsiye Fonu","returnByDate":49.2469},{"fundCode":"RBA","fundName":"ALBARAKA PORTFÖY BEREKET VAKFI NA DESTEK ALTIN KATILIM FONU","category":"Katılım Şemsiye Fonu","returnByDate":41.0482},{"fundCode":"RBK","fundName":"ALBARAKA PORTFÖY KATILIM FONU","category":"Katılım Şemsiye Fonu","returnByDate":32.4093},{"fundCode":"RBH","fundName":"ALBARAKA PORTFÖY KATILIM HİSSE SENEDİ FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":40.2737},{"fundCode":"PVK","fundName":"ALBARAKA PORTFÖY KISA VADELİ KATILIM SERBEST (TL) FON","category":"Serbest Şemsiye Fonu","returnByDate":56.5626},{"fundCode":"RBV","fundName":"ALBARAKA PORTFÖY KISA VADELİ KİRA SERTİFİKALARI KATILIM (TL) FONU","category":"Katılım Şemsiye Fonu","returnByDate":52.3212},{"fundCode":"RBT","fundName":"ALBARAKA PORTFÖY KİRA SERTİFİKALARI  KATILIM FONU","category":"Katılım Şemsiye Fonu","returnByDate":51.1269},{"fundCode":"LLA","fundName":"ALLBATROSS PORTFÖY AYDIN HİSSE SENEDİ SERBEST (TL) FON (HİSSE SENEDİ YOĞUN FON)","category":"Serbest Şemsiye Fonu","returnByDate":1.2787},{"fundCode":"HVU","fundName":"ALLBATROSS PORTFÖY BİRİNCİ DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu","returnByDate":38.4683},{"fundCode":"BVM","fundName":"ALLBATROSS PORTFÖY BİRİNCİ HİSSE SENEDİ SERBEST (TL) FON (HİSSE SENEDİ YOĞUN FON)","category":"Serbest Şemsiye Fonu","returnByDate":9.7075},{"fundCode":"HVZ","fundName":"ALLBATROSS PORTFÖY BİRİNCİ HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":48.3014},{"fundCode":"HVT","fundName":"ALLBATROSS PORTFÖY BİRİNCİ PARA PİYASASI (TL) FONU","category":"Para Piyasası Şemsiye Fonu","returnByDate":59.3683},{"fundCode":"AS1","fundName":"ALLBATROSS PORTFÖY BİRİNCİ SERBEST (DÖVİZ) FON","category":"Serbest Şemsiye Fonu","returnByDate":24.8072},{"fundCode":"DEF","fundName":"ALLBATROSS PORTFÖY DEFNE SERBEST FON","category":"Serbest Şemsiye Fonu","returnByDate":65.2748},{"fundCode":"GIH","fundName":"ALLBATROSS PORTFÖY GIDA VE İÇECEK SEKTÖRÜ HİSSE SENEDİ FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":15.0022},{"fundCode":"LID","fundName":"ALLBATROSS PORTFÖY İKİNCİ DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu"},{"fundCode":"IHZ","fundName":"ALLBATROSS PORTFÖY İKİNCİ HİSSE SENEDİ SERBEST FON (HİSSE SENEDİ YOĞUN FON)","category":"Serbest Şemsiye Fonu","returnByDate":0.7823},{"fundCode":"IHA","fundName":"ALLBATROSS PORTFÖY İKİNCİ HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":44.6287},{"fundCode":"AOJ","fundName":"ALLBATROSS PORTFÖY İNŞAAT SEKTÖRÜ HİSSE SENEDİ SERBEST (TL) FON (HİSSE SENEDİ YOĞUN FON)","category":"Serbest Şemsiye Fonu","returnByDate":43.0961},{"fundCode":"KHT","fundName":"ALLBATROSS PORTFÖY KARTAL HİSSE SENEDİ SERBEST (TL) FON (HİSSE SENEDİ YOĞUN FON)","category":"Serbest Şemsiye Fonu","returnByDate":31.6005},{"fundCode":"KST","fundName":"ALLBATROSS PORTFÖY KATILIM HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":34.362},{"fundCode":"PRU","fundName":"ALLBATROSS PORTFÖY KISA VADELİ SERBEST (TL) FON","category":"Serbest Şemsiye Fonu","returnByDate":53.2894},{"fundCode":"AEV","fundName":"ALLBATROSS PORTFÖY SANAYİ ŞİRKETLERİ HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":31.0408},{"fundCode":"PKF","fundName":"ATA PORTFÖY ALTIN KATILIM FONU","category":"Katılım Şemsiye Fonu","returnByDate":51.3501},{"fundCode":"THV","fundName":"ATA PORTFÖY BARBAROS HİSSE SENEDİ SERBEST (TL) FON (HİSSE SENEDİ YOĞUN FON)","category":"Serbest Şemsiye Fonu","returnByDate":42.6398},{"fundCode":"AED","fundName":"ATA PORTFÖY BİRİNCİ DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu","returnByDate":46.401},{"fundCode":"AAK","fundName":"ATA PORTFÖY ÇOKLU VARLIK DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu","returnByDate":49.9119},{"fundCode":"AUT","fundName":"ATA PORTFÖY DENGELİ DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu","returnByDate":56.7579},{"fundCode":"ANZ","fundName":"ATA PORTFÖY DÖRDÜNCÜ SERBEST (DÖVİZ) FON","category":"Serbest Şemsiye Fonu","returnByDate":27.2182},{"fundCode":"AAS","fundName":"ATA PORTFÖY FON SEPETİ SERBEST FONU","category":"Serbest Şemsiye Fonu","returnByDate":16.148},{"fundCode":"AAV","fundName":"ATA PORTFÖY İKİNCİ HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":51.3877},{"fundCode":"AYA","fundName":"ATA PORTFÖY KAR PAYI ÖDEYEN HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":38.5273},{"fundCode":"TLZ","fundName":"ATA PORTFÖY KATILIM HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":26.6512},{"fundCode":"DGH","fundName":"ATA PORTFÖY PARA PİYASASI SERBEST (TL) FON","category":"Serbest Şemsiye Fonu","returnByDate":56.0305},{"fundCode":"AAL","fundName":"ATA PORTFÖY PARA PİYASASI (TL) FONU","category":"Para Piyasası Şemsiye Fonu","returnByDate":59.3776},{"fundCode":"RTG","fundName":"ATA PORTFÖY ROBOTİK TEKNOLOJİLERİ DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu","returnByDate":34.2818},{"fundCode":"YLC","fundName":"ATA PORTFÖY TARIM VE GIDA DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu","returnByDate":7.1172},{"fundCode":"AHI","fundName":"ATLAS PORTFÖY BİRİNCİ HİSSE SENEDİ FONU(HİSSE SENEDİ YOĞUN)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":45.9571},{"fundCode":"AHU","fundName":"ATLAS PORTFÖY BİRİNCİ ÖZEL SEKTÖR BORÇLANMA ARAÇLARI FONU","category":"Borçlanma Araçları Şemsiye Fonu","returnByDate":59.6652},{"fundCode":"PFS","fundName":"ATLAS PORTFÖY FON SEPETİ FONU","category":"Fon Sepeti Şemsiye Fonu","returnByDate":48.9334},{"fundCode":"PPT","fundName":"ATLAS PORTFÖY PARA PİYASASI (TL) FONU","category":"Para Piyasası Şemsiye Fonu"},{"fundCode":"DFI","fundName":"ATLAS PORTFÖY SERBEST FON","category":"Serbest Şemsiye Fonu","returnByDate":29.4234},{"fundCode":"AHN","fundName":"ATLAS PORTFÖY SERBEST(DÖVİZ)FON","category":"Serbest Şemsiye Fonu","returnByDate":30.1854},{"fundCode":"BDC","fundName":"AURA PORTFÖY BODRUM SERBEST FON","category":"Serbest Şemsiye Fonu","returnByDate":69.2024},{"fundCode":"IYB","fundName":"AURA PORTFÖY DEĞİŞKEN FONU","category":"Değişken Şemsiye Fonu","returnByDate":36.3229},{"fundCode":"ESP","fundName":"AURA PORTFÖY EMTİA SERBEST FON","category":"Serbest Şemsiye Fonu","returnByDate":-8.8386},{"fundCode":"TLH","fundName":"AURA PORTFÖY HİSSE SENEDİ FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":37.3139},{"fundCode":"TPV","fundName":"AURA PORTFÖY İKİNCİ DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu","returnByDate":34.2346},{"fundCode":"TLE","fundName":"AURA PORTFÖY YABANCI BORÇLANMA ARAÇLARI FONU","category":"Borçlanma Araçları Şemsiye Fonu","returnByDate":30.5924},{"fundCode":"SPE","fundName":"AZIMUT PORTFÖY 5.0 SERBEST (DÖVIZ) FON","category":"Serbest Şemsiye Fonu","returnByDate":32.9749},{"fundCode":"GLS","fundName":"AZİMUT PORTFÖY  KİRA SERTİFİKALARI (SUKUK) KATILIM FONU","category":"Katılım Şemsiye Fonu","returnByDate":50.7094},{"fundCode":"KMF","fundName":"AZİMUT PORTFÖY ALTIN KATILIM FONU","category":"Katılım Şemsiye Fonu","returnByDate":54.8034},{"fundCode":"GMA","fundName":"AZİMUT PORTFÖY ÇOKLU VARLIK DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu","returnByDate":49.0093},{"fundCode":"AHV","fundName":"AZİMUT PORTFÖY DENGELİ FON SEPETİ FONU","category":"Fon Sepeti Şemsiye Fonu","returnByDate":51.926},{"fundCode":"GBZ","fundName":"AZİMUT PORTFÖY EMTİA FON SEPETİ FONU","category":"Fon Sepeti Şemsiye Fonu","returnByDate":21.5897},{"fundCode":"KSK","fundName":"AZİMUT PORTFÖY İKİNCİ PARA PİYASASI KATILIM FONU","category":"Katılım Şemsiye Fonu","returnByDate":53.1232},{"fundCode":"SPN","fundName":"AZİMUT PORTFÖY İSTATİSTİKSEL ARBİTRAJ HİSSE SENEDİ SERBEST FON (HİSSE SENEDİ YOĞUN FON)","category":"Serbest Şemsiye Fonu","returnByDate":52.7982},{"fundCode":"HYP","fundName":"AZİMUT PORTFÖY İVME SERBEST FON","category":"Serbest Şemsiye Fonu","returnByDate":38.5439},{"fundCode":"KTI","fundName":"AZİMUT PORTFÖY KATILIM HİSSE SENEDİ FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":46.9078},{"fundCode":"KVS","fundName":"AZİMUT PORTFÖY KISA VADELİ SERBEST (TL) FON","category":"Serbest Şemsiye Fonu","returnByDate":53.7393},{"fundCode":"PPZ","fundName":"AZİMUT PORTFÖY PARA PİYASASI (TL) FONU","category":"Para Piyasası Şemsiye Fonu","returnByDate":61.3723},{"fundCode":"GBC","fundName":"AZİMUT PORTFÖY YABANCI HİSSE SENEDİ FONU","category":"Hisse Senedi Şemsiye Fonu","returnByDate":32.8647},{"fundCode":"BJD","fundName":"AZİMUT PORTFÖY 13.0 SERBEST (DÖVİZ) FON","category":"Serbest Şemsiye Fonu","returnByDate":21.8304},{"fundCode":"ZMT","fundName":"AZİMUT PORTFÖY 22.0 SERBEST (DÖVİZ-AVRO) FON","category":"Serbest Şemsiye Fonu","returnByDate":19.49},{"fundCode":"FYI","fundName":"AZİMUT PORTFÖY 4.0 SERBEST FON","category":"Serbest Şemsiye Fonu","returnByDate":62.0658},{"fundCode":"PSL","fundName":"AZİMUT PORTFÖY 8.0 SERBEST FON","category":"Serbest Şemsiye Fonu","returnByDate":31.3944},{"fundCode":"GTF","fundName":"AZİMUT PYŞ BİRİNCİ BORÇLANMA ARAÇLARI FONU","category":"Borçlanma Araçları Şemsiye Fonu","returnByDate":50.7218},{"fundCode":"GL1","fundName":"AZİMUT PYŞ BİRİNCİ HİSSE SENEDİ FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":55.2097},{"fundCode":"GSP","fundName":"AZİMUT PYŞ KAR PAYI ÖDEYEN HİSSE SENEDİ FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":60.7764},{"fundCode":"GBL","fundName":"AZİMUT PYŞ KISA VADELİ BORÇLANMA ARAÇLARI FONU","category":"Borçlanma Araçları Şemsiye Fonu","returnByDate":57.5729},{"fundCode":"BIS","fundName":"BV PORTFÖY BİRİNCİ SERBEST FON","category":"Serbest Şemsiye Fonu"},{"fundCode":"BVZ","fundName":"BV PORTFÖY İSTATİSTİKSEL ARBİTRAJ SERBEST (TL) FON","category":"Serbest Şemsiye Fonu","returnByDate":70.8901},{"fundCode":"BHI","fundName":"BV PORTFÖY MUTLAK GETİRİ HEDEFLİ HİSSE SENEDİ SERBEST (TL) FON (HİSSE SENEDİ YOĞUN FON)","category":"Serbest Şemsiye Fonu"},{"fundCode":"BTE","fundName":"BV PORTFÖY OYUN VE TEKNOLOJİ DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu","returnByDate":46.3417},{"fundCode":"BVV","fundName":"BV PORTFÖY TEKNOLOJİ DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu","returnByDate":30.3342},{"fundCode":"DBA","fundName":"DENİZ PORTFÖY ALTIN FONU","category":"Kıymetli Madenler Şemsiye Fonu","returnByDate":53.7441},{"fundCode":"DDA","fundName":"DENİZ PORTFÖY BANKACILIK SEKTÖRÜ HİSSE SENEDİ SERBEST FON (HİSSE SENEDİ YOĞUN FON)","category":"Serbest Şemsiye Fonu","returnByDate":73.7723},{"fundCode":"DZM","fundName":"DENİZ PORTFÖY BEŞİNCİ SERBEST (DÖVİZ) FON","category":"Serbest Şemsiye Fonu","returnByDate":41.0725},{"fundCode":"DTL","fundName":"DENİZ PORTFÖY BIST 100 DIŞI ŞİRKETLER HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":48.4231},{"fundCode":"DZE","fundName":"DENİZ PORTFÖY BIST 100 ENDEKSİ HİSSE SENEDİ FONU(HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":38.6559},{"fundCode":"DBP","fundName":"DENİZ PORTFÖY BİRİNCİ DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu","returnByDate":47.2363},{"fundCode":"DPT","fundName":"DENİZ PORTFÖY BİST TEMETTÜ 25 ENDEKSİ HİSSE SENEDİ FONU ( HİSSE SENEDİ YOĞUN FON )","category":"Hisse Senedi Şemsiye Fonu","returnByDate":50.3851},{"fundCode":"DBB","fundName":"D

In [23]:
import http.client

conn = http.client.HTTPSConnection("tefas-api.p.rapidapi.com")

headers = {
    'x-rapidapi-key': "c3c297e087mshf0c09b3c9068e2fp1ae78fjsnf0b02d992e8a",
    'x-rapidapi-host': "tefas-api.p.rapidapi.com"
}

conn.request("GET", "/api/v1/funds/returns/%7Bpage%7D?size=50&endDate=31.12.2024&startDate=01.01.2024&fundType=1", headers=headers)

res = conn.getresponse()
data = res.read()

print(data.decode("utf-8"))

{"error":"Invalid page number","details":"Page must be a non-negative integer","status":400,"retryAfter":"0001-01-01T00:00:00Z","correlationId":"79fab5f0-a69f-47f8-b371-7b4b89865dfa","suggestion":"Please check your request parameters and try again","occurredAt":"2025-10-25T11:38:53.243676216Z"}

In [25]:
import http.client

conn = http.client.HTTPSConnection("tefas-api.p.rapidapi.com")

headers = {
    'x-rapidapi-key': "c3c297e087mshf0c09b3c9068e2fp1ae78fjsnf0b02d992e8a",
    'x-rapidapi-host': "tefas-api.p.rapidapi.com"
}

conn.request("GET", "/api/v1/funds/historical/1?fundType=1&size=250", headers=headers)

res = conn.getresponse()
data = res.read()

parsed = json.loads(data.decode("utf-8"))
records = parsed.get("data") if isinstance(parsed, dict) else parsed
if not isinstance(records, list):
    records = [records] if records else []
df = pd.DataFrame(records)
df

,fund_code,fund_name,price,share_count,num_of_participants,total_portfolio,borsa_bulletin_price,date
0,AAK,ATA PORTFÖY ÇOKLU VARLIK DEĞİŞKEN FON,30.048146,1.121020e+06,769,3.368457e+07,0,2025-10-24
1,AAL,ATA PORTFÖY PARA PİYASASI (TL) FONU,2.618228,1.105103e+09,4790,2.893410e+09,0,2025-10-24
2,AAS,ATA PORTFÖY FON SEPETİ SERBEST FONU,9.889333,4.512205e+06,165,4.462270e+07,0,2025-10-24
3,AAV,ATA PORTFÖY İKİNCİ HİSSE SENEDİ (TL) FONU (HİS...,50.184071,6.735961e+06,2930,3.380379e+08,0,2025-10-24
4,ABG,ATLAS PORTFÖY DÖRDÜNCÜ SERBEST (TL) FON,8.958514,7.367621e+07,13,6.600293e+08,0,2025-10-24
...,...,...,...,...,...,...,...,...
245,DEI,ALLBATROSS PORTFÖY DEMİR KISA VADELİ KATILIM S...,0.079862,6.775401e+10,12,5.410964e+09,0,2025-10-24
246,DFC,DENİZ PORTFÖY TARIM VE GIDA DEĞİŞKEN FON,2.412924,2.939804e+07,1596,7.093525e+07,0,2025-10-24
247,DFD,DENİZ PORTFÖY EMTİA SERBEST FON,2.084495,2.475365e+07,213,5.159885e+07,0,2025-10-24
248,DFI,ATLAS PORTFÖY SERBEST FON,1.393681,1.203229e+09,9834,1.676917e+09,0,2025-10-24
249,DFO,AZİMUT PORTFÖY DLS SERBEST ÖZEL FON,2.577919,2.965423e+08,2,7.644621e+08,0,2025-10-24

In [31]:
import http.client

conn = http.client.HTTPSConnection("tefas-api.p.rapidapi.com")

headers = {
    'x-rapidapi-key': "c3c297e087mshf0c09b3c9068e2fp1ae78fjsnf0b02d992e8a",
    'x-rapidapi-host': "tefas-api.p.rapidapi.com"
}

conn.request("GET", "/api/v1/funds/historical?fundType=3", headers=headers)

res = conn.getresponse()
data = res.read()

print(data.decode("utf-8"))
parsed = json.loads(data.decode("utf-8"))
records = parsed.get("data") if isinstance(parsed, dict) else parsed
if not isinstance(records, list):
    records = [records] if records else []
df = pd.DataFrame(records)
df['fund_name']

{"data":[{"fund_code":"BLH","fund_name":"AK PORTFÖY BIST LİKİT BANKA ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":38.244272,"share_count":64000000,"num_of_participants":0,"total_portfolio":2447633392.19,"borsa_bulletin_price":0,"date":"2025-10-24"},{"fund_code":"BND","fund_name":"AK PORTFÖY BIST BANKA DIŞI LİKİT 10 ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":27.202775,"share_count":14300000,"num_of_participants":0,"total_portfolio":388999688.83,"borsa_bulletin_price":0,"date":"2025-10-24"},{"fund_code":"BOE","fund_name":"AK PORTFÖY BIST 30 ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":28.674122,"share_count":46900000,"num_of_participants":0,"total_portfolio":1344816334.43,"borsa_bulletin_price":0,"date":"2025-10-24"},{"fund_code":"BTL","fund_name":"OSMANLI PORTFÖY BIST TLREF ENDEKSİ (TL) BORSA YATIRIM FONU","price":46.31769,"share_count":2100000,"num_of_participants":0,"total_portfolio":97267148.26,"borsa_bulletin_price":0,"date":"2025-10-24"},{"fund_code":"DJA","fund_name":"QNB PORTFÖY QNB TEMİZ ENERJİ ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":297.670032,"share_count":165000,"num_of_participants":0,"total_portfolio":49115555.32,"borsa_bulletin_price":0,"date":"2025-10-24"},{"fund_code":"FGA","fund_name":"QNB PORTFÖY ALTIN KATILIM BORSA YATIRIM FONU","price":471.629419,"share_count":29850000,"num_of_participants":0,"total_portfolio":14078138155.41,"borsa_bulletin_price":0,"date":"2025-10-24"},{"fund_code":"FGS","fund_name":"QNB PORTFÖY GÜMÜŞ KATILIM BORSA YATIRIM FONU","price":411.818887,"share_count":73025000,"num_of_participants":0,"total_portfolio":30073074217.71,"borsa_bulletin_price":0,"date":"2025-10-24"},{"fund_code":"FUS","fund_name":"QNB PORTFÖY AMERİKAN DOLARI YABANCI BORSA YATIRIM FONU","price":3923.166645,"share_count":180000,"num_of_participants":0,"total_portfolio":706169996.17,"borsa_bulletin_price":0,"date":"2025-10-24"},{"fund_code":"ILK","fund_name":"İŞ PORTFÖY ALTIN KATILIM BORSA YATIRIM FONU","price":593.159625,"share_count":96200000,"num_of_participants":0,"total_portfolio":57061955907.98,"borsa_bulletin_price":0,"date":"2025-10-24"},{"fund_code":"MDL","fund_name":"AK PORTFÖY BIST 100 ENDEKSİ MODEL PORTFÖY  HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":20.616163,"share_count":10500000,"num_of_participants":0,"total_portfolio":216469709.82,"borsa_bulletin_price":0,"date":"2025-10-24"},{"fund_code":"OHS","fund_name":"OSMANLI PORTFÖY KATILIM 30 ENDEKSİ HİSSE SENEDİ YOĞUN (TL) BORSA YATIRIM FONU","price":48.126057,"share_count":1530000,"num_of_participants":0,"total_portfolio":73632867.17,"borsa_bulletin_price":0,"date":"2025-10-24"},{"fund_code":"OHY","fund_name":"OSMANLI PORTFÖY BİST 30 ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":62.156181,"share_count":1005000,"num_of_participants":0,"total_portfolio":62466961.75,"borsa_bulletin_price":0,"date":"2025-10-24"},{"fund_code":"OPE","fund_name":"OSMANLI PORTFÖY BIST TEMETTÜ 25 ENDEKSİ HİSSE SENEDİ YOĞUN (TL) BORSA YATIRIM FONU","price":40.657695,"share_count":2385000,"num_of_participants":0,"total_portfolio":96968601.64,"borsa_bulletin_price":0,"date":"2025-10-24"},{"fund_code":"OPK","fund_name":"OSMANLI PORTFÖY KAR PAYI ÖDEYEN BIST GYO ENDEKSİ HİSSE SENEDİ YOĞUN (TL) BORSA YATIRIM FONU","price":143.145469,"share_count":495000,"num_of_participants":0,"total_portfolio":70857007.03,"borsa_bulletin_price":0,"date":"2025-10-24"},{"fund_code":"ZBB","fund_name":"ZİRAAT PORTFÖY BIST 30 ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":155.381101,"share_count":128480000,"num_of_participants":0,"total_portfolio":19963363871.77,"borsa_bulletin_price":0,"date":"2025-10-24"},{"fund_code":"ZBP","fund_name":"ZİRAAT PORTFÖY BIST LİKİT BANKA ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":162.141937,"share_count":235440000,"num_of_participants":0,"total_portfolio":38174697554.08,"borsa_bulletin_price":0,"date":"2025-10-24"},{"fund_code":"ZEA","fund_name":"ZİRAAT PORTFÖY BIST 30 EŞİT AĞIRLIKLI ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":137.324659,"share_count":200000,"num_of_participants":0,"total_portfolio":27464931.7,"borsa_bulletin_price":0,"date":"2025-10-24"},{"fund_code":"ZEO","fund_name":"ZİRAAT PORTFÖY BIST 50-30 ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":99.680039,"share_count":400000,"num_of_participants":0,"total_portfolio":39872015.46,"borsa_bulletin_price":0,"date":"2025-10-24"},{"fund_code":"ZGD","fund_name":"ZİRAAT PORTFÖY ALTIN KATILIM  BORSA YATIRIM FONU","price":567.723733,"share_count":149280000,"num_of_participants":0,"total_portfolio":84749798847.83,"borsa_bulletin_price":0,"date":"2025-10-24"},{"fund_code":"ZKE","fund_name":"ZİRAAT PORTFÖY KATILIM 30 EŞİT AĞIRLIKLI ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":111.358569,"share_count":11520000,"num_of_participants":0,"total_portfolio":1282850709.48,"borsa_bulletin_price":0,"date":"2025-10-24"},{"fund_code":"ZKP","fund_name":"ZİRAAT PORTFÖY KATILIM 30 ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":172.632309,"share_count":27640000,"num_of_participants":0,"total_portfolio":4771557019.84,"borsa_bulletin_price":0,"date":"2025-10-24"},{"fund_code":"ZPP","fund_name":"ZİRAAT PORTFÖY BIST BANKA DIŞI LİKİT 10 ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":182.103303,"share_count":9320000,"num_of_participants":0,"total_portfolio":1697202786.44,"borsa_bulletin_price":0,"date":"2025-10-24"},{"fund_code":"ZPT","fund_name":"ZİRAAT PORTFÖY YILDIZ PAZAR TEKNOLOJİ VE İLETİŞİM 10 ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":80.461131,"share_count":400000,"num_of_participants":0,"total_portfolio":32184452.52,"borsa_bulletin_price":0,"date":"2025-10-24"},{"fund_code":"ZRE","fund_name":"ZİRAAT PORTFÖY RİSK EŞİT BANKA DIŞI 20 ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":123.968814,"share_count":480000,"num_of_participants":0,"total_portfolio":59505030.8,"borsa_bulletin_price":0,"date":"2025-10-24"},{"fund_code":"ZSR","fund_name":"ZİRAAT PORTFÖY BIST SÜRDÜRÜLEBİLİRLİK 25 ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":37.271177,"share_count":1200000,"num_of_participants":0,"total_portfolio":44725412.64,"borsa_bulletin_price":0,"date":"2025-10-24"},{"fund_code":"ZTM","fund_name":"ZİRAAT PORTFÖY BIST TEMETTÜ 25 ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":140.723204,"share_count":680000,"num_of_participants":0,"total_portfolio":95691778.58,"borsa_bulletin_price":0,"date":"2025-10-24"},{"fund_code":"BLH","fund_name":"AK PORTFÖY BIST LİKİT BANKA ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":38.061146,"share_count":63400000,"num_of_participants":0,"total_portfolio":2413076633.88,"borsa_bulletin_price":0,"date":"2025-10-23"},{"fund_code":"BND","fund_name":"AK PORTFÖY BIST BANKA DIŞI LİKİT 10 ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":27.032068,"share_count":14300000,"num_of_participants":0,"total_portfolio":386558571.61,"borsa_bulletin_price":0,"date":"2025-10-23"},{"fund_code":"BOE","fund_name":"AK PORTFÖY BIST 30 ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":28.481133,"share_count":46900000,"num_of_participants":0,"total_portfolio":1335765138.58,"borsa_bulletin_price":0,"date":"2025-10-23"},{"fund_code":"BTL","fund_name":"OSMANLI PORTFÖY BIST TLREF ENDEKSİ (TL) BORSA YATIRIM FONU","price":46.268046,"share_count":2100000,"num_of_participants":0,"total_portfolio":97162896.06,"borsa_bulletin_price":0,"date":"2025-10-23"},{"fund_code":"DJA","fund_name":"QNB PORTFÖY QNB TEMİZ ENERJİ ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":305.327403,"share_count":165000,"num_of_participants":0,"total_portfolio":50379021.52,"borsa_bulletin_price":0,"date":"2025-10-23"},{"fund_code":"FGA","fund_name":"QNB PORTFÖY ALTIN KATILIM BORSA YATIRIM FONU","price":458.890066,"share_count":31350000,"num_of_participants":0,"total_portfolio":14386203583.1,"borsa_bulletin_price":0,"date":"2025-10-23"},{"fund_code":"FGS","fund_name":"QNB PORTFÖY GÜMÜŞ KATILIM BORSA YATIRIM FONU","price":403.818055,"share_count":73275000,"num_of_participants":0,"total_portfolio":29589767988.32,"borsa_bulletin_price":0,"date":"2025-10-23"},{"fund_code":"FUS","fund_name":"QNB PORTFÖY AMERİKAN DOLARI YABANCI BORSA YATIRIM FONU","price":3922.380057,"share_count":180000,"num_of_participants":0,"total_portfolio":706028410.3,"borsa_bulletin_price":0,"date":"2025-10-23"},{"fund_code":"ILK","fund_name":"İŞ PORTFÖY ALTIN KATILIM BORSA YATIRIM FONU","price":597.834128,"share_count":96200000,"num_of_participants":0,"total_portfolio":57511643085.37,"borsa_bulletin_price":0,"date":"2025-10-23"},{"fund_code":"MDL","fund_name":"AK PORTFÖY BIST 100 ENDEKSİ MODEL PORTFÖY  HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":20.283824,"share_count":10500000,"num_of_participants":0,"total_portfolio":212980155.78,"borsa_bulletin_price":0,"date":"2025-10-23"},{"fund_code":"OHS","fund_name":"OSMANLI PORTFÖY KATILIM 30 ENDEKSİ HİSSE SENEDİ YOĞUN (TL) BORSA YATIRIM FONU","price":47.840173,"share_count":1530000,"num_of_participants":0,"total_portfolio":73195464.77,"borsa_bulletin_price":0,"date":"2025-10-23"},{"fund_code":"OHY","fund_name":"OSMANLI PORTFÖY BİST 30 ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":61.709873,"share_count":1005000,"num_of_participants":0,"total_portfolio":62018422.59,"borsa_bulletin_price":0,"date":"2025-10-23"},{"fund_code":"OPE","fund_name":"OSMANLI PORTFÖY BIST TEMETTÜ 25 ENDEKSİ HİSSE SENEDİ YOĞUN (TL) BORSA YATIRIM FONU","price":40.271173,"share_count":2385000,"num_of_participants":0,"total_portfolio":96046748.48,"borsa_bulletin_price":0,"date":"2025-10-23"},{"fund_code":"OPK","fund_name":"OSMANLI PORTFÖY KAR PAYI ÖDEYEN BIST GYO ENDEKSİ HİSSE SENEDİ YOĞUN (TL) BORSA YATIRIM FONU","price":142.732354,"share_count":495000,"num_of_participants":0,"total_portfolio":70652515,"borsa_bulletin_price":0,"date":"2025-10-23"},{"fund_code":"ZBB","fund_name":"ZİRAAT PORTFÖY BIST 30 ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":154.264923,"share_count":124320000,"num_of_participants":0,"total_portfolio":19178215198.15,"borsa_bulletin_price":0,"date":"2025-10-23"},{"fund_code":"ZBP","fund_name":"ZİRAAT PORTFÖY BIST LİKİT BANKA ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":161.364314,"share_count":235440000,"num_of_participants":0,"total_portfolio":37991614009.79,"borsa_bulletin_price":0,"date":"2025-10-23"},{"fund_code":"ZEA","fund_name":"ZİRAAT PORTFÖY BIST 30 EŞİT AĞIRLIKLI ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":136.101301,"share_count":200000,"num_of_participants":0,"total_portfolio":27220260.15,"borsa_bulletin_price":0,"date":"2025-10-23"},{"fund_code":"ZEO","fund_name":"ZİRAAT PORTFÖY BIST 50-30 ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":98.515366,"share_count":400000,"num_of_participants":0,"total_portfolio":39406146.27,"borsa_bulletin_price":0,"date":"2025-10-23"},{"fund_code":"ZGD","fund_name":"ZİRAAT PORTFÖY ALTIN KATILIM  BORSA YATIRIM FONU","price":548.480328,"share_count":149280000,"num_of_participants":0,"total_portfolio":81877143416.53,"borsa_bulletin_price":0,"date":"2025-10-23"},{"fund_code":"ZKE","fund_name":"ZİRAAT PORTFÖY KATILIM 30 EŞİT AĞIRLIKLI ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":111.082418,"share_count":11640000,"num_of_participants":0,"total_portfolio":1292999346.02,"borsa_bulletin_price":0,"date":"2025-10-23"},{"fund_code":"ZKP","fund_name":"ZİRAAT PORTFÖY KATILIM 30 ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":171.61077,"share_count":27720000,"num_of_participants":0,"total_portfolio":4757050537.58,"borsa_bulletin_price":0,"date":"2025-10-23"},{"fund_code":"ZPP","fund_name":"ZİRAAT PORTFÖY BIST BANKA DIŞI LİKİT 10 ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":180.913682,"share_count":9320000,"num_of_participants":0,"total_portfolio":1686115518.08,"borsa_bulletin_price":0,"date":"2025-10-23"},{"fund_code":"ZPT","fund_name":"ZİRAAT PORTFÖY YILDIZ PAZAR TEKNOLOJİ VE İLETİŞİM 10 ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":81.157882,"share_count":400000,"num_of_participants":0,"total_portfolio":32463152.62,"borsa_bulletin_price":0,"date":"2025-10-23"},{"fund_code":"ZRE","fund_name":"ZİRAAT PORTFÖY RİSK EŞİT BANKA DIŞI 20 ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":123.061694,"share_count":480000,"num_of_participants":0,"total_portfolio":59069612.99,"borsa_bulletin_price":0,"date":"2025-10-23"},{"fund_code":"ZSR","fund_name":"ZİRAAT PORTFÖY BIST SÜRDÜRÜLEBİLİRLİK 25 ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":37.048028,"share_count":1200000,"num_of_participants":0,"total_portfolio":44457633.94,"borsa_bulletin_price":0,"date":"2025-10-23"},{"fund_code":"ZTM","fund_name":"ZİRAAT PORTFÖY BIST TEMETTÜ 25 ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":139.393897,"share_count":680000,"num_of_participants":0,"total_portfolio":94787850.12,"borsa_bulletin_price":0,"date":"2025-10-23"},{"fund_code":"BLH","fund_name":"AK PORTFÖY BIST LİKİT BANKA ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":37.832628,"share_count":63400000,"num_of_participants":0,"total_portfolio":2398588587.97,"borsa_bulletin_price":0,"date":"2025-10-22"},{"fund_code":"BND","fund_name":"AK PORTFÖY BIST BANKA DIŞI LİKİT 10 ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":26.842189,"share_count":14300000,"num_of_participants":0,"total_portfolio":383843300.95,"borsa_bulletin_price":0,"date":"2025-10-22"},{"fund_code":"BOE","fund_name":"AK PORTFÖY BIST 30 ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":28.242156,"share_count":46900000,"num_of_participants":0,"total_portfolio":1324557095.43,"borsa_bulletin_price":0,"date":"2025-10-22"},{"fund_code":"BTL","fund_name":"OSMANLI PORTFÖY BIST TLREF ENDEKSİ (TL) BORSA YATIRIM FONU","price":46.218728,"share_count":2100000,"num_of_participants":0,"total_portfolio":97059329.12,"borsa_bulletin_price":0,"date":"2025-10-22"},{"fund_code":"DJA","fund_name":"QNB PORTFÖY QNB TEMİZ ENERJİ ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":312.729743,"share_count":165000,"num_of_participants":0,"total_portfolio":51600407.57,"borsa_bulletin_price":0,"date":"2025-10-22"},{"fund_code":"FGA","fund_name":"QNB PORTFÖY ALTIN KATILIM BORSA YATIRIM FONU","price":470.125866,"share_count":31600000,"num_of_participants":0,"total_portfolio":14855977351.82,"borsa_bulletin_price":0,"date":"2025-10-22"},{"fund_code":"FGS","fund_name":"QNB PORTFÖY GÜMÜŞ KATILIM BORSA YATIRIM FONU","price":408.720347,"share_count":73275000,"num_of_participants":0,"total_portfolio":29948983425.84,"borsa_bulletin_price":0,"date":"2025-10-22"},{"fund_code":"FUS","fund_name":"QNB PORTFÖY AMERİKAN DOLARI YABANCI BORSA YATIRIM FONU","price":3921.126458,"share_count":180000,"num_of_participants":0,"total_portfolio":705802762.39,"borsa_bulletin_price":0,"date":"2025-10-22"},{"fund_code":"ILK","fund_name":"İŞ PORTFÖY ALTIN KATILIM BORSA YATIRIM FONU","price":627.036336,"share_count":96200000,"num_of_participants":0,"total_portfolio":60320895549.14,"borsa_bulletin_price":0,"date":"2025-10-22"},{"fund_code":"MDL","fund_name":"AK PORTFÖY BIST 100 ENDEKSİ MODEL PORTFÖY  HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":19.991997,"share_count":10500000,"num_of_participants":0,"total_portfolio":209915973.28,"borsa_bulletin_price":0,"date":"2025-10-22"},{"fund_code":"OHS","fund_name":"OSMANLI PORTFÖY KATILIM 30 ENDEKSİ HİSSE SENEDİ YOĞUN (TL) BORSA YATIRIM FONU","price":47.501658,"share_count":1530000,"num_of_participants":0,"total_portfolio":72677537.41,"borsa_bulletin_price":0,"date":"2025-10-22"},{"fund_code":"OHY","fund_name":"OSMANLI PORTFÖY BİST 30 ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":61.210553,"share_count":1005000,"num_of_participants":0,"total_portfolio":61516606.08,"borsa_bulletin_price":0,"date":"2025-10-22"},{"fund_code":"OPE","fund_name":"OSMANLI PORTFÖY BIST TEMETTÜ 25 ENDEKSİ HİSSE SENEDİ YOĞUN (TL) BORSA YATIRIM FONU","price":39.66544,"share_count":2385000,"num_of_participants":0,"total_portfolio":94602073.78,"borsa_bulletin_price":0,"date":"2025-10-22"},{"fund_code":"OPK","fund_name":"OSMANLI PORTFÖY KAR PAYI ÖDEYEN BIST GYO ENDEKSİ HİSSE SENEDİ YOĞUN (TL) BORSA YATIRIM FONU","price":141.424439,"share_count":495000,"num_of_participants":0,"total_portfolio":70005097.41,"borsa_bulletin_price":0,"date":"2025-10-22"},{"fund_code":"ZBB","fund_name":"ZİRAAT PORTFÖY BIST 30 ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":153.003906,"share_count":123760000,"num_of_participants":0,"total_portfolio":18935763431.89,"borsa_bulletin_price":0,"date":"2025-10-22"},{"fund_code":"ZBP","fund_name":"ZİRAAT PORTFÖY BIST LİKİT BANKA ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":160.393966,"share_count":237480000,"num_of_participants":0,"total_portfolio":38090359084.65,"borsa_bulletin_price":0,"date":"2025-10-22"},{"fund_code":"ZEA","fund_name":"ZİRAAT PORTFÖY BIST 30 EŞİT AĞIRLIKLI ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":134.896923,"share_count":200000,"num_of_participants":0,"total_portfolio":26979384.5,"borsa_bulletin_price":0,"date":"2025-10-22"},{"fund_code":"ZEO","fund_name":"ZİRAAT PORTFÖY BIST 50-30 ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":98.333685,"share_count":400000,"num_of_participants":0,"total_portfolio":39333474.18,"borsa_bulletin_price":0,"date":"2025-10-22"},{"fund_code":"ZGD","fund_name":"ZİRAAT PORTFÖY ALTIN KATILIM  BORSA YATIRIM FONU","price":576.328659,"share_count":120280000,"num_of_participants":0,"total_portfolio":69320811164.4,"borsa_bulletin_price":0,"date":"2025-10-22"},{"fund_code":"ZKE","fund_name":"ZİRAAT PORTFÖY KATILIM 30 EŞİT AĞIRLIKLI ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":110.371852,"share_count":11520000,"num_of_participants":0,"total_portfolio":1271483737.41,"borsa_bulletin_price":0,"date":"2025-10-22"},{"fund_code":"ZKP","fund_name":"ZİRAAT PORTFÖY KATILIM 30 ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":170.373337,"share_count":27440000,"num_of_participants":0,"total_portfolio":4675044360.82,"borsa_bulletin_price":0,"date":"2025-10-22"},{"fund_code":"ZPP","fund_name":"ZİRAAT PORTFÖY BIST BANKA DIŞI LİKİT 10 ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":179.648915,"share_count":9320000,"num_of_participants":0,"total_portfolio":1674327890.62,"borsa_bulletin_price":0,"date":"2025-10-22"},{"fund_code":"ZPT","fund_name":"ZİRAAT PORTFÖY YILDIZ PAZAR TEKNOLOJİ VE İLETİŞİM 10 ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":80.658609,"share_count":400000,"num_of_participants":0,"total_portfolio":32263443.73,"borsa_bulletin_price":0,"date":"2025-10-22"},{"fund_code":"ZRE","fund_name":"ZİRAAT PORTFÖY RİSK EŞİT BANKA DIŞI 20 ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":121.752955,"share_count":480000,"num_of_participants":0,"total_portfolio":58441418.4,"borsa_bulletin_price":0,"date":"2025-10-22"},{"fund_code":"ZSR","fund_name":"ZİRAAT PORTFÖY BIST SÜRDÜRÜLEBİLİRLİK 25 ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":36.709787,"share_count":1240000,"num_of_participants":0,"total_portfolio":45520135.65,"borsa_bulletin_price":0,"date":"2025-10-22"},{"fund_code":"ZTM","fund_name":"ZİRAAT PORTFÖY BIST TEMETTÜ 25 ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":137.322366,"share_count":680000,"num_of_participants":0,"total_portfolio":93379208.56,"borsa_bulletin_price":0,"date":"2025-10-22"},{"fund_code":"BLH","fund_name":"AK PORTFÖY BIST LİKİT BANKA ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":37.493296,"share_count":63400000,"num_of_participants":0,"total_portfolio":2377074974.71,"borsa_bulletin_price":0,"date":"2025-10-21"},{"fund_code":"BND","fund_name":"AK PORTFÖY BIST BANKA DIŞI LİKİT 10 ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":26.971926,"share_count":14300000,"num_of_participants":0,"total_portfolio":385698540.51,"borsa_bulletin_price":0,"date":"2025-10-21"},{"fund_code":"BOE","fund_name":"AK PORTFÖY BIST 30 ENDEKSİ HİSSE SENEDİ YOĞUN BORSA YATIRIM FONU","price":28.290703,"share_count":45400000,"num_of_participants":0

0      AK PORTFÖY BIST LİKİT BANKA ENDEKSİ HİSSE SENE...
1      AK PORTFÖY BIST BANKA DIŞI LİKİT 10 ENDEKSİ Hİ...
2      AK PORTFÖY BIST 30 ENDEKSİ HİSSE SENEDİ YOĞUN ...
3      OSMANLI PORTFÖY BIST TLREF ENDEKSİ (TL) BORSA ...
4      QNB PORTFÖY QNB TEMİZ ENERJİ ENDEKSİ HİSSE SEN...
                             ...
125    ZİRAAT PORTFÖY BIST BANKA DIŞI LİKİT 10 ENDEKS...
126    ZİRAAT PORTFÖY YILDIZ PAZAR TEKNOLOJİ VE İLETİ...
127    ZİRAAT PORTFÖY RİSK EŞİT BANKA DIŞI 20 ENDEKSİ...
128    ZİRAAT PORTFÖY BIST SÜRDÜRÜLEBİLİRLİK 25 ENDEK...
129    ZİRAAT PORTFÖY BIST TEMETTÜ 25 ENDEKSİ HİSSE S...
Name: fund_name, Length: 130, dtype: object

In [ ]:
import http.client
import json
import pandas as pd
from time import sleep

headers = {
    'x-rapidapi-key': "c3c297e087mshf0c09b3c9068e2fp1ae78fjsnf0b02d992e8a",
    'x-rapidapi-host': "tefas-api.p.rapidapi.com"
}

conn = http.client.HTTPSConnection("tefas-api.p.rapidapi.com")

# 1️⃣ Tüm fon listesini çek
conn.request("GET", "/api/v1/funds", headers=headers)
res = conn.getresponse()
data = json.loads(res.read().decode("utf-8"))

funds = data.get("data", [])
print(f"Toplam {len(funds)} fon bulundu.")
print("İlk 5 fon:", funds[:5])

# 2️⃣ Her fon için geçmiş verileri çek
all_fund_data = []
for fund in funds:
    code = fund["key"]
    print(f"Fon çekiliyor: {code}")
    conn.request("GET", f"/api/v1/funds/historical?fundCode={code}", headers=headers)
    res = conn.getresponse()
    fund_data = json.loads(res.read().decode("utf-8"))
    records = fund_data.get("data", [])
    if records:
        for r in records:
            r["fund_code"] = code
        all_fund_data.extend(records)
    sleep(0.2)  # RapidAPI rate limit için

# 3️⃣ DataFrame’e çevir
df = pd.DataFrame(all_fund_data)
print(df.head())

# 4️⃣ Örnek: Fon getirilerini hesaplamak
df["return_percent"] = df["price"].pct_change() * 100

Toplam 3304 fon bulundu.
İlk 5 fon: [{'key': 'AVJ', 'value': 'AGESA EMEKLİLİK VE HAYAT A.Ş. BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU'}, {'key': 'AVY', 'value': 'AGESA HAYAT VE EMEKLİLİK A.Ş.  KARMA GRUP EMEKLİLİK YATIRIM FONU'}, {'key': 'AVE', 'value': 'AGESA HAYAT VE EMEKLİLİK A.Ş. AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU'}, {'key': 'EAE', 'value': 'AGESA HAYAT VE EMEKLİLİK A.Ş. ALTIN EMEKLİLİK YATIRIM FONU'}, {'key': 'GEV', 'value': 'AGESA HAYAT VE EMEKLİLİK A.Ş. ALTIN KATILIM EMEKLİLİK YATIRIM FONU'}]
Fon çekiliyor: AVJ
Fon çekiliyor: AVY
Fon çekiliyor: AVE
Fon çekiliyor: EAE
Fon çekiliyor: GEV
Fon çekiliyor: AHJ
Fon çekiliyor: AVH
Fon çekiliyor: AE4
Fon çekiliyor: MZN
Fon çekiliyor: AE1
Fon çekiliyor: AE2
Fon çekiliyor: AEK
Fon çekiliyor: AVP
Fon çekiliyor: AVG
Fon çekiliyor: AE3
Fon çekiliyor: ENF
Fon çekiliyor: AEH
Fon çekiliyor: AEB
Fon çekiliyor: AVU
Fon çekiliyor: MZL
Fon çekiliyor: AVL
Fon çekiliyor: AVB
Fon çekiliyor: AVD
Fon çekiliyor: EHK
Fon çekiliyor: FYL
Fon çekiliyor: FYN
Fon çekiliyor: AEI
Fon çekiliyor: KML
Fon çekiliyor: AEG
Fon çekiliyor: VVA
Fon çekiliyor: VVZ
Fon çekiliyor: VVE
Fon çekiliyor: VVD
Fon çekiliyor: VVU
Fon çekiliyor: AYJ
Fon çekiliyor: VVM
Fon çekiliyor: AAJ
Fon çekiliyor: AVK
Fon çekiliyor: AVO
Fon çekiliyor: SBA
Fon çekiliyor: AVN
Fon çekiliyor: GFH
Fon çekiliyor: TVC
Fon çekiliyor: TSZ
Fon çekiliyor: AVR
Fon çekiliyor: TVH
Fon çekiliyor: MZP
Fon çekiliyor: CJF
Fon çekiliyor: SSO
Fon çekiliyor: PUD
Fon çekiliyor: FUM
Fon çekiliyor: ANL
Fon çekiliyor: AOY
Fon çekiliyor: AFO
Fon çekiliyor: PAL
Fon çekiliyor: AFA
Fon çekiliyor: AFV
Fon çekiliyor: AJL
Fon çekiliyor: BNC
Fon çekiliyor: BND
Fon çekiliyor: ADP
Fon çekiliyor: BLH
Fon çekiliyor: APJ
Fon çekiliyor: BDY
Fon çekiliyor: MDL
Fon çekiliyor: AKU
Fon çekiliyor: BOE
Fon çekiliyor: ABU
Fon çekiliyor: ARL
Fon çekiliyor: BHE
Fon çekiliyor: LTC
Fon çekiliyor: CVE
Fon çekiliyor: PUC
Fon çekiliyor: PUR
Fon çekiliyor: URG
Fon çekiliyor: BVC
Fon çekiliyor: BUY
Fon çekiliyor: VAY
Fon çekiliyor: CJH
Fon çekiliyor: DZS
Fon çekiliyor: AJN
Fon çekiliyor: DSH
Fon çekiliyor: VCY
Fon çekiliyor: EML
Fon çekiliyor: AVZ
Fon çekiliyor: KVT
Fon çekiliyor: AKE
Fon çekiliyor: ZFB
Fon çekiliyor: UCN
Fon çekiliyor: URV
Fon çekiliyor: GUM
Fon çekiliyor: GMI
Fon çekiliyor: HVV
Fon çekiliyor: HYY
Fon çekiliyor: HZV
Fon çekiliyor: AK3
Fon çekiliyor: PAI
Fon çekiliyor: GNZ
Fon çekiliyor: FUA
Fon çekiliyor: AGC
Fon çekiliyor: ARM
Fon çekiliyor: BRR
Fon çekiliyor: PPJ
Fon çekiliyor: CVB
Fon çekiliyor: KUP
Fon çekiliyor: ALC
Fon çekiliyor: KH1
Fon çekiliyor: KHO
Fon çekiliyor: AVT
Fon çekiliyor: GGC
Fon çekiliyor: KNP
Fon çekiliyor: ZLG
Fon çekiliyor: MTV
Fon çekiliyor: AIM
Fon çekiliyor: PAP
Fon çekiliyor: KNZ
Fon çekiliyor: ADE
Fon çekiliyor: MU1
Fon çekiliyor: LHM
Fon çekiliyor: OBN
Fon çekiliyor: OBR
Fon çekiliyor: ODN
Fon çekiliyor: ONK
Fon çekiliyor: URC
Fon çekiliyor: OSN
Fon çekiliyor: OUN
Fon çekiliyor: KNV
Fon çekiliyor: URS
Fon çekiliyor: APT
Fon çekiliyor: URM
Fon çekiliyor: OPZ
Fon çekiliyor: PUT
Fon çekiliyor: ARP
Fon çekiliyor: CVD
Fon çekiliyor: ARF
Fon çekiliyor: CVC
Fon çekiliyor: AZZ
Fon çekiliyor: UHV
Fon çekiliyor: KNC
Fon çekiliyor: UHN
Fon çekiliyor: BVB
Fon çekiliyor: AYR
Fon çekiliyor: AIS
Fon çekiliyor: ALE
Fon çekiliyor: AES
Fon çekiliyor: PUV
Fon çekiliyor: AZF
Fon çekiliyor: APP
Fon çekiliyor: DTZ
Fon çekiliyor: AIH
Fon çekiliyor: SAS
Fon çekiliyor: AFS
Fon çekiliyor: CJG
Fon çekiliyor: CJD
Fon çekiliyor: SCZ
Fon çekiliyor: CVF
Fon çekiliyor: SAP
Fon çekiliyor: TAR
Fon çekiliyor: ICZ
Fon çekiliyor: TGR
Fon çekiliyor: AK2
Fon çekiliyor: AUV
Fon çekiliyor: ODV
Fon çekiliyor: CVA
Fon çekiliyor: BGP
Fon çekiliyor: AJE
Fon çekiliyor: KNT
Fon çekiliyor: LHP
Fon çekiliyor: YDH
Fon çekiliyor: AFT
Fon çekiliyor: ICI
Fon çekiliyor: AK5
Fon çekiliyor: BGY
Fon çekiliyor: AK4
Fon çekiliyor: IDG
Fon çekiliyor: DDN
Fon çekiliyor: IJG
Fon çekiliyor: JST
Fon çekiliyor: SGF
Fon çekiliyor: IUG
Fon çekiliyor: TAV
Fon çekiliyor: AGN
Fon çekiliyor: BYG
Fon çekiliyor: IKG
Fon çekiliyor: SHG
Fon çekiliyor: AJK
Fon çekiliyor: YRB
Fon çekiliyor: SDA
Fon çekiliyor: CYD
Fon çekiliyor: SER
Fon çekiliyor: COT
Fon çekiliyor: AB1
Fon çekiliyor: ONN
Fon çekiliyor: DSU
Fon çekiliyor: MPD
Fon çekiliyor: MJL
Fon çekiliyor: MKG
Fon çekiliyor: YBJ
Fon çekiliyor: HRZ
Fon çekiliyor: MMH
Fon çekiliyor: MJB
Fon çekiliyor: ONE
Fon çekiliyor: CIN
Fon çekiliyor: BOL
Fon çekiliyor: GLG
Fon çekiliyor: ENJ
Fon çekiliyor: ESG
Fon çekiliyor: MJH
Fon çekiliyor: MJG
Fon çekiliyor: FLY
Fon çekiliyor: ASJ
Fon çekiliyor: MPN
Fon çekiliyor: EYT
Fon çekiliyor: DB2
Fon çekiliyor: LKT
Fon çekiliyor: BUL
Fon çekiliyor: SPT
Fon çekiliyor: MPS
Fon çekiliyor: MPF
Fon çekiliyor: NKL
Fon çekiliyor: MPK
Fon çekiliyor: TLK
Fon çekiliyor: PPV
Fon çekiliyor: IDL
Fon çekiliyor: GPT
Fon çekiliyor: MLS
Fon çekiliyor: MTS
Fon çekiliyor: CPU
Fon çekiliyor: TFE
Fon çekiliyor: DOL
Fon çekiliyor: GLC
Fon çekiliyor: MPT
Fon çekiliyor: LTI
Fon çekiliyor: MGA
Fon çekiliyor: MBB
Fon çekiliyor: FUT
Fon çekiliyor: HMN
Fon çekiliyor: MPG
Fon çekiliyor: MBK
Fon çekiliyor: NKB
Fon çekiliyor: NEV
Fon çekiliyor: NKE
Fon çekiliyor: PLY
Fon çekiliyor: SGS
Fon çekiliyor: STO
Fon çekiliyor: MUG
Fon çekiliyor: MYP
Fon çekiliyor: AG8
Fon çekiliyor: RTI
Fon çekiliyor: AL4
Fon çekiliyor: RBA
Fon çekiliyor: CKF
Fon çekiliyor: KAC
Fon çekiliyor: HFY
Fon çekiliyor: KSM
Fon çekiliyor: KSL
Fon çekiliyor: AL7
Fon çekiliyor: VKR
Fon çekiliyor: RBK
Fon çekiliyor: RBH
Fon çekiliyor: AL5
Fon çekiliyor: MJE
Fon çekiliyor: PVK
Fon çekiliyor: RBV
Fon çekiliyor: RBT
Fon çekiliyor: PPG
Fon çekiliyor: URD
Fon çekiliyor: URY
Fon çekiliyor: RPU
Fon çekiliyor: VKI
Fon çekiliyor: AL6
Fon çekiliyor: PJG
Fon çekiliyor: PBA
Fon çekiliyor: OYE
Fon çekiliyor: AK6
Fon çekiliyor: PAT
Fon çekiliyor: BKA
Fon çekiliyor: PIH
Fon çekiliyor: VNE
Fon çekiliyor: PGB
Fon çekiliyor: BKI
Fon çekiliyor: PBV
Fon çekiliyor: BGV
Fon çekiliyor: PG4
Fon çekiliyor: BTH
Fon çekiliyor: AL8
Fon çekiliyor: AG9
Fon çekiliyor: OYK
Fon çekiliyor: FTC
Fon çekiliyor: ABZ
Fon çekiliyor: DKI
Fon çekiliyor: AG5
Fon çekiliyor: PFG
Fon çekiliyor: FOG
Fon çekiliyor: SAG
Fon çekiliyor: PG2
Fon çekiliyor: PG7
Fon çekiliyor: PG6
Fon çekiliyor: INJ
Fon çekiliyor: OYR
Fon çekiliyor: DCS
Fon çekiliyor: PII
Fon çekiliyor: AG7
Fon çekiliyor: PHG
Fon çekiliyor: AHR
Fon çekiliyor: PG1
Fon çekiliyor: AG6
Fon çekiliyor: SGL
Fon çekiliyor: CTY
Fon çekiliyor: THZ
Fon çekiliyor: RTM
Fon çekiliyor: PG5
Fon çekiliyor: PGG
Fon çekiliyor: UNB
Fon çekiliyor: PG3
Fon çekiliyor: PIG
Fon çekiliyor: GGF
Fon çekiliyor: YNT
Fon çekiliyor: PG8
Fon çekiliyor: PG9
Fon çekiliyor: OYZ
Fon çekiliyor: PEG
Fon çekiliyor: STM
Fon çekiliyor: CAF
Fon çekiliyor: NDL
Fon çekiliyor: RYA
Fon çekiliyor: SLN
Fon çekiliyor: AS3
Fon çekiliyor: TMH
Fon çekiliyor: LLA
Fon çekiliyor: BHV
Fon çekiliyor: ABJ
Fon çekiliyor: BBI
Fon çekiliyor: BBP
Fon çekiliyor: HVU
Fon çekiliyor: BFE
Fon çekiliyor: BVM
Fon çekiliyor: HVZ
Fon çekiliyor: HVT
Fon çekiliyor: AS1
Fon çekiliyor: DEF
Fon çekiliyor: DEI
Fon çekiliyor: ESN
Fon çekiliyor: GIH
Fon çekiliyor: LID
Fon çekiliyor: IHZ
Fon çekiliyor: IHA
Fon çekiliyor: AOJ
Fon çekiliyor: PKE
Fon çekiliyor: KHT
Fon çekiliyor: KHF
Fon çekiliyor: KST
Fon çekiliyor: KLS
Fon çekiliyor: KKL
Fon çekiliyor: PRU
Fon çekiliyor: AEV
Fon çekiliyor: SLS
Fon çekiliyor: BSY
Fon çekiliyor: GNE
Fon çekiliyor: AS2
Fon çekiliyor: BGA
Fon çekiliyor: DRG
Fon çekiliyor: ELI
Fon çekiliyor: AB2
Fon çekiliyor: LLI
Fon çekiliyor: LLU
Fon çekiliyor: AZD
Fon çekiliyor: AZK
Fon çekiliyor: AZA
Fon çekiliyor: AUG
Fon çekiliyor: AZH
Fon çekiliyor: HFS
Fon çekiliyor: AZL
Fon çekiliyor: AZS
Fon çekiliyor: AZY
Fon çekiliyor: ALU
Fon çekiliyor: AMZ
Fon çekiliyor: AEZ
Fon çekiliyor: FOA
Fon çekiliyor: ALZ
Fon çekiliyor: ACV
Fon çekiliyor: AEU
Fon çekiliyor: AMG
Fon çekiliyor: ALS
Fon çekiliyor: AUA
Fon çekiliyor: AEN
Fon çekiliyor: AMR
Fon çekiliyor: ALR
Fon çekiliyor: AMY
Fon çekiliyor: FYY
Fon çekiliyor: FYU
Fon çekiliyor: AMF
Fon çekiliyor: KOE
Fon çekiliyor: ALI
Fon çekiliyor: ALJ
Fon çekiliyor: AIP
Fon çekiliyor: AIE
Fon çekiliyor: ANJ
Fon çekiliyor: ANP
Fon çekiliyor: KOS
Fon çekiliyor: KOA
Fon çekiliyor: AFJ
Fon çekiliyor: APG
Fon çekiliyor: AEC
Fon çekiliyor: AEP
Fon çekiliyor: HSR
Fon çekiliyor: YZD
Fon çekiliyor: AHL
Fon çekiliyor: BGL
Fon çekiliyor: AEA
Fon çekiliyor: AH0
Fon çekiliyor: AO1
Fon çekiliyor: AO2
Fon çekiliyor: AH6
Fon çekiliyor: AH3
Fon çekiliyor: HS1
Fon çekiliyor: AG2
Fon çekiliyor: AH9
Fon çekiliyor: GMF
Fon çekiliyor: AH5
Fon çekiliyor: AG3
Fon çekiliyor: AH1
Fon çekiliyor: AG1
Fon çekiliyor: AHB
Fon çekiliyor: AH4
Fon çekiliyor: ATE
Fon çekiliyor: AER
Fon çekiliyor: AGE
Fon çekiliyor: AET
Fon çekiliyor: MDK
Fon çekiliyor: AJA
Fon çekiliyor: AJG
Fon çekiliyor: AJB
Fon çekiliyor: AJH
Fon çekiliyor: AJC
Fon çekiliyor: AFP
Fon çekiliyor: AFH
Fon çekiliyor: AJF
Fon çekiliyor: AHC
Fon çekiliyor: AH2
Fon çekiliyor: ATK
Fon çekiliyor: BHS
Fon çekiliyor: TVG
Fon çekiliyor: BHT
Fon çekiliyor: BNO
Fon çekiliyor: AH8
Fon çekiliyor: AG4
Fon çekiliyor: MDD
Fon çekiliyor: ABE
Fon çekiliyor: AY1
Fon çekiliyor: BII
Fon çekiliyor: NGC
Fon çekiliyor: NGK
Fon çekiliyor: GYU
Fon çekiliyor: ERS
Fon çekiliyor: RBG
Fon çekiliyor: RGB
Fon çekiliyor: DGG
Fon çekiliyor: RYZ
Fon çekiliyor: NG6
Fon çekiliyor: SGG
Fon çekiliyor: RBU
Fon çekiliyor: YGG
Fon çekiliyor: AR6
Fon çekiliyor: AZ7
Fon çekiliyor: AR1
Fon çekiliyor: AZ1
Fon çekiliyor: AIV
Fon çekiliyor: BGU
Fon çekiliyor: ON3
Fon çekiliyor: AZ6
Fon çekiliyor: AZ9
Fon çekiliyor: AZ2
Fon çekiliyor: AZ4
Fon çekiliyor: ZG6
Fon çekiliyor: ON6
Fon çekiliyor: OBG
Fon çekiliyor: ON1
Fon çekiliyor: ON4
Fon çekiliyor: ON2
Fon çekiliyor: ON8
Fon çekiliyor: ONU
Fon çekiliyor: ON0
Fon çekiliyor: ONA
Fon çekiliyor: AO7
Fon çekiliyor: ZG8
Fon çekiliyor: AR8
Fon çekiliyor: BYF
Fon çekiliyor: AZ8
Fon çekiliyor: ZG7
Fon çekiliyor: AZ3
Fon çekiliyor: AZ5
Fon çekiliyor: AR9
Fon çekiliyor: LRT
Fon çekiliyor: PKF
Fon çekiliyor: THV
Fon çekiliyor: YCL
Fon çekiliyor: AED
Fon çekiliyor: AAK
Fon çekiliyor: AUT
Fon çekiliyor: ANZ
Fon çekiliyor: URA
Fon çekiliyor: AAS
Fon çekiliyor: NKJ
Fon çekiliyor: JET
Fon çekiliyor: AAV
Fon çekiliyor: AVC
Fon çekiliyor: AYA
Fon çekiliyor: TLZ
Fon çekiliyor: DGH
Fon çekiliyor: AAL
Fon çekiliyor: RTG
Fon çekiliyor: RSF
Fon çekiliyor: YLC
Fon çekiliyor: BCG
Fon çekiliyor: NKK
Fon çekiliyor: LGO
Fon çekiliyor: TAL
Fon çekiliyor: BSH
Fon çekiliyor: AP5
Fon çekiliyor: AP2
Fon çekiliyor: BTZ
Fon çekiliyor: AHI
Fon çekiliyor: BAC
Fon çekiliyor: AHU
Fon çekiliyor: AP4
Fon çekiliyor: ABG
Fon çekiliyor: PFS
Fon çekiliyor: SSE
Fon çekiliyor: LAI
Fon çekiliyor: KHD
Fon çekiliyor: BTJ
Fon çekiliyor: KHJ
Fon çekiliyor: KLH
Fon çekiliyor: PSE
Fon çekiliyor: PPT
Fon çekiliyor: SNY
Fon çekiliyor: STI
Fon çekiliyor: DFI
Fon çekiliyor: ZVB
Fon çekiliyor: AHN
Fon çekiliyor: GCD
Fon çekiliyor: UHS
Fon çekiliyor: GLM
Fon çekiliyor: ZVE
Fon çekiliyor: AT1
Fon çekiliyor: BRI
Fon çekiliyor: BAK
Fon çekiliyor: BLM
Fon çekiliyor: BNE
Fon çekiliyor: BN2
Fon çekiliyor: BGM
Fon çekiliyor: GKR
Fon çekiliyor: GTR
Fon çekiliyor: MAH
Fon çekiliyor: BRE
Fon çekiliyor: GJS
Fon çekiliyor: ZVD
Fon çekiliyor: GUG
Fon çekiliyor: TOG
Fon çekiliyor: BDC
Fon çekiliyor: IYB
Fon çekiliyor: DLN
Fon çekiliyor: ESP
Fon çekiliyor: TLH
Fon çekiliyor: TPV
Fon çekiliyor: JUP
Fon çekiliyor: MTL
Fon çekiliyor: PRH
Fon çekiliyor: TLE
Fon çekiliyor: BZG
Fon çekiliyor: KUE
Fon çekiliyor: SBG
Fon çekiliyor: HEA
Fon çekiliyor: HEL
Fon çekiliyor: HEG
Fon çekiliyor: HEB
Fon çekiliyor: RZN
Fon çekiliyor: HES
Fon çekiliyor: HED
Fon çekiliyor: HEE
Fon çekiliyor: HER
Fon çekiliyor: RZM
Fon çekiliyor: HET
Fon çekiliyor: AJR
Fon çekiliyor: AJZ
Fon çekiliyor: AJP
Fon çekiliyor: AJY
Fon çekiliyor: AJV
Fon çekiliyor: HEI
Fon çekiliyor: HEC
Fon çekiliyor: AJT
Fon çekiliyor: HEP
Fon çekiliyor: HEK
Fon çekiliyor: SPD
Fon çekiliyor: FRA
Fon çekiliyor: TKH
Fon çekiliyor: SPE
Fon çekiliyor: SPA
Fon çekiliyor: ZFL
Fon çekiliyor: GLS
Fon çekiliyor: PAC
Fon çekiliyor: DTP
Fon çekiliyor: PUA
Fon çekiliyor: THS
Fon çekiliyor: GP1
Fon çekiliyor: SFS
Fon çekiliyor: PPF
Fon çekiliyor: LCT
Fon çekiliyor: RKL
Fon çekiliyor: KMF
Fon çekiliyor: UHL
Fon çekiliyor: FYZ
Fon çekiliyor: SRA
Fon çekiliyor: AHZ
Fon çekiliyor: VFS
Fon çekiliyor: NTB
Fon çekiliyor: BFT
Fon çekiliyor: BAO
Fon çekiliyor: BGH
Fon çekiliyor: BLG
Fon çekiliyor: RCV
Fon çekiliyor: HJA
Fon çekiliyor: AZV
Fon çekiliyor: PBS
Fon çekiliyor: BUT
Fon çekiliyor: BUP
Fon çekiliyor: HUI
Fon çekiliyor: TRN
Fon çekiliyor: CSS
Fon çekiliyor: AII
Fon çekiliyor: ATJ
Fon çekiliyor: GMA
Fon çekiliyor: AHV
Fon çekiliyor: DZP
Fon çekiliyor: AHH
Fon çekiliyor: HIZ
Fon çekiliyor: DFO
Fon çekiliyor: FDV
Fon çekiliyor: VCG
Fon çekiliyor: FYB
Fon çekiliyor: UFH
Fon çekiliyor: GBZ
Fon çekiliyor: EHS
Fon çekiliyor: IJF
Fon çekiliyor: AIR
Fon çekiliyor: FNE
Fon çekiliyor: FRZ
Fon çekiliyor: GMO
Fon çekiliyor: GSL
Fon çekiliyor: BVT
Fon çekiliyor: GSG
Fon çekiliyor: CBO
Fon çekiliyor: HPJ
Fon çekiliyor: NOV
Fon çekiliyor: PRF
Fon çekiliyor: AIG
Fon çekiliyor: OMG
Fon çekiliyor: LGK
Fon çekiliyor: KSK
Fon çekiliyor: KNI
Fon çekiliyor: VCD
Fon çekiliyor: LZV
Fon çekiliyor: EJG
Fon çekiliyor: IZA
Fon çekiliyor: IDI
Fon çekiliyor: SPN
Fon çekiliyor: HYP
Fon çekiliyor: IZM
Fon çekiliyor: KTI
Fon çekiliyor: KVS
Fon çekiliyor: SYF
Fon çekiliyor: KOT
Fon çekiliyor: PTG
Fon çekiliyor: PUZ
Fon çekiliyor: MTI
Fon çekiliyor: MSK
Fon çekiliyor: MCU
Fon çekiliyor: NLD
Fon çekiliyor: DOR
Fon çekiliyor: ORI
Fon çekiliyor: OTM
Fon çekiliyor: FYG
Fon çekiliyor: PPZ
Fon çekiliyor: PGS
Fon çekiliyor: PNR
Fon çekiliyor: SAT
Fon çekiliyor: PSS
Fon çekiliyor: GNK
Fon çekiliyor: SHS
Fon çekiliyor: SRE
Fon çekiliyor: SRO
Fon çekiliyor: SVS
Fon çekiliyor: SYL
Fon çekiliyor: TAZ
Fon çekiliyor: TJL
Fon çekiliyor: TEJ
Fon çekiliyor: TMU
Fon çekiliyor: TSP
Fon çekiliyor: USS
Fon çekiliyor: FYM
Fon çekiliyor: VTF
Fon çekiliyor: GBC
Fon çekiliyor: YPR
Fon çekiliyor: PYF
Fon çekiliyor: ABW
Fon çekiliyor: BRP
Fon çekiliyor: COS
Fon çekiliyor: CVT
Fon çekiliyor: CGS
Fon çekiliyor: TTJ
Fon çekiliyor: FBM
Fon çekiliyor: FTR
Fon çekiliyor: GRG
Fon çekiliyor: IGJ
Fon çekiliyor: ITY
Fon çekiliyor: IUL
Fon çekiliyor: THC
Fon çekiliyor: POV
Fon çekiliyor: ZGU
Fon çekiliyor: ZPS
Fon çekiliyor: TOP
Fon çekiliyor: PYH
Fon çekiliyor: PYL
Fon çekiliyor: HMT
Fon çekiliyor: BJD
Fon çekiliyor: DOD
Fon çekiliyor: HGT
Fon çekiliyor: FDZ
Fon çekiliyor: DVU
Fon çekiliyor: IBJ
Fon çekiliyor: THO
Fon çekiliyor: IOT
Fon çekiliyor: ZMT
Fon çekiliyor: ZMU
Fon çekiliyor: YDM
Fon çekiliyor: SYR
Fon çekiliyor: AY6
Fon çekiliyor: AY7
Fon çekiliyor: FYI
Fon çekiliyor: GSE
Fon çekiliyor: PSL
Fon çekiliyor: PSG
Fon çekiliyor: GTF
Fon çekiliyor: GL1
Fon çekiliyor: IBG
Fon çekiliyor: GSP
Fon çekiliyor: GBL
Fon çekiliyor: IBR
Fon çekiliyor: FYH
Fon çekiliyor: AZJ
Fon çekiliyor: AU1
Fon çekiliyor: BHN
Fon çekiliyor: BYZ
Fon çekiliyor: CBD
Fon çekiliyor: BSC
Fon çekiliyor: BON
Fon çekiliyor: CVL
Fon çekiliyor: DGF
Fon çekiliyor: CAH
Fon çekiliyor: HFR
Fon çekiliyor: CHY
Fon çekiliyor: AJ1
Fon çekiliyor: PAB
Fon çekiliyor: P1A
Fon çekiliyor: SEH
Fon çekiliyor: DA1
Fon çekiliyor: AGA
Fon çekiliyor: TKV
Fon çekiliyor: AGB
Fon çekiliyor: AGG
Fon çekiliyor: AGH
Fon çekiliyor: AGT
Fon çekiliyor: AGD
Fon çekiliyor: BHK
Fon çekiliyor: AGM
Fon çekiliyor: BEO
Fon çekiliyor: BEF
Fon çekiliyor: BEI
Fon çekiliyor: BSR
Fon çekiliyor: BNA
Fon çekiliyor: PRS
Fon çekiliyor: PRC
Fon çekiliyor: BPU
Fon çekiliyor: BPL
Fon çekiliyor: BPF
Fon çekiliyor: BPE
Fon çekiliyor: BPH
Fon çekiliyor: BPK
Fon çekiliyor: BPC
Fon çekiliyor: BNK
Fon çekiliyor: BNB
Fon çekiliyor: BPI
Fon çekiliyor: BPS
Fon çekiliyor: BPJ
Fon çekiliyor: BPN
Fon çekiliyor: BPO
Fon çekiliyor: BNZ
Fon çekiliyor: BPR
Fon çekiliyor: BNL
Fon çekiliyor: BNS
Fon çekiliyor: BZY
Fon çekiliyor: BPG
Fon çekiliyor: BLA
Fon çekiliyor: BLT
Fon çekiliyor: BOS
Fon çekiliyor: BRB
Fon çekiliyor: BP5
Fon çekiliyor: BBN
Fon çekiliyor: BPD
Fon çekiliyor: BBS
Fon çekiliyor: BCO
Fon çekiliyor: BDO
Fon çekiliyor: BFS
Fon çekiliyor: BHA
Fon çekiliyor: BIK
Fon çekiliyor: BMU
Fon çekiliyor: BPZ
Fon çekiliyor: BUC

In [ ]:
import http.client
import json
import pandas as pd
conn = http.client.HTTPSConnection("tefas-api.p.rapidapi.com")

headers = {
    'x-rapidapi-key': "c3c297e087mshf0c09b3c9068e2fp1ae78fjsnf0b02d992e8a",
    'x-rapidapi-host': "tefas-api.p.rapidapi.com"
}

conn.request("GET", "/api/v1/funds/returns?fundType=1&startDate=01.01.2024&endDate=31.12.2024", headers=headers)

res = conn.getresponse()
data = res.read()

print(data.decode("utf-8"))
parsed = json.loads(data.decode("utf-8"))
records = parsed.get("data") if isinstance(parsed, dict) else parsed
if not isinstance(records, list):
    records = [records] if records else []
df = pd.DataFrame(records)
df

{"data":[{"fundCode":"AOY","fundName":"AK PORTFÖY ALTERNATİF ENERJİ YABANCI HİSSE SENEDİ FONU","category":"Hisse Senedi Şemsiye Fonu","returnByDate":-22.6937},{"fundCode":"AFO","fundName":"AK PORTFÖY ALTIN FONU","category":"Kıymetli Madenler Şemsiye Fonu","returnByDate":45.6979},{"fundCode":"PAL","fundName":"AK PORTFÖY ALTINCI SERBEST(DÖVİZ) FON","category":"Serbest Şemsiye Fonu","returnByDate":24.4644},{"fundCode":"AFA","fundName":"AK PORTFÖY AMERİKA YABANCI HİSSE SENEDİ FONU","category":"Hisse Senedi Şemsiye Fonu","returnByDate":46.7721},{"fundCode":"AFV","fundName":"AK PORTFÖY AVRUPA YABANCI HİSSE SENEDİ FONU","category":"Hisse Senedi Şemsiye Fonu","returnByDate":18.2311},{"fundCode":"BNC","fundName":"AK PORTFÖY BEŞİNCİ SERBEST FON","category":"Serbest Şemsiye Fonu"},{"fundCode":"ADP","fundName":"AK PORTFÖY BIST BANKA ENDEKSİ HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":71.6558},{"fundCode":"APJ","fundName":"AK PORTFÖY BIST ŞİRKETLERİ FON SEPETİ FONU","category":"Fon Sepeti Şemsiye Fonu","returnByDate":50.8449},{"fundCode":"AKU","fundName":"AK PORTFÖY BIST 30 ENDEKSİ HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":37.7057},{"fundCode":"ARL","fundName":"AK PORTFÖY BİRİNCİ FON SEPETİ FONU","category":"Fon Sepeti Şemsiye Fonu","returnByDate":54.2715},{"fundCode":"PUC","fundName":"AK PORTFÖY BİRİNCİ KISA VADELİ SERBEST (TL)  FON","category":"Serbest Şemsiye Fonu","returnByDate":60.2037},{"fundCode":"BUY","fundName":"AK PORTFÖY BÜYÜYEN ŞİRKETLER HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":4.5229},{"fundCode":"VAY","fundName":"AK PORTFÖY DEĞER ODAKLI 100 ŞİRKETLERİ HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":36.5776},{"fundCode":"VCY","fundName":"AK PORTFÖY ELEKTRİKLİ VE OTONOM ARAÇ TEKNOLOJİLERİ DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu","returnByDate":13.3888},{"fundCode":"AKE","fundName":"AK PORTFÖY EUROBOND (AMERİKAN DOLARI) BORÇLANMA ARAÇLARI FONU","category":"Borçlanma Araçları Şemsiye Fonu","returnByDate":26.9699},{"fundCode":"ZFB","fundName":"AK PORTFÖY FİNTEK VE BLOKZİNCİRİ TEKNOLOJİLERİ DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu","returnByDate":47.7066},{"fundCode":"GUM","fundName":"AK PORTFÖY GÜMÜŞ FON SEPETI FONU","category":"Fon Sepeti Şemsiye Fonu","returnByDate":42.5672},{"fundCode":"AK3","fundName":"AK PORTFÖY HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":59.8084},{"fundCode":"FUA","fundName":"AK PORTFÖY İHRACATÇI ŞİRKETLER HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":19.9466},{"fundCode":"AGC","fundName":"AK PORTFÖY İKİNCİ DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu","returnByDate":29.6443},{"fundCode":"ARM","fundName":"AK PORTFÖY İKİNCİ FON SEPETİ FONU","category":"Fon Sepeti Şemsiye Fonu","returnByDate":53.8046},{"fundCode":"ALC","fundName":"AK PORTFÖY KAR PAYI ÖDEYEN ŞİRKETLER HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":62.3444},{"fundCode":"MTV","fundName":"AK PORTFÖY METAVERSE VE DİJİTAL YAŞAM TEKNOLOJİLERİ DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu","returnByDate":33.7419},{"fundCode":"ADE","fundName":"AK PORTFÖY MUTLAK GETİRİ HEDEFLİ DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu","returnByDate":54.5603},{"fundCode":"ONK","fundName":"AK PORTFÖY ONİKİNCİ SERBEST (DÖVİZ-AVRO) FON","category":"Serbest Şemsiye Fonu","returnByDate":16.186},{"fundCode":"APT","fundName":"AK PORTFÖY ORTA VADELI BORÇLANMA ARAÇLARI FONU","category":"Borçlanma Araçları Şemsiye Fonu","returnByDate":34.2794},{"fundCode":"AYR","fundName":"AK PORTFÖY ÖZEL SEKTÖR BORÇLANMA ARAÇLARI (TL) FONU","category":"Borçlanma Araçları Şemsiye Fonu","returnByDate":54.8992},{"fundCode":"AIS","fundName":"AK PORTFÖY PARA PİYASASI KATILIM FONU","category":"Katılım Şemsiye Fonu","returnByDate":49.8198},{"fundCode":"AES","fundName":"AK PORTFÖY PETROL YABANCI BYF FON SEPETİ FONU","category":"Fon Sepeti Şemsiye Fonu","returnByDate":22.2976},{"fundCode":"DTZ","fundName":"AK PORTFÖY ROBOTİK TEKNOLOJİLER DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu","returnByDate":29.775},{"fundCode":"AFS","fundName":"AK PORTFÖY SAĞLIK SEKTÖRÜ YABANCI HİSSE SENEDİ FONU","category":"Hisse Senedi Şemsiye Fonu","returnByDate":8.2178},{"fundCode":"TAR","fundName":"AK PORTFÖY TARIM VE GIDA TEKNOLOJİLERİ DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu","returnByDate":15.0573},{"fundCode":"ICZ","fundName":"AK PORTFÖY TEKNOLOJİ ŞİRKETLERİ HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":47.0035},{"fundCode":"TGR","fundName":"AK PORTFÖY TURİZM VE SEYAHAT SEKTÖRÜ DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu","returnByDate":37.6789},{"fundCode":"AK2","fundName":"AK PORTFÖY UZUN VADELİ BORÇLANMA ARAÇLARI FONU","category":"Borçlanma Araçları Şemsiye Fonu","returnByDate":20.2605},{"fundCode":"ODV","fundName":"AK PORTFÖY ÜÇÜNCÜ FON SEPETİ FONU","category":"Fon Sepeti Şemsiye Fonu","returnByDate":52.59},{"fundCode":"BGP","fundName":"AK PORTFÖY ÜÇÜNCÜ PARA PİYASASI (TL) FONU","category":"Para Piyasası Şemsiye Fonu","returnByDate":61.877},{"fundCode":"AFT","fundName":"AK PORTFÖY YENİ TEKNOLOJİLER YABANCI HİSSE SENEDİ FONU","category":"Hisse Senedi Şemsiye Fonu","returnByDate":47.1888},{"fundCode":"AJK","fundName":"AK PORTFÖY 0-5 YIL VADELİ SERBEST (DÖVİZ) FON","category":"Serbest Şemsiye Fonu","returnByDate":17.4868},{"fundCode":"ONN","fundName":"AKTİF PORTFÖY AKTİF ONİKS SERBEST (TL) FON","category":"Serbest Şemsiye Fonu","returnByDate":54.4251},{"fundCode":"MJL","fundName":"AKTİF PORTFÖY AKTİF SERBEST (DÖVİZ-AVRO) FON","category":"Serbest Şemsiye Fonu","returnByDate":15.4193},{"fundCode":"MKG","fundName":"AKTİF PORTFÖY ALTIN KATILIM FONU","category":"Kıymetli Madenler Şemsiye Fonu","returnByDate":50.143},{"fundCode":"MMH","fundName":"AKTİF PORTFÖY BIST 30 ENDEKSİ HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":42.422},{"fundCode":"MJB","fundName":"AKTİF PORTFÖY BİRİNCİ FON SEPETİ FONU","category":"Fon Sepeti Şemsiye Fonu","returnByDate":33.8418},{"fundCode":"ONE","fundName":"AKTİF PORTFÖY BİRİNCİ HİSSE SENEDİ SERBEST (TL) FON (HİSSE SENEDİ YOĞUN FON)","category":"Serbest Şemsiye Fonu","returnByDate":22.2614},{"fundCode":"GLG","fundName":"AKTİF PORTFÖY CAPİTAL HİSSE SENEDİ SERBEST FON (HİSSE SENEDİ YOĞUN FON)","category":"Serbest Şemsiye Fonu","returnByDate":27.8642},{"fundCode":"ESG","fundName":"AKTİF PORTFÖY ESG SÜRDÜRÜLEBİLİRLİK SERBEST FON","category":"Serbest Şemsiye Fonu","returnByDate":34.2522},{"fundCode":"MJG","fundName":"AKTİF PORTFÖY GÜMÜŞ FON SEPETİ FONU","category":"Fon Sepeti Şemsiye Fonu","returnByDate":44.2251},{"fundCode":"ASJ","fundName":"AKTİF PORTFÖY HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":46.3305},{"fundCode":"MPN","fundName":"AKTİF PORTFÖY İKİNCİ AKTİF SERBEST (DÖVİZ) FON","category":"Serbest Şemsiye Fonu","returnByDate":28.8451},{"fundCode":"EYT","fundName":"AKTİF PORTFÖY İKİNCİ FON SEPETİ FONU","category":"Fon Sepeti Şemsiye Fonu","returnByDate":44.0042},{"fundCode":"BUL","fundName":"AKTİF PORTFÖY İNŞAAT SEKTÖRÜ HİSSE SENEDİ SERBEST (TL) FON (HİSSE SENEDİ YOĞUN FON)","category":"Serbest Şemsiye Fonu","returnByDate":1.684},{"fundCode":"MPS","fundName":"AKTİF PORTFÖY KATILIM HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":40.3837},{"fundCode":"MPF","fundName":"AKTİF PORTFÖY KISA VADELİ KİRA SERTİFİKASI KATILIM (TL) FONU","category":"Katılım Şemsiye Fonu","returnByDate":52.0906},{"fundCode":"MPK","fundName":"AKTİF PORTFÖY KİRA SERTİFİKASI KATILIM (TL) FONU","category":"Katılım Şemsiye Fonu","returnByDate":49.5571},{"fundCode":"IDL","fundName":"AKTİF PORTFÖY PARA PİYASASI (TL) FONU","category":"Para Piyasası Şemsiye Fonu","returnByDate":60.9247},{"fundCode":"MTS","fundName":"AKTİF PORTFÖY TARIM VE SÜRDÜRÜLEBİLİRLİK FON SEPETİ FONU","category":"Fon Sepeti Şemsiye Fonu","returnByDate":19.4428},{"fundCode":"CPU","fundName":"AKTİF PORTFÖY TEKNOLOJİ KATILIM FONU","category":"Katılım Şemsiye Fonu","returnByDate":48.9891},{"fundCode":"GLC","fundName":"AKTİF PORTFÖY ÜÇÜNCÜ FON SEPETİ FONU","category":"Fon Sepeti Şemsiye Fonu","returnByDate":49.2469},{"fundCode":"RBA","fundName":"ALBARAKA PORTFÖY BEREKET VAKFI NA DESTEK ALTIN KATILIM FONU","category":"Katılım Şemsiye Fonu","returnByDate":41.0482},{"fundCode":"RBK","fundName":"ALBARAKA PORTFÖY KATILIM FONU","category":"Katılım Şemsiye Fonu","returnByDate":32.4093},{"fundCode":"RBH","fundName":"ALBARAKA PORTFÖY KATILIM HİSSE SENEDİ FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":40.2737},{"fundCode":"PVK","fundName":"ALBARAKA PORTFÖY KISA VADELİ KATILIM SERBEST (TL) FON","category":"Serbest Şemsiye Fonu","returnByDate":56.5626},{"fundCode":"RBV","fundName":"ALBARAKA PORTFÖY KISA VADELİ KİRA SERTİFİKALARI KATILIM (TL) FONU","category":"Katılım Şemsiye Fonu","returnByDate":52.3212},{"fundCode":"RBT","fundName":"ALBARAKA PORTFÖY KİRA SERTİFİKALARI  KATILIM FONU","category":"Katılım Şemsiye Fonu","returnByDate":51.1269},{"fundCode":"LLA","fundName":"ALLBATROSS PORTFÖY AYDIN HİSSE SENEDİ SERBEST (TL) FON (HİSSE SENEDİ YOĞUN FON)","category":"Serbest Şemsiye Fonu","returnByDate":1.2787},{"fundCode":"HVU","fundName":"ALLBATROSS PORTFÖY BİRİNCİ DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu","returnByDate":38.4683},{"fundCode":"BVM","fundName":"ALLBATROSS PORTFÖY BİRİNCİ HİSSE SENEDİ SERBEST (TL) FON (HİSSE SENEDİ YOĞUN FON)","category":"Serbest Şemsiye Fonu","returnByDate":9.7075},{"fundCode":"HVZ","fundName":"ALLBATROSS PORTFÖY BİRİNCİ HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":48.3014},{"fundCode":"HVT","fundName":"ALLBATROSS PORTFÖY BİRİNCİ PARA PİYASASI (TL) FONU","category":"Para Piyasası Şemsiye Fonu","returnByDate":59.3683},{"fundCode":"AS1","fundName":"ALLBATROSS PORTFÖY BİRİNCİ SERBEST (DÖVİZ) FON","category":"Serbest Şemsiye Fonu","returnByDate":24.8072},{"fundCode":"DEF","fundName":"ALLBATROSS PORTFÖY DEFNE SERBEST FON","category":"Serbest Şemsiye Fonu","returnByDate":65.2748},{"fundCode":"GIH","fundName":"ALLBATROSS PORTFÖY GIDA VE İÇECEK SEKTÖRÜ HİSSE SENEDİ FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":15.0022},{"fundCode":"LID","fundName":"ALLBATROSS PORTFÖY İKİNCİ DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu"},{"fundCode":"IHZ","fundName":"ALLBATROSS PORTFÖY İKİNCİ HİSSE SENEDİ SERBEST FON (HİSSE SENEDİ YOĞUN FON)","category":"Serbest Şemsiye Fonu","returnByDate":0.7823},{"fundCode":"IHA","fundName":"ALLBATROSS PORTFÖY İKİNCİ HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":44.6287},{"fundCode":"AOJ","fundName":"ALLBATROSS PORTFÖY İNŞAAT SEKTÖRÜ HİSSE SENEDİ SERBEST (TL) FON (HİSSE SENEDİ YOĞUN FON)","category":"Serbest Şemsiye Fonu","returnByDate":43.0961},{"fundCode":"KHT","fundName":"ALLBATROSS PORTFÖY KARTAL HİSSE SENEDİ SERBEST (TL) FON (HİSSE SENEDİ YOĞUN FON)","category":"Serbest Şemsiye Fonu","returnByDate":31.6005},{"fundCode":"KST","fundName":"ALLBATROSS PORTFÖY KATILIM HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":34.362},{"fundCode":"PRU","fundName":"ALLBATROSS PORTFÖY KISA VADELİ SERBEST (TL) FON","category":"Serbest Şemsiye Fonu","returnByDate":53.2894},{"fundCode":"AEV","fundName":"ALLBATROSS PORTFÖY SANAYİ ŞİRKETLERİ HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":31.0408},{"fundCode":"PKF","fundName":"ATA PORTFÖY ALTIN KATILIM FONU","category":"Katılım Şemsiye Fonu","returnByDate":51.3501},{"fundCode":"THV","fundName":"ATA PORTFÖY BARBAROS HİSSE SENEDİ SERBEST (TL) FON (HİSSE SENEDİ YOĞUN FON)","category":"Serbest Şemsiye Fonu","returnByDate":42.6398},{"fundCode":"AED","fundName":"ATA PORTFÖY BİRİNCİ DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu","returnByDate":46.401},{"fundCode":"AAK","fundName":"ATA PORTFÖY ÇOKLU VARLIK DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu","returnByDate":49.9119},{"fundCode":"AUT","fundName":"ATA PORTFÖY DENGELİ DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu","returnByDate":56.7579},{"fundCode":"ANZ","fundName":"ATA PORTFÖY DÖRDÜNCÜ SERBEST (DÖVİZ) FON","category":"Serbest Şemsiye Fonu","returnByDate":27.2182},{"fundCode":"AAS","fundName":"ATA PORTFÖY FON SEPETİ SERBEST FONU","category":"Serbest Şemsiye Fonu","returnByDate":16.148},{"fundCode":"AAV","fundName":"ATA PORTFÖY İKİNCİ HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":51.3877},{"fundCode":"AYA","fundName":"ATA PORTFÖY KAR PAYI ÖDEYEN HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":38.5273},{"fundCode":"TLZ","fundName":"ATA PORTFÖY KATILIM HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":26.6512},{"fundCode":"DGH","fundName":"ATA PORTFÖY PARA PİYASASI SERBEST (TL) FON","category":"Serbest Şemsiye Fonu","returnByDate":56.0305},{"fundCode":"AAL","fundName":"ATA PORTFÖY PARA PİYASASI (TL) FONU","category":"Para Piyasası Şemsiye Fonu","returnByDate":59.3776},{"fundCode":"RTG","fundName":"ATA PORTFÖY ROBOTİK TEKNOLOJİLERİ DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu","returnByDate":34.2818},{"fundCode":"YLC","fundName":"ATA PORTFÖY TARIM VE GIDA DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu","returnByDate":7.1172},{"fundCode":"AHI","fundName":"ATLAS PORTFÖY BİRİNCİ HİSSE SENEDİ FONU(HİSSE SENEDİ YOĞUN)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":45.9571},{"fundCode":"AHU","fundName":"ATLAS PORTFÖY BİRİNCİ ÖZEL SEKTÖR BORÇLANMA ARAÇLARI FONU","category":"Borçlanma Araçları Şemsiye Fonu","returnByDate":59.6652},{"fundCode":"PFS","fundName":"ATLAS PORTFÖY FON SEPETİ FONU","category":"Fon Sepeti Şemsiye Fonu","returnByDate":48.9334},{"fundCode":"PPT","fundName":"ATLAS PORTFÖY PARA PİYASASI (TL) FONU","category":"Para Piyasası Şemsiye Fonu"},{"fundCode":"DFI","fundName":"ATLAS PORTFÖY SERBEST FON","category":"Serbest Şemsiye Fonu","returnByDate":29.4234},{"fundCode":"AHN","fundName":"ATLAS PORTFÖY SERBEST(DÖVİZ)FON","category":"Serbest Şemsiye Fonu","returnByDate":30.1854},{"fundCode":"BDC","fundName":"AURA PORTFÖY BODRUM SERBEST FON","category":"Serbest Şemsiye Fonu","returnByDate":69.2024},{"fundCode":"IYB","fundName":"AURA PORTFÖY DEĞİŞKEN FONU","category":"Değişken Şemsiye Fonu","returnByDate":36.3229},{"fundCode":"ESP","fundName":"AURA PORTFÖY EMTİA SERBEST FON","category":"Serbest Şemsiye Fonu","returnByDate":-8.8386},{"fundCode":"TLH","fundName":"AURA PORTFÖY HİSSE SENEDİ FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":37.3139},{"fundCode":"TPV","fundName":"AURA PORTFÖY İKİNCİ DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu","returnByDate":34.2346},{"fundCode":"TLE","fundName":"AURA PORTFÖY YABANCI BORÇLANMA ARAÇLARI FONU","category":"Borçlanma Araçları Şemsiye Fonu","returnByDate":30.5924},{"fundCode":"SPE","fundName":"AZIMUT PORTFÖY 5.0 SERBEST (DÖVIZ) FON","category":"Serbest Şemsiye Fonu","returnByDate":32.9749},{"fundCode":"GLS","fundName":"AZİMUT PORTFÖY  KİRA SERTİFİKALARI (SUKUK) KATILIM FONU","category":"Katılım Şemsiye Fonu","returnByDate":50.7094},{"fundCode":"KMF","fundName":"AZİMUT PORTFÖY ALTIN KATILIM FONU","category":"Katılım Şemsiye Fonu","returnByDate":54.8034},{"fundCode":"GMA","fundName":"AZİMUT PORTFÖY ÇOKLU VARLIK DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu","returnByDate":49.0093},{"fundCode":"AHV","fundName":"AZİMUT PORTFÖY DENGELİ FON SEPETİ FONU","category":"Fon Sepeti Şemsiye Fonu","returnByDate":51.926},{"fundCode":"GBZ","fundName":"AZİMUT PORTFÖY EMTİA FON SEPETİ FONU","category":"Fon Sepeti Şemsiye Fonu","returnByDate":21.5897},{"fundCode":"KSK","fundName":"AZİMUT PORTFÖY İKİNCİ PARA PİYASASI KATILIM FONU","category":"Katılım Şemsiye Fonu","returnByDate":53.1232},{"fundCode":"SPN","fundName":"AZİMUT PORTFÖY İSTATİSTİKSEL ARBİTRAJ HİSSE SENEDİ SERBEST FON (HİSSE SENEDİ YOĞUN FON)","category":"Serbest Şemsiye Fonu","returnByDate":52.7982},{"fundCode":"HYP","fundName":"AZİMUT PORTFÖY İVME SERBEST FON","category":"Serbest Şemsiye Fonu","returnByDate":38.5439},{"fundCode":"KTI","fundName":"AZİMUT PORTFÖY KATILIM HİSSE SENEDİ FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":46.9078},{"fundCode":"KVS","fundName":"AZİMUT PORTFÖY KISA VADELİ SERBEST (TL) FON","category":"Serbest Şemsiye Fonu","returnByDate":53.7393},{"fundCode":"PPZ","fundName":"AZİMUT PORTFÖY PARA PİYASASI (TL) FONU","category":"Para Piyasası Şemsiye Fonu","returnByDate":61.3723},{"fundCode":"GBC","fundName":"AZİMUT PORTFÖY YABANCI HİSSE SENEDİ FONU","category":"Hisse Senedi Şemsiye Fonu","returnByDate":32.8647},{"fundCode":"BJD","fundName":"AZİMUT PORTFÖY 13.0 SERBEST (DÖVİZ) FON","category":"Serbest Şemsiye Fonu","returnByDate":21.8304},{"fundCode":"ZMT","fundName":"AZİMUT PORTFÖY 22.0 SERBEST (DÖVİZ-AVRO) FON","category":"Serbest Şemsiye Fonu","returnByDate":19.49},{"fundCode":"FYI","fundName":"AZİMUT PORTFÖY 4.0 SERBEST FON","category":"Serbest Şemsiye Fonu","returnByDate":62.0658},{"fundCode":"PSL","fundName":"AZİMUT PORTFÖY 8.0 SERBEST FON","category":"Serbest Şemsiye Fonu","returnByDate":31.3944},{"fundCode":"GTF","fundName":"AZİMUT PYŞ BİRİNCİ BORÇLANMA ARAÇLARI FONU","category":"Borçlanma Araçları Şemsiye Fonu","returnByDate":50.7218},{"fundCode":"GL1","fundName":"AZİMUT PYŞ BİRİNCİ HİSSE SENEDİ FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":55.2097},{"fundCode":"GSP","fundName":"AZİMUT PYŞ KAR PAYI ÖDEYEN HİSSE SENEDİ FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":60.7764},{"fundCode":"GBL","fundName":"AZİMUT PYŞ KISA VADELİ BORÇLANMA ARAÇLARI FONU","category":"Borçlanma Araçları Şemsiye Fonu","returnByDate":57.5729},{"fundCode":"BIS","fundName":"BV PORTFÖY BİRİNCİ SERBEST FON","category":"Serbest Şemsiye Fonu"},{"fundCode":"BVZ","fundName":"BV PORTFÖY İSTATİSTİKSEL ARBİTRAJ SERBEST (TL) FON","category":"Serbest Şemsiye Fonu","returnByDate":70.8901},{"fundCode":"BHI","fundName":"BV PORTFÖY MUTLAK GETİRİ HEDEFLİ HİSSE SENEDİ SERBEST (TL) FON (HİSSE SENEDİ YOĞUN FON)","category":"Serbest Şemsiye Fonu"},{"fundCode":"BTE","fundName":"BV PORTFÖY OYUN VE TEKNOLOJİ DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu","returnByDate":46.3417},{"fundCode":"BVV","fundName":"BV PORTFÖY TEKNOLOJİ DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu","returnByDate":30.3342},{"fundCode":"DBA","fundName":"DENİZ PORTFÖY ALTIN FONU","category":"Kıymetli Madenler Şemsiye Fonu","returnByDate":53.7441},{"fundCode":"DDA","fundName":"DENİZ PORTFÖY BANKACILIK SEKTÖRÜ HİSSE SENEDİ SERBEST FON (HİSSE SENEDİ YOĞUN FON)","category":"Serbest Şemsiye Fonu","returnByDate":73.7723},{"fundCode":"DZM","fundName":"DENİZ PORTFÖY BEŞİNCİ SERBEST (DÖVİZ) FON","category":"Serbest Şemsiye Fonu","returnByDate":41.0725},{"fundCode":"DTL","fundName":"DENİZ PORTFÖY BIST 100 DIŞI ŞİRKETLER HİSSE SENEDİ (TL) FONU (HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":48.4231},{"fundCode":"DZE","fundName":"DENİZ PORTFÖY BIST 100 ENDEKSİ HİSSE SENEDİ FONU(HİSSE SENEDİ YOĞUN FON)","category":"Hisse Senedi Şemsiye Fonu","returnByDate":38.6559},{"fundCode":"DBP","fundName":"DENİZ PORTFÖY BİRİNCİ DEĞİŞKEN FON","category":"Değişken Şemsiye Fonu","returnByDate":47.2363},{"fundCode":"DPT","fundName":"DENİZ PORTFÖY BİST TEMETTÜ 25 ENDEKSİ HİSSE SENEDİ FONU ( HİSSE SENEDİ YOĞUN FON )","category":"Hisse Senedi Şemsiye Fonu","returnByDate":50.3851},{"fundCode":"DBB","fundName":"D

,fundCode,fundName,category,returnByDate,1w_return,1m_return,3m_return,6m_return,1y_return
0,AOY,AK PORTFÖY ALTERNATİF ENERJİ YABANCI HİSSE SEN...,Hisse Senedi Şemsiye Fonu,-22.6937,NaN,NaN,NaN,NaN,NaN
1,AFO,AK PORTFÖY ALTIN FONU,Kıymetli Madenler Şemsiye Fonu,45.6979,NaN,NaN,NaN,NaN,NaN
2,PAL,AK PORTFÖY ALTINCI SERBEST(DÖVİZ) FON,Serbest Şemsiye Fonu,24.4644,NaN,NaN,NaN,NaN,NaN
3,AFA,AK PORTFÖY AMERİKA YABANCI HİSSE SENEDİ FONU,Hisse Senedi Şemsiye Fonu,46.7721,NaN,NaN,NaN,NaN,NaN
4,AFV,AK PORTFÖY AVRUPA YABANCI HİSSE SENEDİ FONU,Hisse Senedi Şemsiye Fonu,18.2311,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
608,ZP6,ZİRAAT PORTFÖY SEDEF KATILIM SERBEST (DÖVİZ - ...,Serbest Şemsiye Fonu,26.4422,NaN,NaN,NaN,NaN,NaN
609,ZPA,ZİRAAT PORTFÖY SERBEST (DÖVİZ) FON,Serbest Şemsiye Fonu,26.6946,NaN,NaN,NaN,NaN,NaN
610,ZSF,ZİRAAT PORTFÖY S&P/OIC COMCEC (İSEDAK) 50 SHAR...,Hisse Senedi Şemsiye Fonu,27.7327,NaN,NaN,NaN,NaN,NaN
611,ZDD,ZİRAAT PORTFÖY TEMKİNLİ DEĞİŞKEN FON,Değişken Şemsiye Fonu,53.5670,NaN,NaN,NaN,NaN,NaN
612,ZVO,ZİRAAT PORTFÖY ÜÇÜNCÜ SERBEST (TL) FON,Serbest Şemsiye Fonu,4.9183,NaN,NaN,NaN,NaN,NaN

In [8]:
import http.client
import json
import pandas as pd
from datetime import datetime, timedelta

# RapidAPI bağlantı bilgileri
headers = {
    'x-rapidapi-key': "c3c297e087mshf0c09b3c9068e2fp1ae78fjsnf0b02d992e8a",
    'x-rapidapi-host': "tefas-api.p.rapidapi.com"
}
conn = http.client.HTTPSConnection("tefas-api.p.rapidapi.com")

# 📅 Bugünün tarihi
today = datetime.today()

# 🔁 Hesaplanacak periyotlar
periods = {
    "1M": today - timedelta(days=30),
    "3M": today - timedelta(days=90),
    "6M": today - timedelta(days=180),
    "1Y": today - timedelta(days=365)
}

all_data = []

for label, start_date in periods.items():
    start = start_date.strftime("%d.%m.%Y")
    end = today.strftime("%d.%m.%Y")
    print(f"📊 {label} getirileri alınıyor: {start} - {end}")
    
    conn.request("GET", f"/api/v1/funds/returns?fundType=1&startDate={start}&endDate={end}", headers=headers)
    res = conn.getresponse()
    data = json.loads(res.read().decode("utf-8"))
    
    records = data.get("data", [])
    if not isinstance(records, list):
        records = [records] if records else []
    
    df = pd.DataFrame(records)
    df["period"] = label  # hangi dönem olduğunu işaretle
    all_data.append(df)

# 🔗 Tüm periyotları birleştir
result = pd.concat(all_data, ignore_index=True)

print(result.head())

📊 1M getirileri alınıyor: 25.09.2025 - 25.10.2025
📊 3M getirileri alınıyor: 27.07.2025 - 25.10.2025
📊 6M getirileri alınıyor: 28.04.2025 - 25.10.2025
📊 1Y getirileri alınıyor: 25.10.2024 - 25.10.2025
  fundCode                                           fundName  \
0      AOY  AK PORTFÖY ALTERNATİF ENERJİ YABANCI HİSSE SEN...
1      AFO                              AK PORTFÖY ALTIN FONU
2      PAL              AK PORTFÖY ALTINCI SERBEST(DÖVİZ) FON
3      AFA       AK PORTFÖY AMERİKA YABANCI HİSSE SENEDİ FONU
4      AFV        AK PORTFÖY AVRUPA YABANCI HİSSE SENEDİ FONU

                         category  returnByDate period
0       Hisse Senedi Şemsiye Fonu        7.9185     1M
1  Kıymetli Madenler Şemsiye Fonu       14.0505     1M
2            Serbest Şemsiye Fonu        1.6250     1M
3       Hisse Senedi Şemsiye Fonu        1.3945     1M
4       Hisse Senedi Şemsiye Fonu        3.9065     1M

In [14]:
import yfinance as yf
print('yfinance version:', yf.__version__)
print()

# Test 1: Basit bir ticker
print('Test 1: AAPL (Apple)')
try:
    aapl = yf.download('AAPL', start='2024-10-01', end='2024-10-25', progress=False)
    print(f'✅ AAPL: {len(aapl)} satır veri')
    print(aapl.head(2))
except Exception as e:
    print(f'❌ AAPL hatası: {e}')

print()
print('Test 2: BIST ticker (GARAN.IS)')
try:
    garan = yf.download('GARAN.IS', start='2024-10-01', end='2024-10-25', progress=False)
    print(f'✅ GARAN.IS: {len(garan)} satır veri')
    print(garan.head(2))
except Exception as e:
    print(f'❌ GARAN.IS hatası: {e}')

!pip list

Failed to get ticker 'AAPL' reason: Expecting value: line 1 column 1 (char 0)

1 Failed download:
['AAPL']: YFTzMissingError('$%ticker%: possibly delisted; no timezone found')

1 Failed download:
['AAPL']: YFTzMissingError('$%ticker%: possibly delisted; no timezone found')
Failed to get ticker 'GARAN.IS' reason: Expecting value: line 1 column 1 (char 0)

1 Failed download:
['GARAN.IS']: YFTzMissingError('$%ticker%: possibly delisted; no timezone found')
Failed to get ticker 'GARAN.IS' reason: Expecting value: line 1 column 1 (char 0)

1 Failed download:
['GARAN.IS']: YFTzMissingError('$%ticker%: possibly delisted; no timezone found')

yfinance version: 0.2.48

Test 1: AAPL (Apple)
✅ AAPL: 0 satır veri
Empty DataFrame
Columns: [(Adj Close, AAPL), (Close, AAPL), (High, AAPL), (Low, AAPL), (Open, AAPL), (Volume, AAPL)]
Index: []

Test 2: BIST ticker (GARAN.IS)
✅ GARAN.IS: 0 satır veri
Empty DataFrame
Columns: [(Adj Close, GARAN.IS), (Close, GARAN.IS), (High, GARAN.IS), (Low, GARAN.IS), (Open, GARAN.IS), (Volume, GARAN.IS)]
Index: []
Package            Version     Location
------------------ ----------- -----------------------------------------
appdirs            1.4.4
APScheduler        3.8.1
asgiref            3.8.1
asttokens          3.0.0
beautifulsoup4     4.14.2
certifi            2024.2.2
cffi               2.0.0
charset-normalizer 3.3.2
comm               0.2.3
curl_cffi          0.13.0
debugpy            1.8.17
decorator          5.2.1
Django             4.2.11
django-apscheduler 0.6.0
exceptiongroup     1.3.0
executing          2.2.1
frozendict         2.4.6
html5lib           1.1
idna               3.6
importlib_metadata 8.7.0
ipykernel          6.31.0
ipython            8.18.1
jedi               0.19.2
jupyter_client     8.6.3
jupyter_core       5.8.1
lxml               5.1.0
matplotlib-inline  0.2.1
multitasking       0.0.11
nest-asyncio       1.6.0
numpy              1.24.3
packaging          25.0
pandas             2.0.3
parso              0.8.5
peewee             3.18.2
pexpect            4.9.0
pip                21.2.3
platformdirs       4.5.0
prompt_toolkit     3.0.52
protobuf           6.33.0
psutil             7.1.2
psycopg2-binary    2.8.6
ptyprocess         0.7.0
pure_eval          0.2.3
pycparser          2.23
Pygments           2.19.2
python-dateutil    2.9.0.post0
pytz               2024.1
pyzmq              27.1.0
requests           2.31.0
setuptools         53.0.0
six                1.16.0
soupsieve          2.8
sqlparse           0.4.4
stack-data         0.6.3
stock-collector    1.0.0       /home/volkan/repos/Stock_Collector_Django
tornado            6.5.2
traitlets          5.14.3
typing_extensions  4.10.0
tzdata             2025.2
tzlocal            2.1
urllib3            2.2.1
wcwidth            0.2.14
webencodings       0.5.1
websockets         15.0.1
yfinance           0.2.66
zipp               3.23.0
Package            Version     Location
------------------ ----------- -----------------------------------------
appdirs            1.4.4
APScheduler        3.8.1
asgiref            3.8.1
asttokens          3.0.0
beautifulsoup4     4.14.2
certifi            2024.2.2
cffi               2.0.0
charset-normalizer 3.3.2
comm               0.2.3
curl_cffi          0.13.0
debugpy            1.8.17
decorator          5.2.1
Django             4.2.11
django-apscheduler 0.6.0
exceptiongroup     1.3.0
executing          2.2.1
frozendict         2.4.6
html5lib           1.1
idna               3.6
importlib_metadata 8.7.0
ipykernel          6.31.0
ipython            8.18.1
jedi               0.19.2
jupyter_client     8.6.3
jupyter_core       5.8.1
lxml               5.1.0
matplotlib-inline  0.2.1
multitasking       0.0.11
nest-asyncio       1.6.0
numpy              1.24.3
packaging          25.0
pandas             2.0.3
parso              0.8.5
peewee             3.18.2
pexpect            4.9.0
pip                21.2.3
platformdirs       4.5.0
prompt_toolkit     3.0.52
protobuf           6.33.0
psutil             7.1.2
psycopg2-binary    2.8.6
ptyprocess         0.7.0
pure_eval          0.2.3
pycparser          2.23
Pygments           2.19.2
python-dateutil    2.9.0.post0
pytz               2024.1
pyzmq              27.1.0
requests           2.31.0
setuptools         53.0.0
six                1.16.0
soupsieve          2.8
sqlparse           0.4.4
stack-data         0.6.3
stock-collector    1.0.0       /home/volkan/repos/Stock_Collector_Django
tornado            6.5.2
traitlets          5.14.3
typing_extensions  4.10.0
tzdata             2025.2
tzlocal            2.1
urllib3            2.2.1
wcwidth            0.2.14
webencodings       0.5.1
websockets         15.0.1
yfinance           0.2.66
zipp               3.23.0

In [15]:
import yfinance as yf
import pandas as pd
from datetime import datetime

def get_stock_data_safe(ticker, start_date, end_date, retries=3):
    """
    Production-ready yfinance veri çekme fonksiyonu
    
    Args:
        ticker: Hisse sembolü (AAPL, GARAN.IS, etc.)
        start_date: YYYY-MM-DD formatında
        end_date: YYYY-MM-DD formatında
        retries: Deneme sayısı
    
    Returns:
        DataFrame veya None
    """
    for attempt in range(retries):
        try:
            # Ticker objesi oluştur
            stock = yf.Ticker(ticker)
            
            # Veri çek
            df = stock.history(start=start_date, end=end_date)
            
            if df.empty:
                print(f"⚠️ {ticker}: Veri boş (delisted olabilir)")
                return None
            
            # Index'i sütun yap
            df = df.reset_index()
            
            # Ticker kolonu ekle
            df['ticker'] = ticker
            
            print(f"✅ {ticker}: {len(df)} satır veri")
            return df
            
        except Exception as e:
            if attempt < retries - 1:
                print(f"⚠️ {ticker}: Hata (Deneme {attempt + 1}/{retries}), tekrar deneniyor...")
                continue
            else:
                print(f"❌ {ticker}: {str(e)}")
                return None
    
    return None

# TEST
print("🧪 Production-ready fonksiyon testi:")
print("=" * 60)

result = get_stock_data_safe('AAPL', '2024-10-01', '2024-10-25')
if result is not None:
    print("\nSONUÇ:")
    print(result.head())
    print(f"\nKolonlar: {result.columns.tolist()}")

Failed to get ticker 'AAPL' reason: Expecting value: line 1 column 1 (char 0)
$AAPL: possibly delisted; no timezone found
$AAPL: possibly delisted; no timezone found

🧪 Production-ready fonksiyon testi:
============================================================
⚠️ AAPL: Veri boş (delisted olabilir)

In [16]:
import yfinance as yf

print("📊 Yöntem 3: BIST Hisseleri (.IS uzantısı)")
print("=" * 60)

# BIST hisseleri için .IS uzantısı gerekli
bist_ticker = yf.Ticker("GARAN.IS")
hist = bist_ticker.history(start="2024-10-01", end="2024-10-25")

print(f"\n✅ GARAN.IS:")
print(f"Satır sayısı: {len(hist)}")
print(hist.head())

# Birden fazla BIST hissesi
bist_tickers = ['GARAN.IS', 'THYAO.IS', 'ISCTR.IS']
bist_data = yf.download(bist_tickers, start='2024-10-01', end='2024-10-25', group_by='ticker')

print(f"\n✅ Çoklu BIST: {bist_data.shape}")
print("\nGARAN.IS:")
print(bist_data['GARAN.IS'].head())

Failed to get ticker 'GARAN.IS' reason: Expecting value: line 1 column 1 (char 0)
$GARAN.IS: possibly delisted; no timezone found
$GARAN.IS: possibly delisted; no timezone found
Failed to get ticker 'GARAN.IS' reason: Expecting value: line 1 column 1 (char 0)
Failed to get ticker 'THYAO.IS' reason: Expecting value: line 1 column 1 (char 0)
Failed to get ticker 'ISCTR.IS' reason: Expecting value: line 1 column 1 (char 0)
[*********************100%***********************]  3 of 3 completedFailed to get ticker 'GARAN.IS' reason: Expecting value: line 1 column 1 (char 0)
Failed to get ticker 'THYAO.IS' reason: Expecting value: line 1 column 1 (char 0)
Failed to get ticker 'ISCTR.IS' reason: Expecting value: line 1 column 1 (char 0)
[*********************100%***********************]  3 of 3 completed

3 Failed downloads:
['GARAN.IS', 'THYAO.IS', 'ISCTR.IS']: YFTzMissingError('$%ticker%: possibly delisted; no timezone found')


3 Failed downloads:
['GARAN.IS', 'THYAO.IS', 'ISCTR.IS']: YFTzMissingError('$%ticker%: possibly delisted; no timezone found')

📊 Yöntem 3: BIST Hisseleri (.IS uzantısı)
============================================================

✅ GARAN.IS:
Satır sayısı: 0
Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

✅ Çoklu BIST: (0, 18)

GARAN.IS:
Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

In [12]:
import yfinance as yf

print("📊 Yöntem 2: yf.download() - Çoklu Ticker")
print("=" * 60)

# Birden fazla ticker
tickers = ['AAPL', 'MSFT', 'GOOGL']
data = yf.download(tickers, start='2024-10-01', end='2024-10-25', group_by='ticker')

print(f"\n✅ Toplam veri: {data.shape}")
print("\nAAPL verileri:")
print(data['AAPL'].head())

Failed to get ticker 'AAPL' reason: Expecting value: line 1 column 1 (char 0)

📊 Yöntem 2: yf.download() - Çoklu Ticker
============================================================

Failed to get ticker 'MSFT' reason: Expecting value: line 1 column 1 (char 0)
[                       0%                       ]Failed to get ticker 'GOOGL' reason: Expecting value: line 1 column 1 (char 0)
[*********************100%***********************]  2 of 3 completed

3 Failed downloads:
['AAPL', 'MSFT', 'GOOGL']: YFTzMissingError('$%ticker%: possibly delisted; no timezone found')

✅ Toplam veri: (0, 18)

AAPL verileri:
Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

In [13]:
import yfinance as yf
import pandas as pd

print("📊 Yöntem 1: Ticker Object Kullanımı (ÖNERİLEN)")
print("=" * 60)

# Tek bir ticker için
ticker = yf.Ticker("AAPL")

# Son 1 aylık veri
hist = ticker.history(period="1mo")
print(f"\n✅ AAPL - Son 1 ay:")
print(f"Satır sayısı: {len(hist)}")
print(hist.head())

# Tarih aralığı ile
hist2 = ticker.history(start="2024-10-01", end="2024-10-25")
print(f"\n✅ AAPL - Belirli tarih aralığı:")
print(f"Satır sayısı: {len(hist2)}")
print(hist2.head())

Failed to get ticker 'AAPL' reason: Expecting value: line 1 column 1 (char 0)

📊 Yöntem 1: Ticker Object Kullanımı (ÖNERİLEN)
============================================================

$AAPL: possibly delisted; no price data found  (period=1mo)
$AAPL: possibly delisted; no timezone found

✅ AAPL - Son 1 ay:
Satır sayısı: 0
Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

✅ AAPL - Belirli tarih aralığı:
Satır sayısı: 0
Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

# ✅ yfinance 0.2.38 - Çalışan Örnekler

yfinance dokümantasyonuna göre doğru kullanım şekli:

# 🧪 yfinance 0.2.66 TEST

En son versiyon ile test edelim:

# 🔄 pandas-datareader Alternatifi

yfinance yerine daha stabil bir çözüm:

In [21]:
!pip install pandas-datareader -q

In [22]:
import pandas_datareader as pdr
from datetime import datetime

print("📊 pandas-datareader TEST")
print("=" * 60)

# Test 1: Yahoo Finance via pandas-datareader
print("\n✅ Test 1: AAPL (Apple) - Yahoo Finance")
try:
    aapl = pdr.get_data_yahoo('AAPL', start='2024-10-01', end='2024-10-25')
    print(f"Satır sayısı: {len(aapl)}")
    print(aapl.head())
except Exception as e:
    print(f"❌ Hata: {e}")

# Test 2: BIST ticker
print("\n✅ Test 2: GARAN.IS (Garanti) - Yahoo Finance")
try:
    garan = pdr.get_data_yahoo('GARAN.IS', start='2024-10-01', end='2024-10-25')
    print(f"Satır sayısı: {len(garan)}")
    print(garan.head())
except Exception as e:
    print(f"❌ Hata: {e}")

# Test 3: MSFT
print("\n✅ Test 3: MSFT (Microsoft)")
try:
    msft = pdr.get_data_yahoo('MSFT', start='2024-10-01', end='2024-10-25')
    print(f"Satır sayısı: {len(msft)}")
    print(msft.head())
except Exception as e:
    print(f"❌ Hata: {e}")

📊 pandas-datareader TEST
============================================================

✅ Test 1: AAPL (Apple) - Yahoo Finance
❌ Hata: Unable to read URL: https://finance.yahoo.com/quote/AAPL/history?period1=1727748000&period2=1729907999&interval=1d&frequency=1d&filter=history
Response Text:
b'<html><meta charset=\'utf-8\'>\n<script>\nif(window != window.top){\ndocument.write(\'<p>Content is currently unavailable.</p><img src="//geo.yahoo.com/p?s=1197757039&t=\'\n    + new Date().getTime() + \'&_R=\'\n    + encodeURIComponent(document.referrer)\n    + \'&err=404\'\n    + \'" width="0px" height="0px"/>\');\n}else{\nwindow.location.replace(\'https://\' + window.location.host + \'/?err=404\');\n}\n</script>\n<noscript>\n<META http-equiv="refresh" content="0;URL=https://finance.yahoo.com/?err=404">\n</noscript></html>'

✅ Test 2: GARAN.IS (Garanti) - Yahoo Finance
❌ Hata: Unable to read URL: https://finance.yahoo.com/quote/GARAN.IS/history?period1=1727748000&period2=1729907999&interval=1d&frequency=1d&filter=history
Response Text:
b'<html><meta charset=\'utf-8\'>\n<script>\nif(window != window.top){\ndocument.write(\'<p>Content is currently unavailable.</p><img src="//geo.yahoo.com/p?s=1197757039&t=\'\n    + new Date().getTime() + \'&_R=\'\n    + encodeURIComponent(document.referrer)\n    + \'&err=404\'\n    + \'" width="0px" height="0px"/>\');\n}else{\nwindow.location.replace(\'https://\' + window.location.host + \'/?err=404\');\n}\n</script>\n<noscript>\n<META http-equiv="refresh" content="0;URL=https://finance.yahoo.com/?err=404">\n</noscript></html>'

✅ Test 3: MSFT (Microsoft)
❌ Hata: Unable to read URL: https://finance.yahoo.com/quote/MSFT/history?period1=1727748000&period2=1729907999&interval=1d&frequency=1d&filter=history
Response Text:
b'<html><meta charset=\'utf-8\'>\n<script>\nif(window != window.top){\ndocument.write(\'<p>Content is currently unavailable.</p><img src="//geo.yahoo.com/p?s=1197757039&t=\'\n    + new Date().getTime() + \'&_R=\'\n    + encodeURIComponent(document.referrer)\n    + \'&err=404\'\n    + \'" width="0px" height="0px"/>\');\n}else{\nwindow.location.replace(\'https://\' + window.location.host + \'/?err=404\');\n}\n</script>\n<noscript>\n<META http-equiv="refresh" content="0;URL=https://finance.yahoo.com/?err=404">\n</noscript></html><html><meta charset=\'utf-8\'>\n<script>\nif(window != window.top){\ndocument.write(\'<p>Content is currently unavailable.</p><img src="//geo.yahoo.com/p?s=1197757039&t=\'\n    + new Date().getTime() + \'&_R=\'\n    + encodeURIComponent(document.referrer)\n    + \'&err=404\'\n    + \'" width="0px" height="0px"/>\');\n}else{\nwindow.location.replace(\'https://\' + window.location.host + \'/?err=404\');\n}\n</script>\n<noscript>\n<META http-equiv="refresh" content="0;URL=https://finance.yahoo.com/?err=404">\n</noscript></html>'

In [23]:
!pip install yfinance

Requirement already satisfied: yfinance in ./venv/lib/python3.9/site-packages (0.2.66)
Requirement already satisfied: beautifulsoup4>=4.11.1 in ./venv/lib/python3.9/site-packages/beautifulsoup4-4.14.2-py3.9.egg (from yfinance) (4.14.2)
Requirement already satisfied: frozendict>=2.3.4 in ./venv/lib/python3.9/site-packages/frozendict-2.4.6-py3.9-linux-x86_64.egg (from yfinance) (2.4.6)
Requirement already satisfied: pytz>=2022.5 in ./venv/lib/python3.9/site-packages/pytz-2024.1-py3.9.egg (from yfinance) (2024.1)
Requirement already satisfied: platformdirs>=2.0.0 in ./venv/lib/python3.9/site-packages/platformdirs-4.5.0-py3.9.egg (from yfinance) (4.5.0)
Requirement already satisfied: curl_cffi>=0.7 in ./venv/lib/python3.9/site-packages (from yfinance) (0.13.0)
Requirement already satisfied: websockets>=13.0 in ./venv/lib/python3.9/site-packages (from yfinance) (15.0.1)
Requirement already satisfied: pandas>=1.3.0 in ./venv/lib/python3.9/site-packages/pandas-2.0.3-py3.9-linux-x86_64.egg (from yfinance) (2.0.3)
Requirement already satisfied: multitasking>=0.0.7 in ./venv/lib/python3.9/site-packages/multitasking-0.0.11-py3.9.egg (from yfinance) (0.0.11)
Requirement already satisfied: requests>=2.31 in ./venv/lib/python3.9/site-packages/requests-2.31.0-py3.9.egg (from yfinance) (2.31.0)
Requirement already satisfied: protobuf>=3.19.0 in ./venv/lib/python3.9/site-packages (from yfinance) (6.33.0)
Requirement already satisfied: numpy>=1.16.5 in ./venv/lib/python3.9/site-packages/numpy-1.24.3-py3.9-linux-x86_64.egg (from yfinance) (1.24.3)
Requirement already satisfied: peewee>=3.16.2 in ./venv/lib/python3.9/site-packages/peewee-3.18.2-py3.9.egg (from yfinance) (3.18.2)
Requirement already satisfied: soupsieve>1.2 in ./venv/lib/python3.9/site-packages/soupsieve-2.8-py3.9.egg (from beautifulsoup4>=4.11.1->yfinance) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in ./venv/lib/python3.9/site-packages/typing_extensions-4.10.0-py3.9.egg (from beautifulsoup4>=4.11.1->yfinance) (4.10.0)
Requirement already satisfied: certifi>=2024.2.2 in ./venv/lib/python3.9/site-packages/certifi-2024.2.2-py3.9.egg (from curl_cffi>=0.7->yfinance) (2024.2.2)
Requirement already satisfied: cffi>=1.12.0 in ./venv/lib/python3.9/site-packages (from curl_cffi>=0.7->yfinance) (2.0.0)
Requirement already satisfied: pycparser in ./venv/lib/python3.9/site-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance) (2.23)
Requirement already satisfied: certifi>=2024.2.2 in ./venv/lib/python3.9/site-packages/certifi-2024.2.2-py3.9.egg (from curl_cffi>=0.7->yfinance) (2024.2.2)
Requirement already satisfied: cffi>=1.12.0 in ./venv/lib/python3.9/site-packages (from curl_cffi>=0.7->yfinance) (2.0.0)
Requirement already satisfied: pycparser in ./venv/lib/python3.9/site-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance) (2.23)
Requirement already satisfied: python-dateutil>=2.8.2 in ./venv/lib/python3.9/site-packages/python_dateutil-2.9.0.post0-py3.9.egg (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.1 in ./venv/lib/python3.9/site-packages/tzdata-2025.2-py3.9.egg (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.9/site-packages/six-1.16.0-py3.9.egg (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in ./venv/lib/python3.9/site-packages/charset_normalizer-3.3.2-py3.9-linux-x86_64.egg (from requests>=2.31->yfinance) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in ./venv/lib/python3.9/site-packages/idna-3.6-py3.9.egg (from requests>=2.31->yfinance) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./venv/lib/python3.9/site-packages/urllib3-2.2.1-py3.9.egg (from requests>=2.31->yfinance) (2.2.1)
Requirement already satisfied: python-dateutil>=2.8.2 in ./venv/lib/python3.9/site-packages/python_dateutil-2.9.0.post0-py3.9.egg (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.1 in ./venv/lib/python3.9/site-packages/tzdata-2025.2-py3.9.egg (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.9/site-packages/six-1.16.0-py3.9.egg (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in ./venv/lib/python3.9/site-packages/charset_normalizer-3.3.2-py3.9-linux-x86_64.egg (from requests>=2.31->yfinance) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in ./venv/lib/python3.9/site-packages/idna-3.6-py3.9.egg (from requests>=2.31->yfinance) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./venv/lib/python3.9/site-packages/urllib3-2.2.1-py3.9.egg (from requests>=2.31->yfinance) (2.2.1)

In [30]:
import yfinance as yf

ticker = yf.Ticker("MSFT")
print(ticker.fast_info)
hist = ticker.history(period="3d")
print(hist)
tickers = ["MSFT", "ACSEL.IS", "ADELA.IS"]
for t in tickers:
    try:
        data = yf.Ticker(t).history(period="1d")
        if data.empty:
            print(f"{t} veri yok veya delisted")
        else:
            print(f"{t} için veri mevcut")
    except Exception as e:
        print(f"{t} hatalı: {e}")

Failed to get ticker 'MSFT' reason: Expecting value: line 1 column 1 (char 0)

lazy-loading dict with keys = ['currency', 'dayHigh', 'dayLow', 'exchange', 'fiftyDayAverage', 'lastPrice', 'lastVolume', 'marketCap', 'open', 'previousClose', 'quoteType', 'regularMarketPreviousClose', 'shares', 'tenDayAverageVolume', 'threeMonthAverageVolume', 'timezone', 'twoHundredDayAverage', 'yearChange', 'yearHigh', 'yearLow']

$MSFT: possibly delisted; no price data found  (period=3d)
Failed to get ticker 'MSFT' reason: Expecting value: line 1 column 1 (char 0)
Failed to get ticker 'MSFT' reason: Expecting value: line 1 column 1 (char 0)

Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

$MSFT: possibly delisted; no price data found  (period=1d)
Failed to get ticker 'ACSEL.IS' reason: Expecting value: line 1 column 1 (char 0)
Failed to get ticker 'ACSEL.IS' reason: Expecting value: line 1 column 1 (char 0)

MSFT veri yok veya delisted

$ACSEL.IS: possibly delisted; no price data found  (period=1d)
Failed to get ticker 'ADELA.IS' reason: Expecting value: line 1 column 1 (char 0)
Failed to get ticker 'ADELA.IS' reason: Expecting value: line 1 column 1 (char 0)

ACSEL.IS veri yok veya delisted

$ADELA.IS: possibly delisted; no price data found  (period=1d)

ADELA.IS veri yok veya delisted

# 🚀 Alpha Vantage API - Çalışan Çözüm

Yahoo Finance artık çalışmıyor. Alpha Vantage'e geçiyoruz:
- ✅ Ücretsiz 500 requests/gün
- ✅ Stabil ve güvenilir
- ✅ BIST desteği var

In [31]:
!pip install alpha-vantage -q

In [32]:
from alpha_vantage.timeseries import TimeSeries
import pandas as pd

# Demo API key (günde 25 request limit - ücretsiz hesap aç: https://www.alphavantage.co/support/#api-key)
API_KEY = 'demo'  # Bu demo key, sadece test için. Kendi key'ini al!

print("📊 Alpha Vantage TEST")
print("=" * 60)

# Test 1: AAPL (Apple)
print("\n✅ Test 1: AAPL (Apple)")
try:
    ts = TimeSeries(key=API_KEY, output_format='pandas')
    data, meta_data = ts.get_daily(symbol='AAPL', outputsize='compact')
    print(f"Satır sayısı: {len(data)}")
    print("\nİlk 5 satır:")
    print(data.head())
    print(f"\nKolonlar: {data.columns.tolist()}")
except Exception as e:
    print(f"❌ Hata: {e}")

print("\n" + "="*60)
print("⚠️  Demo API key kullanıyoruz - sadece IBM ticker için çalışır")
print("📝 Ücretsiz API key al: https://www.alphavantage.co/support/#api-key")
print("🎯 500 request/gün bedava!")

📊 Alpha Vantage TEST
============================================================

✅ Test 1: AAPL (Apple)
❌ Hata: The **demo** API key is for demo purposes only. Please claim your free API key at (https://www.alphavantage.co/support/#api-key) to explore our full API offerings. It takes fewer than 20 seconds.

============================================================
⚠️  Demo API key kullanıyoruz - sadece IBM ticker için çalışır
📝 Ücretsiz API key al: https://www.alphavantage.co/support/#api-key
🎯 500 request/gün bedava!

In [33]:
# 🔑 Kendi API key'ini buraya yapıştır
YOUR_API_KEY = 'O5Z5HIUECULLKZZA'

from alpha_vantage.timeseries import TimeSeries
import pandas as pd
from datetime import datetime, timedelta

def get_stock_data_alphavantage(ticker, api_key, days=100):
    """
    Alpha Vantage ile hisse verisi çek
    
    Args:
        ticker: Hisse sembolü (AAPL, MSFT, GARAN.IS vb.)
        api_key: Alpha Vantage API key
        days: Kaç günlük veri (100 = compact, 5000+ = full)
    
    Returns:
        DataFrame with OHLCV data
    """
    try:
        ts = TimeSeries(key=api_key, output_format='pandas')
        
        # compact = son 100 gün, full = 20+ yıl
        outputsize = 'compact' if days <= 100 else 'full'
        
        # Günlük veri çek
        data, meta = ts.get_daily(symbol=ticker, outputsize=outputsize)
        
        # Kolon isimlerini düzenle
        data.columns = ['Open', 'High', 'Low', 'Close', 'Volume']
        
        # Index'i reset et (date kolonu yap)
        data = data.reset_index()
        data.rename(columns={'date': 'Date'}, inplace=True)
        
        # Son N günü filtrele
        cutoff_date = datetime.now() - timedelta(days=days)
        data['Date'] = pd.to_datetime(data['Date'])
        data = data[data['Date'] >= cutoff_date]
        
        # Ticker ekle
        data['ticker'] = ticker
        
        print(f"✅ {ticker}: {len(data)} satır veri")
        return data
        
    except Exception as e:
        print(f"❌ {ticker}: {str(e)}")
        return None

# TEST (API key aldıktan sonra çalıştır)
if YOUR_API_KEY != 'BURAYA_KENDI_API_KEYINI_YAZ':
    print("🧪 Alpha Vantage Production Test:")
    print("=" * 60)
    
    # Test 1: AAPL
    aapl_data = get_stock_data_alphavantage('AAPL', YOUR_API_KEY, days=30)
    if aapl_data is not None:
        print("\nSONUÇ:")
        print(aapl_data.head())
else:
    print("⚠️  Önce API key'ini yapıştır!")

🧪 Alpha Vantage Production Test:
============================================================
✅ AAPL: 21 satır veri

SONUÇ:
        Date     Open     High       Low   Close      Volume ticker
0 2025-10-24  261.190  264.130  259.1800  262.82  38253717.0   AAPL
1 2025-10-23  259.940  260.620  258.0101  259.58  32754941.0   AAPL
2 2025-10-22  262.650  262.850  255.4300  258.45  45015254.0   AAPL
3 2025-10-21  261.880  265.290  261.8300  262.77  46695948.0   AAPL
4 2025-10-20  255.885  264.375  255.6300  262.24  90483029.0   AAPL
✅ AAPL: 21 satır veri

SONUÇ:
        Date     Open     High       Low   Close      Volume ticker
0 2025-10-24  261.190  264.130  259.1800  262.82  38253717.0   AAPL
1 2025-10-23  259.940  260.620  258.0101  259.58  32754941.0   AAPL
2 2025-10-22  262.650  262.850  255.4300  258.45  45015254.0   AAPL
3 2025-10-21  261.880  265.290  261.8300  262.77  46695948.0   AAPL
4 2025-10-20  255.885  264.375  255.6300  262.24  90483029.0   AAPL